#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (44 * xMult), yPos)] = color;
	Result[int2(xPos + (45 * xMult), yPos)] = color;
	Result[int2(xPos + (44 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos, yPos - (25 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos, yPos - (26 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (36 * yMult))] = color;
}