#pragma kernel CSMain

RWTexture2D<float4> Result;
RWTexture2D<float4> PreResult;

int xPos;
int yPos;

int radius;

int dispatchSize;

float4 color;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    for (int y = (int) (id.y + yPos - radius); y <= (int) (yPos + radius); y += dispatchSize)
    {
        for (int x = (int) (id.x + xPos - radius); x <= (int) (xPos + radius); x += dispatchSize)
        {
            int xPow = pow(x - xPos, 2);
            int yPow = pow(y - yPos, 2);
            int rPow = pow(radius, 2);
            
            if (xPow + yPow >= rPow - radius && xPow + yPow <= rPow + radius)
            {
                Result[int2(x, y)] = color;
                PreResult[int2(x, y)] = color;
            }
        }
    }
}