#pragma kernel CSMain

RWTexture2D<float4> Result;
RWTexture2D<float4> PreResult;

int xPos;
int yPos;

int radius;

float4 color;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_GroupThreadID)
{
    for (int y = (int) (id.y + yPos - radius); y < (int) (yPos + radius); y += 8)
    {
        for (int x = (int) (id.x + xPos - radius); x < (int) (xPos + radius); x += 8)
        {
            Result[int2(x, y)] = color;
            PreResult[int2(x, y)] = color;
        }
    }
}