#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 yellow = float4(1, 1, 0, 1);
    
    // Start cap
    Result[int2(xPos, yPos)] = yellow;
    
    // Top line
    Result[int2(xPos + 1, yPos + 1)] = yellow;
    Result[int2(xPos + 2, yPos + 1)] = yellow;
    Result[int2(xPos + 3, yPos + 1)] = yellow;
    Result[int2(xPos + 4, yPos + 1)] = yellow;
    Result[int2(xPos + 5, yPos + 1)] = yellow;
    
    // Bottom line
    Result[int2(xPos + 1, yPos - 1)] = yellow;
    Result[int2(xPos + 2, yPos - 1)] = yellow;
    Result[int2(xPos + 3, yPos - 1)] = yellow;
    Result[int2(xPos + 4, yPos - 1)] = yellow;
    Result[int2(xPos + 5, yPos - 1)] = yellow;
    
    // End cap
    Result[int2(xPos + 6, yPos)] = yellow;
    
}