#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

bool left;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 red = float4(1, 0, 0, 1);
    float4 blue = float4(0, 0, 1, 1);
    
    if (left)
    {
        Result[int2(xPos + 1, yPos)] = red;
        Result[int2(xPos, yPos)] = blue;
    }
    else
    {
        Result[int2(xPos - 1, yPos)] = red;
        Result[int2(xPos, yPos)] = blue;
    }
}