#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 49, yPos)] = color;
	Result[int2(xPos + 48, yPos - 1)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 50, yPos - 2)] = color;
	Result[int2(xPos + 59, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos + 59, yPos - 3)] = color;
	Result[int2(xPos + 60, yPos - 3)] = color;
	Result[int2(xPos + 63, yPos - 3)] = color;
	Result[int2(xPos + 64, yPos - 3)] = color;
	Result[int2(xPos + 65, yPos - 3)] = color;
	Result[int2(xPos + 60, yPos - 4)] = color;
	Result[int2(xPos + 63, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 64, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 48, yPos - 9)] = color;
	Result[int2(xPos + 49, yPos - 9)] = color;
	Result[int2(xPos + 53, yPos - 9)] = color;
	Result[int2(xPos + 54, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 10)] = color;
	Result[int2(xPos + 40, yPos - 10)] = color;
	Result[int2(xPos + 41, yPos - 10)] = color;
	Result[int2(xPos + 47, yPos - 10)] = color;
	Result[int2(xPos + 50, yPos - 10)] = color;
	Result[int2(xPos + 52, yPos - 10)] = color;
	Result[int2(xPos + 55, yPos - 10)] = color;
	Result[int2(xPos + 61, yPos - 10)] = color;
	Result[int2(xPos + 62, yPos - 10)] = color;
	Result[int2(xPos + 63, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 41, yPos - 11)] = color;
	Result[int2(xPos + 48, yPos - 11)] = color;
	Result[int2(xPos + 49, yPos - 11)] = color;
	Result[int2(xPos + 53, yPos - 11)] = color;
	Result[int2(xPos + 54, yPos - 11)] = color;
	Result[int2(xPos + 61, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 44, yPos - 12)] = color;
	Result[int2(xPos + 66, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 6, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
}