#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 54, yPos - 8)] = color;
	Result[int2(xPos + 55, yPos - 8)] = color;
	Result[int2(xPos + 57, yPos - 8)] = color;
	Result[int2(xPos + 53, yPos - 9)] = color;
	Result[int2(xPos + 55, yPos - 9)] = color;
	Result[int2(xPos + 57, yPos - 9)] = color;
	Result[int2(xPos + 58, yPos - 9)] = color;
	Result[int2(xPos + 59, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 53, yPos - 10)] = color;
	Result[int2(xPos + 60, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 54, yPos - 11)] = color;
	Result[int2(xPos + 55, yPos - 11)] = color;
	Result[int2(xPos + 56, yPos - 11)] = color;
	Result[int2(xPos + 57, yPos - 11)] = color;
	Result[int2(xPos + 58, yPos - 11)] = color;
	Result[int2(xPos + 60, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 59, yPos - 12)] = color;
	Result[int2(xPos + 56, yPos - 13)] = color;
	Result[int2(xPos + 56, yPos - 14)] = color;
	Result[int2(xPos + 57, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 8, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
}