#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (79 * xMult), yPos)] = color;
	Result[int2(xPos + (78 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos, yPos - (14 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (89 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (33 * yMult))] = color;
}