#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 39782)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 39782)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 39783)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 39784)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 39785)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 39785)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 39738)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 39785)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 39739)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 39785)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 39740)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 39739)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 39738)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 39740)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 39741)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 39742)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 111)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 111)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 112)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 140)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 141)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 141)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 141)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 142)) * yMult)] = color;
}