#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 69)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 69)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 69)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 86)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 86)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 88)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 86)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 87)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 96)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 106)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 96)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 100)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 112)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 112)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 29)) * yMult)] = color;
}