#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (62 * xMult), yPos)] = color;
	Result[int2(xPos + (61 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos, yPos - (25 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (54 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (54 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (55 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (55 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (55 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (56 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (56 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (56 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (57 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (57 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (60 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (60 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (60 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (61 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (62 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (72 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (72 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (72 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (73 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (74 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (75 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (75 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (76 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (76 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (77 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (80 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (80 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (80 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (81 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (82 * yMult))] = color;
}