#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 3)] = color;
	Result[int2(xPos + 34, yPos - 3)] = color;
	Result[int2(xPos + 43, yPos - 4)] = color;
	Result[int2(xPos + 43, yPos - 5)] = color;
	Result[int2(xPos + 45, yPos - 5)] = color;
	Result[int2(xPos + 43, yPos - 6)] = color;
	Result[int2(xPos + 44, yPos - 6)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 43, yPos - 11)] = color;
	Result[int2(xPos + 44, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 43, yPos - 12)] = color;
	Result[int2(xPos + 44, yPos - 12)] = color;
}