#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (9 * xMult), yPos)] = color;
	Result[int2(xPos + (11 * xMult), yPos)] = color;
	Result[int2(xPos + (10 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos, yPos - (41 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos, yPos - (43 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (54 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (54 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (62 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (62 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (63 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (63 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (64 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (99 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (100 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (100 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (101 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (101 * yMult))] = color;
}