#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 3)] = color;
	Result[int2(xPos + 40, yPos - 4)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 4, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 25)] = color;
	Result[int2(xPos + 4, yPos - 25)] = color;
	Result[int2(xPos + 33, yPos - 26)] = color;
	Result[int2(xPos + 35, yPos - 26)] = color;
	Result[int2(xPos + 33, yPos - 27)] = color;
	Result[int2(xPos + 34, yPos - 27)] = color;
	Result[int2(xPos + 34, yPos - 28)] = color;
	Result[int2(xPos + 44, yPos - 29)] = color;
	Result[int2(xPos + 45, yPos - 29)] = color;
	Result[int2(xPos + 44, yPos - 30)] = color;
	Result[int2(xPos + 46, yPos - 30)] = color;
	Result[int2(xPos + 44, yPos - 31)] = color;
	Result[int2(xPos, yPos - 41)] = color;
	Result[int2(xPos + 1, yPos - 42)] = color;
	Result[int2(xPos + 2, yPos - 42)] = color;
	Result[int2(xPos, yPos - 43)] = color;
	Result[int2(xPos + 1, yPos - 43)] = color;
	Result[int2(xPos + 3, yPos - 48)] = color;
	Result[int2(xPos + 4, yPos - 48)] = color;
	Result[int2(xPos + 2, yPos - 49)] = color;
	Result[int2(xPos + 4, yPos - 49)] = color;
	Result[int2(xPos + 4, yPos - 50)] = color;
	Result[int2(xPos + 5, yPos - 52)] = color;
	Result[int2(xPos + 6, yPos - 52)] = color;
	Result[int2(xPos + 7, yPos - 52)] = color;
	Result[int2(xPos + 37, yPos - 52)] = color;
	Result[int2(xPos + 38, yPos - 52)] = color;
	Result[int2(xPos + 5, yPos - 53)] = color;
	Result[int2(xPos + 36, yPos - 53)] = color;
	Result[int2(xPos + 37, yPos - 53)] = color;
	Result[int2(xPos + 6, yPos - 54)] = color;
	Result[int2(xPos + 38, yPos - 54)] = color;
	Result[int2(xPos + 92, yPos - 62)] = color;
	Result[int2(xPos + 93, yPos - 62)] = color;
	Result[int2(xPos + 91, yPos - 63)] = color;
	Result[int2(xPos + 92, yPos - 63)] = color;
	Result[int2(xPos + 93, yPos - 64)] = color;
	Result[int2(xPos + 39, yPos - 99)] = color;
	Result[int2(xPos + 38, yPos - 100)] = color;
	Result[int2(xPos + 39, yPos - 100)] = color;
	Result[int2(xPos + 38, yPos - 101)] = color;
	Result[int2(xPos + 40, yPos - 101)] = color;
}