#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 21)] = color;
	Result[int2(xPos + 3, yPos - 22)] = color;
	Result[int2(xPos + 20, yPos - 27)] = color;
	Result[int2(xPos + 21, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
	Result[int2(xPos + 9, yPos - 28)] = color;
	Result[int2(xPos + 10, yPos - 28)] = color;
	Result[int2(xPos + 11, yPos - 28)] = color;
	Result[int2(xPos + 22, yPos - 28)] = color;
	Result[int2(xPos + 22, yPos - 29)] = color;
	Result[int2(xPos + 21, yPos - 30)] = color;
}