#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 4)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 9, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 12, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 13, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 7, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 19)] = color;
	Result[int2(xPos + 15, yPos - 19)] = color;
	Result[int2(xPos + 14, yPos - 20)] = color;
	Result[int2(xPos + 15, yPos - 20)] = color;
}