#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 5, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
}