#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (312 * xMult), yPos)] = color;
	Result[int2(xPos + (203 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (312 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (197 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (199 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (201 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (202 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (312 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (198 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (199 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (202 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (203 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (198 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (235 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (236 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (237 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (126 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (127 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (128 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos, yPos - (38 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (88 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (238 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (238 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (129 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (238 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (129 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (129 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (244 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (245 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (246 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (252 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (253 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (254 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (257 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (258 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (254 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (256 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (257 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (135 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (136 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (137 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (253 * xMult), yPos - (53 * yMult))] = color;
	Result[int2(xPos + (258 * xMult), yPos - (53 * yMult))] = color;
}