#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 77, yPos)] = color;
	Result[int2(xPos + 77, yPos - 1)] = color;
	Result[int2(xPos + 77, yPos - 2)] = color;
	Result[int2(xPos, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
	Result[int2(xPos + 3, yPos - 43)] = color;
	Result[int2(xPos + 3, yPos - 44)] = color;
	Result[int2(xPos + 3, yPos - 45)] = color;
	Result[int2(xPos + 20, yPos - 50)] = color;
	Result[int2(xPos + 21, yPos - 50)] = color;
	Result[int2(xPos + 22, yPos - 50)] = color;
	Result[int2(xPos + 9, yPos - 51)] = color;
	Result[int2(xPos + 10, yPos - 51)] = color;
	Result[int2(xPos + 11, yPos - 51)] = color;
	Result[int2(xPos + 22, yPos - 51)] = color;
	Result[int2(xPos + 22, yPos - 52)] = color;
	Result[int2(xPos + 21, yPos - 53)] = color;
}