#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 37, yPos)] = color;
	Result[int2(xPos + 38, yPos)] = color;
	Result[int2(xPos + 39, yPos)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 31, yPos - 2)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 3)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 3)] = color;
	Result[int2(xPos + 30, yPos - 3)] = color;
	Result[int2(xPos + 35, yPos - 3)] = color;
	Result[int2(xPos + 36, yPos - 3)] = color;
	Result[int2(xPos + 41, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 14, yPos - 4)] = color;
	Result[int2(xPos + 29, yPos - 4)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 29, yPos - 5)] = color;
	Result[int2(xPos + 30, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 40, yPos - 8)] = color;
	Result[int2(xPos + 41, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 40, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 41, yPos - 10)] = color;
	Result[int2(xPos + 42, yPos - 10)] = color;
	Result[int2(xPos + 43, yPos - 10)] = color;
	Result[int2(xPos, yPos - 11)] = color;
	Result[int2(xPos + 43, yPos - 11)] = color;
}