#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 3)] = color;
	Result[int2(xPos + 19, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 19, yPos - 8)] = color;
	Result[int2(xPos + 27, yPos - 8)] = color;
	Result[int2(xPos + 28, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 28, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
}