#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 62)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 48)) * yMult)] = color;
}