#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 33, yPos)] = color;
	Result[int2(xPos + 35, yPos)] = color;
	Result[int2(xPos + 34, yPos - 1)] = color;
	Result[int2(xPos + 35, yPos - 1)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 3)] = color;
	Result[int2(xPos + 40, yPos - 4)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 44, yPos - 5)] = color;
	Result[int2(xPos + 45, yPos - 5)] = color;
	Result[int2(xPos + 44, yPos - 6)] = color;
	Result[int2(xPos + 46, yPos - 6)] = color;
	Result[int2(xPos + 44, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 10)] = color;
	Result[int2(xPos + 24, yPos - 10)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 32, yPos - 13)] = color;
	Result[int2(xPos + 33, yPos - 13)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 17)] = color;
	Result[int2(xPos + 37, yPos - 17)] = color;
	Result[int2(xPos + 35, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 11, yPos - 23)] = color;
	Result[int2(xPos + 9, yPos - 24)] = color;
	Result[int2(xPos + 10, yPos - 24)] = color;
	Result[int2(xPos + 12, yPos - 31)] = color;
	Result[int2(xPos + 13, yPos - 31)] = color;
	Result[int2(xPos + 11, yPos - 32)] = color;
	Result[int2(xPos + 13, yPos - 32)] = color;
	Result[int2(xPos, yPos - 33)] = color;
	Result[int2(xPos + 13, yPos - 33)] = color;
	Result[int2(xPos + 1, yPos - 34)] = color;
	Result[int2(xPos + 2, yPos - 34)] = color;
	Result[int2(xPos, yPos - 35)] = color;
	Result[int2(xPos + 1, yPos - 35)] = color;
	Result[int2(xPos + 16, yPos - 35)] = color;
	Result[int2(xPos + 17, yPos - 35)] = color;
	Result[int2(xPos + 18, yPos - 35)] = color;
	Result[int2(xPos + 16, yPos - 36)] = color;
	Result[int2(xPos + 17, yPos - 37)] = color;
	Result[int2(xPos + 3, yPos - 40)] = color;
	Result[int2(xPos + 4, yPos - 40)] = color;
	Result[int2(xPos + 2, yPos - 41)] = color;
	Result[int2(xPos + 4, yPos - 41)] = color;
	Result[int2(xPos + 4, yPos - 42)] = color;
	Result[int2(xPos + 5, yPos - 44)] = color;
	Result[int2(xPos + 6, yPos - 44)] = color;
	Result[int2(xPos + 7, yPos - 44)] = color;
	Result[int2(xPos + 5, yPos - 45)] = color;
	Result[int2(xPos + 6, yPos - 46)] = color;
	Result[int2(xPos + 90, yPos - 78)] = color;
	Result[int2(xPos + 91, yPos - 78)] = color;
	Result[int2(xPos + 89, yPos - 79)] = color;
	Result[int2(xPos + 90, yPos - 79)] = color;
	Result[int2(xPos + 91, yPos - 80)] = color;
	Result[int2(xPos + 79, yPos - 89)] = color;
	Result[int2(xPos + 78, yPos - 90)] = color;
	Result[int2(xPos + 79, yPos - 90)] = color;
	Result[int2(xPos + 78, yPos - 91)] = color;
	Result[int2(xPos + 80, yPos - 91)] = color;
}