#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 24)] = color;
	Result[int2(xPos + 7, yPos - 25)] = color;
	Result[int2(xPos + 8, yPos - 25)] = color;
	Result[int2(xPos + 6, yPos - 26)] = color;
	Result[int2(xPos, yPos - 29)] = color;
	Result[int2(xPos + 9, yPos - 29)] = color;
	Result[int2(xPos + 10, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 30)] = color;
	Result[int2(xPos + 2, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 30)] = color;
	Result[int2(xPos + 1, yPos - 32)] = color;
	Result[int2(xPos + 1, yPos - 33)] = color;
	Result[int2(xPos + 2, yPos - 33)] = color;
	Result[int2(xPos, yPos - 34)] = color;
}