#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 28, yPos)] = color;
	Result[int2(xPos + 29, yPos)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 27, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 11, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 29, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 27, yPos - 14)] = color;
	Result[int2(xPos + 28, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 26, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 27, yPos - 16)] = color;
	Result[int2(xPos + 28, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 17)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 17)] = color;
	Result[int2(xPos + 11, yPos - 18)] = color;
	Result[int2(xPos + 27, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 27, yPos - 19)] = color;
	Result[int2(xPos + 28, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 20)] = color;
	Result[int2(xPos + 18, yPos - 20)] = color;
}