#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 14, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 17, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 6)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 18, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 15, yPos - 18)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
}