#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 13)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 28, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 26, yPos - 15)] = color;
	Result[int2(xPos + 27, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 30, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 6, yPos - 18)] = color;
	Result[int2(xPos + 7, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 19, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 5, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 19)] = color;
	Result[int2(xPos + 15, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 32, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 5, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 20)] = color;
	Result[int2(xPos + 15, yPos - 20)] = color;
	Result[int2(xPos + 16, yPos - 20)] = color;
	Result[int2(xPos + 18, yPos - 26)] = color;
	Result[int2(xPos + 19, yPos - 26)] = color;
	Result[int2(xPos + 18, yPos - 27)] = color;
	Result[int2(xPos + 20, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 20, yPos - 28)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 17, yPos - 30)] = color;
	Result[int2(xPos + 17, yPos - 31)] = color;
	Result[int2(xPos + 14, yPos - 32)] = color;
	Result[int2(xPos + 15, yPos - 32)] = color;
	Result[int2(xPos + 16, yPos - 32)] = color;
	Result[int2(xPos + 14, yPos - 33)] = color;
}