#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 12, yPos)] = color;
	Result[int2(xPos + 13, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 30, yPos - 8)] = color;
	Result[int2(xPos + 31, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 30, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 21, yPos - 10)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 21, yPos - 11)] = color;
	Result[int2(xPos + 28, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 21, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 12, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 27)] = color;
	Result[int2(xPos + 20, yPos - 27)] = color;
	Result[int2(xPos + 21, yPos - 27)] = color;
	Result[int2(xPos + 2, yPos - 28)] = color;
	Result[int2(xPos + 3, yPos - 28)] = color;
	Result[int2(xPos + 10, yPos - 28)] = color;
	Result[int2(xPos + 12, yPos - 28)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 21, yPos - 28)] = color;
	Result[int2(xPos + 28, yPos - 28)] = color;
	Result[int2(xPos + 29, yPos - 28)] = color;
	Result[int2(xPos + 1, yPos - 29)] = color;
	Result[int2(xPos + 3, yPos - 29)] = color;
	Result[int2(xPos + 10, yPos - 29)] = color;
	Result[int2(xPos + 11, yPos - 29)] = color;
	Result[int2(xPos + 12, yPos - 29)] = color;
	Result[int2(xPos + 19, yPos - 29)] = color;
	Result[int2(xPos + 20, yPos - 29)] = color;
	Result[int2(xPos + 21, yPos - 29)] = color;
	Result[int2(xPos + 28, yPos - 29)] = color;
	Result[int2(xPos + 30, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 30)] = color;
	Result[int2(xPos + 30, yPos - 30)] = color;
	Result[int2(xPos, yPos - 31)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 30, yPos - 31)] = color;
	Result[int2(xPos + 31, yPos - 31)] = color;
	Result[int2(xPos + 12, yPos - 38)] = color;
	Result[int2(xPos + 13, yPos - 38)] = color;
	Result[int2(xPos + 18, yPos - 38)] = color;
	Result[int2(xPos + 19, yPos - 38)] = color;
	Result[int2(xPos + 12, yPos - 39)] = color;
	Result[int2(xPos + 13, yPos - 39)] = color;
	Result[int2(xPos + 18, yPos - 39)] = color;
	Result[int2(xPos + 19, yPos - 39)] = color;
}