#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 45, yPos)] = color;
	Result[int2(xPos + 46, yPos)] = color;
	Result[int2(xPos + 45, yPos - 1)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 45, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 3)] = color;
	Result[int2(xPos + 44, yPos - 3)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 46, yPos - 10)] = color;
	Result[int2(xPos + 47, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
	Result[int2(xPos + 18, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 40, yPos - 11)] = color;
	Result[int2(xPos + 42, yPos - 11)] = color;
	Result[int2(xPos + 46, yPos - 11)] = color;
	Result[int2(xPos + 47, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 13, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 42, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 13)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 28, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 45, yPos - 16)] = color;
	Result[int2(xPos + 46, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 17)] = color;
	Result[int2(xPos + 45, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 18, yPos - 18)] = color;
	Result[int2(xPos + 19, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 28, yPos - 18)] = color;
	Result[int2(xPos + 29, yPos - 18)] = color;
	Result[int2(xPos + 30, yPos - 18)] = color;
	Result[int2(xPos + 46, yPos - 18)] = color;
	Result[int2(xPos + 47, yPos - 18)] = color;
	Result[int2(xPos + 48, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 48, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 17, yPos - 20)] = color;
	Result[int2(xPos + 20, yPos - 20)] = color;
	Result[int2(xPos + 17, yPos - 21)] = color;
	Result[int2(xPos + 18, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 23)] = color;
	Result[int2(xPos + 6, yPos - 24)] = color;
	Result[int2(xPos + 7, yPos - 24)] = color;
	Result[int2(xPos + 29, yPos - 24)] = color;
	Result[int2(xPos + 30, yPos - 24)] = color;
	Result[int2(xPos + 35, yPos - 24)] = color;
	Result[int2(xPos + 36, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 6, yPos - 25)] = color;
	Result[int2(xPos + 8, yPos - 25)] = color;
	Result[int2(xPos + 17, yPos - 25)] = color;
	Result[int2(xPos + 18, yPos - 25)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 30, yPos - 25)] = color;
	Result[int2(xPos + 35, yPos - 25)] = color;
	Result[int2(xPos + 36, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
	Result[int2(xPos + 2, yPos - 26)] = color;
	Result[int2(xPos + 17, yPos - 26)] = color;
	Result[int2(xPos + 18, yPos - 26)] = color;
	Result[int2(xPos + 4, yPos - 33)] = color;
	Result[int2(xPos + 5, yPos - 33)] = color;
	Result[int2(xPos + 3, yPos - 34)] = color;
	Result[int2(xPos + 5, yPos - 34)] = color;
	Result[int2(xPos + 3, yPos - 35)] = color;
	Result[int2(xPos + 2, yPos - 36)] = color;
	Result[int2(xPos + 3, yPos - 36)] = color;
}