#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 45, yPos - 18)] = color;
	Result[int2(xPos + 44, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 20)] = color;
	Result[int2(xPos + 45, yPos - 20)] = color;
	Result[int2(xPos + 46, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 23)] = color;
	Result[int2(xPos + 30, yPos - 23)] = color;
	Result[int2(xPos + 29, yPos - 24)] = color;
	Result[int2(xPos + 30, yPos - 24)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 37, yPos - 27)] = color;
	Result[int2(xPos + 35, yPos - 28)] = color;
	Result[int2(xPos + 36, yPos - 28)] = color;
	Result[int2(xPos + 32, yPos - 29)] = color;
	Result[int2(xPos + 36, yPos - 29)] = color;
	Result[int2(xPos + 37, yPos - 29)] = color;
	Result[int2(xPos + 33, yPos - 30)] = color;
	Result[int2(xPos + 34, yPos - 30)] = color;
	Result[int2(xPos + 32, yPos - 31)] = color;
	Result[int2(xPos + 33, yPos - 31)] = color;
	Result[int2(xPos + 57, yPos - 43)] = color;
	Result[int2(xPos + 58, yPos - 43)] = color;
	Result[int2(xPos + 57, yPos - 44)] = color;
	Result[int2(xPos + 59, yPos - 44)] = color;
	Result[int2(xPos + 57, yPos - 45)] = color;
	Result[int2(xPos + 58, yPos - 48)] = color;
	Result[int2(xPos + 59, yPos - 48)] = color;
	Result[int2(xPos + 57, yPos - 49)] = color;
	Result[int2(xPos + 58, yPos - 49)] = color;
	Result[int2(xPos + 59, yPos - 50)] = color;
	Result[int2(xPos + 61, yPos - 55)] = color;
	Result[int2(xPos + 62, yPos - 55)] = color;
	Result[int2(xPos + 60, yPos - 56)] = color;
	Result[int2(xPos + 61, yPos - 56)] = color;
	Result[int2(xPos + 62, yPos - 57)] = color;
}