#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 50, yPos)] = color;
	Result[int2(xPos + 51, yPos)] = color;
	Result[int2(xPos + 51, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 51, yPos - 2)] = color;
	Result[int2(xPos + 53, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 52, yPos - 3)] = color;
	Result[int2(xPos + 53, yPos - 3)] = color;
	Result[int2(xPos + 61, yPos - 3)] = color;
	Result[int2(xPos + 63, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 15, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 64, yPos - 4)] = color;
	Result[int2(xPos + 65, yPos - 4)] = color;
	Result[int2(xPos + 74, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 64, yPos - 5)] = color;
	Result[int2(xPos + 65, yPos - 5)] = color;
	Result[int2(xPos + 72, yPos - 5)] = color;
	Result[int2(xPos + 74, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
	Result[int2(xPos + 64, yPos - 6)] = color;
	Result[int2(xPos + 65, yPos - 6)] = color;
	Result[int2(xPos + 71, yPos - 6)] = color;
	Result[int2(xPos + 73, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 7)] = color;
	Result[int2(xPos + 24, yPos - 7)] = color;
	Result[int2(xPos + 61, yPos - 7)] = color;
	Result[int2(xPos + 63, yPos - 7)] = color;
	Result[int2(xPos + 70, yPos - 7)] = color;
	Result[int2(xPos + 73, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 12, yPos - 8)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos + 61, yPos - 8)] = color;
	Result[int2(xPos + 71, yPos - 8)] = color;
	Result[int2(xPos + 73, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 34, yPos - 9)] = color;
	Result[int2(xPos + 72, yPos - 9)] = color;
	Result[int2(xPos + 74, yPos - 9)] = color;
	Result[int2(xPos + 83, yPos - 9)] = color;
	Result[int2(xPos + 84, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos + 74, yPos - 10)] = color;
	Result[int2(xPos + 83, yPos - 10)] = color;
	Result[int2(xPos + 85, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 11)] = color;
	Result[int2(xPos + 35, yPos - 11)] = color;
	Result[int2(xPos + 85, yPos - 11)] = color;
	Result[int2(xPos + 85, yPos - 12)] = color;
	Result[int2(xPos + 86, yPos - 12)] = color;
}