#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 3)] = color;
	Result[int2(xPos + 6, yPos - 3)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 6, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 10)] = color;
	Result[int2(xPos + 6, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 22, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 22, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 15)] = color;
	Result[int2(xPos + 20, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 8, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 13, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 3, yPos - 21)] = color;
	Result[int2(xPos + 11, yPos - 21)] = color;
	Result[int2(xPos + 13, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
}