#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 50)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 70)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 86)) * xMult), (yPos - 12)) * yMult)] = color;
}