#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 44, yPos)] = color;
	Result[int2(xPos + 46, yPos)] = color;
	Result[int2(xPos + 44, yPos - 1)] = color;
	Result[int2(xPos + 45, yPos - 1)] = color;
	Result[int2(xPos + 45, yPos - 2)] = color;
	Result[int2(xPos + 38, yPos - 3)] = color;
	Result[int2(xPos + 39, yPos - 4)] = color;
	Result[int2(xPos + 37, yPos - 5)] = color;
	Result[int2(xPos + 38, yPos - 5)] = color;
	Result[int2(xPos + 39, yPos - 5)] = color;
	Result[int2(xPos + 26, yPos - 7)] = color;
	Result[int2(xPos + 27, yPos - 7)] = color;
	Result[int2(xPos + 34, yPos - 7)] = color;
	Result[int2(xPos + 35, yPos - 7)] = color;
	Result[int2(xPos + 36, yPos - 7)] = color;
	Result[int2(xPos + 42, yPos - 7)] = color;
	Result[int2(xPos + 43, yPos - 7)] = color;
	Result[int2(xPos + 57, yPos - 7)] = color;
	Result[int2(xPos + 59, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 8)] = color;
	Result[int2(xPos + 26, yPos - 8)] = color;
	Result[int2(xPos + 28, yPos - 8)] = color;
	Result[int2(xPos + 36, yPos - 8)] = color;
	Result[int2(xPos + 42, yPos - 8)] = color;
	Result[int2(xPos + 44, yPos - 8)] = color;
	Result[int2(xPos + 57, yPos - 8)] = color;
	Result[int2(xPos + 58, yPos - 8)] = color;
	Result[int2(xPos + 60, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 28, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 44, yPos - 9)] = color;
	Result[int2(xPos + 60, yPos - 9)] = color;
	Result[int2(xPos + 7, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 44, yPos - 10)] = color;
	Result[int2(xPos + 46, yPos - 10)] = color;
	Result[int2(xPos + 47, yPos - 10)] = color;
	Result[int2(xPos + 60, yPos - 10)] = color;
	Result[int2(xPos + 62, yPos - 10)] = color;
	Result[int2(xPos + 63, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 9, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 45, yPos - 11)] = color;
	Result[int2(xPos + 47, yPos - 11)] = color;
	Result[int2(xPos + 61, yPos - 11)] = color;
	Result[int2(xPos + 63, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 13, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
}