#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 57, yPos)] = color;
	Result[int2(xPos + 56, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 56, yPos - 2)] = color;
	Result[int2(xPos + 57, yPos - 2)] = color;
	Result[int2(xPos + 58, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 64, yPos - 4)] = color;
	Result[int2(xPos + 62, yPos - 5)] = color;
	Result[int2(xPos + 63, yPos - 5)] = color;
	Result[int2(xPos + 63, yPos - 6)] = color;
	Result[int2(xPos + 64, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 40)] = color;
	Result[int2(xPos + 11, yPos - 41)] = color;
	Result[int2(xPos + 12, yPos - 41)] = color;
	Result[int2(xPos + 10, yPos - 42)] = color;
	Result[int2(xPos + 11, yPos - 42)] = color;
	Result[int2(xPos + 50, yPos - 43)] = color;
	Result[int2(xPos + 49, yPos - 44)] = color;
	Result[int2(xPos + 50, yPos - 44)] = color;
	Result[int2(xPos + 49, yPos - 45)] = color;
	Result[int2(xPos + 51, yPos - 45)] = color;
	Result[int2(xPos + 4, yPos - 48)] = color;
	Result[int2(xPos + 5, yPos - 48)] = color;
	Result[int2(xPos + 6, yPos - 48)] = color;
	Result[int2(xPos + 6, yPos - 49)] = color;
	Result[int2(xPos + 57, yPos - 49)] = color;
	Result[int2(xPos + 5, yPos - 50)] = color;
	Result[int2(xPos + 56, yPos - 50)] = color;
	Result[int2(xPos + 57, yPos - 50)] = color;
	Result[int2(xPos + 56, yPos - 51)] = color;
	Result[int2(xPos + 58, yPos - 51)] = color;
	Result[int2(xPos + 62, yPos - 52)] = color;
	Result[int2(xPos + 63, yPos - 52)] = color;
	Result[int2(xPos + 64, yPos - 52)] = color;
	Result[int2(xPos + 62, yPos - 53)] = color;
	Result[int2(xPos + 63, yPos - 54)] = color;
	Result[int2(xPos + 17, yPos - 55)] = color;
	Result[int2(xPos + 18, yPos - 55)] = color;
	Result[int2(xPos + 19, yPos - 55)] = color;
	Result[int2(xPos + 19, yPos - 56)] = color;
	Result[int2(xPos + 18, yPos - 57)] = color;
	Result[int2(xPos + 39, yPos - 62)] = color;
	Result[int2(xPos + 40, yPos - 62)] = color;
	Result[int2(xPos + 41, yPos - 62)] = color;
	Result[int2(xPos + 39, yPos - 63)] = color;
	Result[int2(xPos + 40, yPos - 64)] = color;
	Result[int2(xPos + 14, yPos - 66)] = color;
	Result[int2(xPos + 15, yPos - 66)] = color;
	Result[int2(xPos + 15, yPos - 67)] = color;
	Result[int2(xPos + 16, yPos - 67)] = color;
	Result[int2(xPos + 14, yPos - 68)] = color;
	Result[int2(xPos + 35, yPos - 74)] = color;
	Result[int2(xPos + 33, yPos - 75)] = color;
	Result[int2(xPos + 35, yPos - 75)] = color;
	Result[int2(xPos + 34, yPos - 76)] = color;
	Result[int2(xPos + 35, yPos - 76)] = color;
	Result[int2(xPos + 44, yPos - 76)] = color;
	Result[int2(xPos + 46, yPos - 76)] = color;
	Result[int2(xPos + 44, yPos - 77)] = color;
	Result[int2(xPos + 45, yPos - 77)] = color;
	Result[int2(xPos + 45, yPos - 78)] = color;
	Result[int2(xPos + 23, yPos - 83)] = color;
	Result[int2(xPos + 34, yPos - 83)] = color;
	Result[int2(xPos + 24, yPos - 84)] = color;
	Result[int2(xPos + 25, yPos - 84)] = color;
	Result[int2(xPos + 34, yPos - 84)] = color;
	Result[int2(xPos + 35, yPos - 84)] = color;
	Result[int2(xPos + 23, yPos - 85)] = color;
	Result[int2(xPos + 24, yPos - 85)] = color;
	Result[int2(xPos + 33, yPos - 85)] = color;
	Result[int2(xPos + 35, yPos - 85)] = color;
	Result[int2(xPos + 23, yPos - 89)] = color;
	Result[int2(xPos + 24, yPos - 89)] = color;
	Result[int2(xPos + 25, yPos - 89)] = color;
	Result[int2(xPos + 25, yPos - 90)] = color;
	Result[int2(xPos + 24, yPos - 91)] = color;
	Result[int2(xPos + 26, yPos - 92)] = color;
	Result[int2(xPos + 27, yPos - 92)] = color;
	Result[int2(xPos + 28, yPos - 92)] = color;
	Result[int2(xPos + 26, yPos - 93)] = color;
	Result[int2(xPos + 27, yPos - 94)] = color;
}