#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 26, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 28, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 28, yPos - 6)] = color;
	Result[int2(xPos + 29, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 13, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 7)] = color;
	Result[int2(xPos + 25, yPos - 7)] = color;
	Result[int2(xPos + 26, yPos - 7)] = color;
	Result[int2(xPos + 28, yPos - 7)] = color;
	Result[int2(xPos + 30, yPos - 7)] = color;
	Result[int2(xPos + 7, yPos - 8)] = color;
	Result[int2(xPos + 8, yPos - 8)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 8)] = color;
	Result[int2(xPos + 18, yPos - 8)] = color;
	Result[int2(xPos + 20, yPos - 8)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 28, yPos - 8)] = color;
	Result[int2(xPos + 30, yPos - 8)] = color;
	Result[int2(xPos + 31, yPos - 8)] = color;
	Result[int2(xPos + 6, yPos - 9)] = color;
	Result[int2(xPos + 11, yPos - 9)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 20, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 7, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 18, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 22, yPos - 11)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 25, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 27, yPos - 16)] = color;
}