#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 46)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 76)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 76)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 57)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 57)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 72)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 74)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 74)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 75)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 80)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 80)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 80)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 82)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 82)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 83)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 83)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 88)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 88)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 88)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 88)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 89)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 89)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 89)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 89)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 90)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 90)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 90)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 90)) * yMult)] = color;
}