#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 45, yPos - 18)] = color;
	Result[int2(xPos + 44, yPos - 19)] = color;
	Result[int2(xPos + 46, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 20)] = color;
	Result[int2(xPos + 46, yPos - 20)] = color;
	Result[int2(xPos + 43, yPos - 21)] = color;
	Result[int2(xPos + 44, yPos - 21)] = color;
	Result[int2(xPos + 46, yPos - 21)] = color;
	Result[int2(xPos + 47, yPos - 21)] = color;
	Result[int2(xPos + 48, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 49, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 43, yPos - 23)] = color;
	Result[int2(xPos + 44, yPos - 23)] = color;
	Result[int2(xPos + 46, yPos - 23)] = color;
	Result[int2(xPos + 47, yPos - 23)] = color;
	Result[int2(xPos + 48, yPos - 23)] = color;
	Result[int2(xPos + 43, yPos - 24)] = color;
	Result[int2(xPos + 44, yPos - 24)] = color;
	Result[int2(xPos + 46, yPos - 24)] = color;
	Result[int2(xPos + 46, yPos - 31)] = color;
	Result[int2(xPos + 47, yPos - 31)] = color;
	Result[int2(xPos + 37, yPos - 32)] = color;
	Result[int2(xPos + 46, yPos - 32)] = color;
	Result[int2(xPos + 47, yPos - 32)] = color;
	Result[int2(xPos + 36, yPos - 33)] = color;
	Result[int2(xPos + 38, yPos - 33)] = color;
	Result[int2(xPos + 36, yPos - 34)] = color;
	Result[int2(xPos + 39, yPos - 34)] = color;
	Result[int2(xPos + 37, yPos - 35)] = color;
	Result[int2(xPos + 38, yPos - 35)] = color;
	Result[int2(xPos + 20, yPos - 36)] = color;
	Result[int2(xPos + 21, yPos - 36)] = color;
	Result[int2(xPos + 19, yPos - 37)] = color;
	Result[int2(xPos + 21, yPos - 37)] = color;
	Result[int2(xPos + 19, yPos - 38)] = color;
	Result[int2(xPos + 44, yPos - 38)] = color;
	Result[int2(xPos + 45, yPos - 38)] = color;
	Result[int2(xPos + 18, yPos - 39)] = color;
	Result[int2(xPos + 19, yPos - 39)] = color;
	Result[int2(xPos + 44, yPos - 39)] = color;
	Result[int2(xPos + 45, yPos - 39)] = color;
	Result[int2(xPos + 35, yPos - 44)] = color;
	Result[int2(xPos + 36, yPos - 44)] = color;
	Result[int2(xPos + 35, yPos - 45)] = color;
	Result[int2(xPos + 36, yPos - 45)] = color;
}