#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (1 * xMult), yPos)] = color;
	Result[int2(xPos + (6 * xMult), yPos)] = color;
	Result[int2(xPos + (7 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (14 * xMult), yPos)] = color;
	Result[int2(xPos + (21 * xMult), yPos)] = color;
	Result[int2(xPos + (22 * xMult), yPos)] = color;
	Result[int2(xPos + (30 * xMult), yPos)] = color;
	Result[int2(xPos + (31 * xMult), yPos)] = color;
	Result[int2(xPos + (40 * xMult), yPos)] = color;
	Result[int2(xPos + (41 * xMult), yPos)] = color;
	Result[int2(xPos + (51 * xMult), yPos)] = color;
	Result[int2(xPos + (52 * xMult), yPos)] = color;
	Result[int2(xPos + (63 * xMult), yPos)] = color;
	Result[int2(xPos + (64 * xMult), yPos)] = color;
	Result[int2(xPos + (76 * xMult), yPos)] = color;
	Result[int2(xPos + (77 * xMult), yPos)] = color;
	Result[int2(xPos + (90 * xMult), yPos)] = color;
	Result[int2(xPos + (91 * xMult), yPos)] = color;
	Result[int2(xPos + (105 * xMult), yPos)] = color;
	Result[int2(xPos + (106 * xMult), yPos)] = color;
	Result[int2(xPos + (121 * xMult), yPos)] = color;
	Result[int2(xPos + (122 * xMult), yPos)] = color;
	Result[int2(xPos, yPos - (1 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (121 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (123 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (123 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (125 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (111 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (125 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (127 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (111 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (113 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (127 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (129 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (113 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (115 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (129 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (131 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (88 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (115 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (117 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (131 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (133 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (88 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (117 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (119 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (133 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (135 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (118 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (119 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (136 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (135 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (136 * xMult), yPos - (15 * yMult))] = color;
}