#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 13, yPos)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 29, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 28, yPos - 3)] = color;
	Result[int2(xPos + 29, yPos - 3)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 33, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 33, yPos - 23)] = color;
	Result[int2(xPos, yPos - 36)] = color;
	Result[int2(xPos + 1, yPos - 36)] = color;
	Result[int2(xPos + 31, yPos - 36)] = color;
	Result[int2(xPos + 32, yPos - 36)] = color;
	Result[int2(xPos + 1, yPos - 37)] = color;
	Result[int2(xPos + 2, yPos - 37)] = color;
	Result[int2(xPos + 31, yPos - 37)] = color;
	Result[int2(xPos, yPos - 38)] = color;
	Result[int2(xPos + 1, yPos - 38)] = color;
	Result[int2(xPos + 21, yPos - 38)] = color;
	Result[int2(xPos + 22, yPos - 38)] = color;
	Result[int2(xPos + 26, yPos - 38)] = color;
	Result[int2(xPos + 27, yPos - 38)] = color;
	Result[int2(xPos + 32, yPos - 38)] = color;
	Result[int2(xPos + 33, yPos - 38)] = color;
	Result[int2(xPos + 34, yPos - 38)] = color;
	Result[int2(xPos, yPos - 39)] = color;
	Result[int2(xPos + 19, yPos - 39)] = color;
	Result[int2(xPos + 22, yPos - 39)] = color;
	Result[int2(xPos + 27, yPos - 39)] = color;
	Result[int2(xPos + 34, yPos - 39)] = color;
	Result[int2(xPos + 19, yPos - 40)] = color;
	Result[int2(xPos + 20, yPos - 40)] = color;
	Result[int2(xPos + 21, yPos - 40)] = color;
	Result[int2(xPos + 26, yPos - 40)] = color;
	Result[int2(xPos + 26, yPos - 41)] = color;
	Result[int2(xPos + 27, yPos - 41)] = color;
	Result[int2(xPos + 19, yPos - 42)] = color;
	Result[int2(xPos + 20, yPos - 42)] = color;
	Result[int2(xPos + 22, yPos - 42)] = color;
	Result[int2(xPos + 19, yPos - 43)] = color;
	Result[int2(xPos + 21, yPos - 43)] = color;
	Result[int2(xPos + 22, yPos - 43)] = color;
}