#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos, yPos - (36 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos, yPos - (38 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos, yPos - (39 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (43 * yMult))] = color;
}