#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 14, yPos)] = color;
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 12, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 13, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 5, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
}