#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (38 * xMult), yPos)] = color;
	Result[int2(xPos + (82 * xMult), yPos)] = color;
	Result[int2(xPos + (36 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos, yPos - (11 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (104 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos, yPos - (13 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos, yPos - (15 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos, yPos - (17 * yMult))] = color;
}