#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 27, yPos - 3)] = color;
	Result[int2(xPos + 29, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 29, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 5)] = color;
	Result[int2(xPos + 29, yPos - 5)] = color;
	Result[int2(xPos + 30, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 6)] = color;
	Result[int2(xPos + 26, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 4, yPos - 8)] = color;
	Result[int2(xPos + 4, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 10, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 11)] = color;
}