#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 4, yPos - 21)] = color;
	Result[int2(xPos + 4, yPos - 22)] = color;
	Result[int2(xPos + 5, yPos - 22)] = color;
	Result[int2(xPos + 5, yPos - 23)] = color;
	Result[int2(xPos + 6, yPos - 23)] = color;
	Result[int2(xPos + 5, yPos - 24)] = color;
}