#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 30, yPos)] = color;
	Result[int2(xPos + 31, yPos)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 31, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 29, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 29, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 29, yPos - 4)] = color;
	Result[int2(xPos + 31, yPos - 4)] = color;
	Result[int2(xPos + 30, yPos - 5)] = color;
	Result[int2(xPos + 31, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
}