#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 1)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 47)) * yMult)] = color;
}