#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 46, yPos - 15)] = color;
	Result[int2(xPos + 45, yPos - 16)] = color;
	Result[int2(xPos + 45, yPos - 17)] = color;
	Result[int2(xPos + 46, yPos - 17)] = color;
	Result[int2(xPos + 47, yPos - 17)] = color;
	Result[int2(xPos + 37, yPos - 24)] = color;
	Result[int2(xPos + 37, yPos - 25)] = color;
	Result[int2(xPos + 39, yPos - 25)] = color;
	Result[int2(xPos + 37, yPos - 26)] = color;
	Result[int2(xPos + 38, yPos - 26)] = color;
	Result[int2(xPos + 23, yPos - 32)] = color;
	Result[int2(xPos + 24, yPos - 32)] = color;
	Result[int2(xPos + 30, yPos - 32)] = color;
	Result[int2(xPos + 23, yPos - 33)] = color;
	Result[int2(xPos + 24, yPos - 33)] = color;
	Result[int2(xPos + 29, yPos - 33)] = color;
	Result[int2(xPos + 31, yPos - 33)] = color;
	Result[int2(xPos + 29, yPos - 34)] = color;
	Result[int2(xPos + 31, yPos - 34)] = color;
	Result[int2(xPos + 30, yPos - 35)] = color;
	Result[int2(xPos + 44, yPos - 36)] = color;
	Result[int2(xPos + 45, yPos - 36)] = color;
	Result[int2(xPos + 44, yPos - 37)] = color;
	Result[int2(xPos + 46, yPos - 37)] = color;
	Result[int2(xPos + 46, yPos - 38)] = color;
	Result[int2(xPos + 35, yPos - 39)] = color;
	Result[int2(xPos + 36, yPos - 39)] = color;
	Result[int2(xPos + 46, yPos - 39)] = color;
	Result[int2(xPos + 47, yPos - 39)] = color;
	Result[int2(xPos + 28, yPos - 40)] = color;
	Result[int2(xPos + 29, yPos - 40)] = color;
	Result[int2(xPos + 35, yPos - 40)] = color;
	Result[int2(xPos + 36, yPos - 40)] = color;
	Result[int2(xPos + 27, yPos - 41)] = color;
	Result[int2(xPos + 29, yPos - 41)] = color;
	Result[int2(xPos + 27, yPos - 42)] = color;
	Result[int2(xPos + 28, yPos - 42)] = color;
	Result[int2(xPos + 30, yPos - 44)] = color;
	Result[int2(xPos + 31, yPos - 44)] = color;
	Result[int2(xPos + 30, yPos - 45)] = color;
	Result[int2(xPos + 31, yPos - 46)] = color;
	Result[int2(xPos + 32, yPos - 46)] = color;
	Result[int2(xPos + 33, yPos - 46)] = color;
	Result[int2(xPos + 33, yPos - 47)] = color;
}