#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 14, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 15, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 15, yPos - 4)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 13, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 13, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 15)] = color;
	Result[int2(xPos + 23, yPos - 16)] = color;
	Result[int2(xPos + 24, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
	Result[int2(xPos + 21, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
	Result[int2(xPos + 44, yPos - 30)] = color;
	Result[int2(xPos + 44, yPos - 31)] = color;
	Result[int2(xPos + 45, yPos - 31)] = color;
	Result[int2(xPos + 43, yPos - 32)] = color;
	Result[int2(xPos + 44, yPos - 32)] = color;
	Result[int2(xPos + 61, yPos - 34)] = color;
	Result[int2(xPos + 62, yPos - 34)] = color;
	Result[int2(xPos + 61, yPos - 35)] = color;
	Result[int2(xPos + 63, yPos - 35)] = color;
	Result[int2(xPos + 63, yPos - 36)] = color;
	Result[int2(xPos + 63, yPos - 37)] = color;
	Result[int2(xPos + 64, yPos - 37)] = color;
	Result[int2(xPos + 40, yPos - 38)] = color;
	Result[int2(xPos + 41, yPos - 38)] = color;
	Result[int2(xPos + 41, yPos - 39)] = color;
	Result[int2(xPos + 38, yPos - 40)] = color;
	Result[int2(xPos + 39, yPos - 40)] = color;
	Result[int2(xPos + 40, yPos - 40)] = color;
	Result[int2(xPos + 38, yPos - 41)] = color;
}