#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 28, yPos)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 8)] = color;
	Result[int2(xPos + 19, yPos - 8)] = color;
	Result[int2(xPos + 14, yPos - 9)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 20, yPos - 9)] = color;
	Result[int2(xPos + 21, yPos - 9)] = color;
	Result[int2(xPos + 15, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 26, yPos - 12)] = color;
	Result[int2(xPos + 27, yPos - 12)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 17)] = color;
	Result[int2(xPos + 24, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 18)] = color;
	Result[int2(xPos + 23, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 46, yPos - 20)] = color;
	Result[int2(xPos + 47, yPos - 20)] = color;
	Result[int2(xPos + 54, yPos - 20)] = color;
	Result[int2(xPos + 55, yPos - 20)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 45, yPos - 21)] = color;
	Result[int2(xPos + 49, yPos - 21)] = color;
	Result[int2(xPos + 52, yPos - 21)] = color;
	Result[int2(xPos + 56, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 22)] = color;
	Result[int2(xPos + 17, yPos - 22)] = color;
	Result[int2(xPos + 46, yPos - 22)] = color;
	Result[int2(xPos + 55, yPos - 22)] = color;
	Result[int2(xPos + 15, yPos - 23)] = color;
	Result[int2(xPos + 17, yPos - 23)] = color;
	Result[int2(xPos + 47, yPos - 23)] = color;
	Result[int2(xPos + 49, yPos - 23)] = color;
	Result[int2(xPos + 50, yPos - 23)] = color;
	Result[int2(xPos + 51, yPos - 23)] = color;
	Result[int2(xPos + 52, yPos - 23)] = color;
	Result[int2(xPos + 54, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 24)] = color;
	Result[int2(xPos + 35, yPos - 24)] = color;
	Result[int2(xPos + 36, yPos - 24)] = color;
	Result[int2(xPos + 50, yPos - 24)] = color;
	Result[int2(xPos + 51, yPos - 24)] = color;
	Result[int2(xPos, yPos - 25)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 35, yPos - 25)] = color;
	Result[int2(xPos + 37, yPos - 25)] = color;
	Result[int2(xPos + 2, yPos - 26)] = color;
	Result[int2(xPos + 21, yPos - 26)] = color;
	Result[int2(xPos + 23, yPos - 26)] = color;
	Result[int2(xPos + 35, yPos - 26)] = color;
}