#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 59)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 46)) * yMult)] = color;
}