#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 4)) * yMult)] = color;
}