#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 8, yPos - 8)] = color;
	Result[int2(xPos + 26, yPos - 8)] = color;
	Result[int2(xPos + 27, yPos - 8)] = color;
	Result[int2(xPos + 29, yPos - 8)] = color;
	Result[int2(xPos + 30, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 25, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 31, yPos - 9)] = color;
	Result[int2(xPos + 25, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 29, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 27, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 16)] = color;
}