#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (1 * xMult), yPos)] = color;
	Result[int2(xPos + (2 * xMult), yPos)] = color;
	Result[int2(xPos + (7 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (19 * xMult), yPos)] = color;
	Result[int2(xPos + (25 * xMult), yPos)] = color;
	Result[int2(xPos + (31 * xMult), yPos)] = color;
	Result[int2(xPos + (37 * xMult), yPos)] = color;
	Result[int2(xPos + (43 * xMult), yPos)] = color;
	Result[int2(xPos + (49 * xMult), yPos)] = color;
	Result[int2(xPos + (55 * xMult), yPos)] = color;
	Result[int2(xPos + (61 * xMult), yPos)] = color;
	Result[int2(xPos, yPos - (1 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos, yPos - (2 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (2 * yMult))] = color;
}