#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 47)) * yMult)] = color;
}