#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (35 * xMult), yPos)] = color;
	Result[int2(xPos + (37 * xMult), yPos)] = color;
	Result[int2(xPos + (35 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos, yPos - (9 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (52 * yMult))] = color;
}