#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 12, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 29, yPos - 2)] = color;
	Result[int2(xPos + 31, yPos - 2)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 36, yPos - 2)] = color;
	Result[int2(xPos + 37, yPos - 2)] = color;
	Result[int2(xPos + 39, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 44, yPos - 2)] = color;
	Result[int2(xPos + 45, yPos - 2)] = color;
	Result[int2(xPos + 47, yPos - 2)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 51, yPos - 2)] = color;
	Result[int2(xPos + 52, yPos - 2)] = color;
	Result[int2(xPos + 53, yPos - 2)] = color;
	Result[int2(xPos + 55, yPos - 2)] = color;
	Result[int2(xPos + 56, yPos - 2)] = color;
	Result[int2(xPos + 57, yPos - 2)] = color;
	Result[int2(xPos + 59, yPos - 2)] = color;
	Result[int2(xPos + 60, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 6, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 3)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 6, yPos - 4)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
}