#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 14, yPos)] = color;
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 6, yPos - 3)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 8)] = color;
	Result[int2(xPos + 13, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 4, yPos - 9)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 12, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 14, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
}