#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 3)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 15, yPos - 3)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos + 21, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 11, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 37, yPos - 10)] = color;
	Result[int2(xPos + 38, yPos - 10)] = color;
	Result[int2(xPos + 36, yPos - 11)] = color;
	Result[int2(xPos + 39, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 37, yPos - 12)] = color;
	Result[int2(xPos + 38, yPos - 12)] = color;
	Result[int2(xPos, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 42, yPos - 16)] = color;
	Result[int2(xPos + 43, yPos - 16)] = color;
	Result[int2(xPos + 42, yPos - 17)] = color;
	Result[int2(xPos + 44, yPos - 17)] = color;
	Result[int2(xPos + 43, yPos - 18)] = color;
	Result[int2(xPos + 44, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 21, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 23)] = color;
}