#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 12, yPos - 5)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 20)] = color;
	Result[int2(xPos + 13, yPos - 21)] = color;
	Result[int2(xPos + 15, yPos - 21)] = color;
	Result[int2(xPos + 17, yPos - 21)] = color;
	Result[int2(xPos + 19, yPos - 21)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 14, yPos - 22)] = color;
	Result[int2(xPos + 15, yPos - 22)] = color;
	Result[int2(xPos + 17, yPos - 22)] = color;
	Result[int2(xPos + 18, yPos - 22)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
}