#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 10, yPos - 14)] = color;
	Result[int2(xPos + 21, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 14)] = color;
	Result[int2(xPos + 24, yPos - 14)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
}