#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (3 * xMult), yPos)] = color;
	Result[int2(xPos + (4 * xMult), yPos)] = color;
	Result[int2(xPos + (8 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (14 * xMult), yPos)] = color;
	Result[int2(xPos + (20 * xMult), yPos)] = color;
	Result[int2(xPos + (27 * xMult), yPos)] = color;
	Result[int2(xPos + (28 * xMult), yPos)] = color;
	Result[int2(xPos + (36 * xMult), yPos)] = color;
	Result[int2(xPos + (45 * xMult), yPos)] = color;
	Result[int2(xPos + (46 * xMult), yPos)] = color;
	Result[int2(xPos + (56 * xMult), yPos)] = color;
	Result[int2(xPos + (67 * xMult), yPos)] = color;
	Result[int2(xPos + (68 * xMult), yPos)] = color;
	Result[int2(xPos + (3 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (47 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (47 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (9 * yMult))] = color;
}