#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 12, yPos)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos + 29, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 14)] = color;
	Result[int2(xPos + 30, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 28, yPos - 15)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 5, yPos - 18)] = color;
	Result[int2(xPos + 4, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 20)] = color;
	Result[int2(xPos + 35, yPos - 20)] = color;
	Result[int2(xPos + 34, yPos - 21)] = color;
	Result[int2(xPos + 35, yPos - 21)] = color;
	Result[int2(xPos + 25, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 23)] = color;
	Result[int2(xPos + 25, yPos - 24)] = color;
	Result[int2(xPos + 26, yPos - 24)] = color;
	Result[int2(xPos + 15, yPos - 34)] = color;
	Result[int2(xPos + 16, yPos - 34)] = color;
	Result[int2(xPos + 14, yPos - 35)] = color;
	Result[int2(xPos + 17, yPos - 35)] = color;
	Result[int2(xPos + 15, yPos - 36)] = color;
	Result[int2(xPos + 16, yPos - 36)] = color;
}