#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 20, yPos)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 8, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 21, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 21, yPos - 22)] = color;
	Result[int2(xPos + 22, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
	Result[int2(xPos + 3, yPos - 23)] = color;
	Result[int2(xPos + 8, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 10, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos, yPos - 26)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
}