#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (53 * xMult), yPos)] = color;
	Result[int2(xPos + (54 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (47 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (47 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (86 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos, yPos - (40 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (44 * yMult))] = color;
}