#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 21, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 19, yPos - 4)] = color;
	Result[int2(xPos + 18, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 38, yPos - 5)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 37, yPos - 6)] = color;
	Result[int2(xPos + 39, yPos - 6)] = color;
	Result[int2(xPos + 37, yPos - 7)] = color;
	Result[int2(xPos + 40, yPos - 7)] = color;
	Result[int2(xPos + 44, yPos - 7)] = color;
	Result[int2(xPos + 45, yPos - 7)] = color;
	Result[int2(xPos + 46, yPos - 7)] = color;
	Result[int2(xPos + 37, yPos - 8)] = color;
	Result[int2(xPos + 39, yPos - 8)] = color;
	Result[int2(xPos + 43, yPos - 8)] = color;
	Result[int2(xPos + 47, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 38, yPos - 9)] = color;
	Result[int2(xPos + 43, yPos - 9)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 43, yPos - 10)] = color;
	Result[int2(xPos + 44, yPos - 10)] = color;
	Result[int2(xPos + 46, yPos - 10)] = color;
	Result[int2(xPos + 47, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 18, yPos - 11)] = color;
	Result[int2(xPos + 45, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
}