#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 6, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 69, yPos - 14)] = color;
	Result[int2(xPos + 67, yPos - 15)] = color;
	Result[int2(xPos + 68, yPos - 15)] = color;
	Result[int2(xPos + 68, yPos - 16)] = color;
	Result[int2(xPos + 69, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 30)] = color;
	Result[int2(xPos + 23, yPos - 30)] = color;
	Result[int2(xPos + 22, yPos - 31)] = color;
	Result[int2(xPos + 23, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 32)] = color;
	Result[int2(xPos + 26, yPos - 33)] = color;
	Result[int2(xPos + 27, yPos - 34)] = color;
	Result[int2(xPos + 28, yPos - 34)] = color;
	Result[int2(xPos + 26, yPos - 35)] = color;
	Result[int2(xPos + 27, yPos - 35)] = color;
	Result[int2(xPos + 30, yPos - 35)] = color;
	Result[int2(xPos + 32, yPos - 35)] = color;
	Result[int2(xPos + 30, yPos - 36)] = color;
	Result[int2(xPos + 31, yPos - 36)] = color;
	Result[int2(xPos + 31, yPos - 37)] = color;
	Result[int2(xPos + 33, yPos - 45)] = color;
	Result[int2(xPos + 34, yPos - 46)] = color;
	Result[int2(xPos + 32, yPos - 47)] = color;
	Result[int2(xPos + 33, yPos - 47)] = color;
	Result[int2(xPos + 34, yPos - 47)] = color;
	Result[int2(xPos + 37, yPos - 49)] = color;
	Result[int2(xPos + 38, yPos - 49)] = color;
	Result[int2(xPos + 31, yPos - 50)] = color;
	Result[int2(xPos + 32, yPos - 50)] = color;
	Result[int2(xPos + 33, yPos - 50)] = color;
	Result[int2(xPos + 36, yPos - 50)] = color;
	Result[int2(xPos + 37, yPos - 50)] = color;
	Result[int2(xPos + 31, yPos - 51)] = color;
	Result[int2(xPos + 38, yPos - 51)] = color;
	Result[int2(xPos + 32, yPos - 52)] = color;
}