#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 42, yPos)] = color;
	Result[int2(xPos + 43, yPos - 1)] = color;
	Result[int2(xPos + 44, yPos - 1)] = color;
	Result[int2(xPos + 42, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 5, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 28, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 51, yPos - 9)] = color;
	Result[int2(xPos + 52, yPos - 9)] = color;
	Result[int2(xPos + 68, yPos - 9)] = color;
	Result[int2(xPos + 69, yPos - 9)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 50, yPos - 10)] = color;
	Result[int2(xPos + 51, yPos - 10)] = color;
	Result[int2(xPos + 68, yPos - 10)] = color;
	Result[int2(xPos + 70, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 52, yPos - 11)] = color;
	Result[int2(xPos + 71, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 72, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 32, yPos - 13)] = color;
	Result[int2(xPos + 48, yPos - 13)] = color;
	Result[int2(xPos + 50, yPos - 13)] = color;
	Result[int2(xPos + 71, yPos - 13)] = color;
	Result[int2(xPos + 72, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 49, yPos - 14)] = color;
	Result[int2(xPos + 50, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 15)] = color;
	Result[int2(xPos + 49, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos + 49, yPos - 17)] = color;
	Result[int2(xPos + 50, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 12, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 48, yPos - 18)] = color;
	Result[int2(xPos + 49, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 50, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
}