#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 45, yPos - 4)] = color;
	Result[int2(xPos + 46, yPos - 4)] = color;
	Result[int2(xPos + 49, yPos - 4)] = color;
	Result[int2(xPos + 45, yPos - 5)] = color;
	Result[int2(xPos + 48, yPos - 5)] = color;
	Result[int2(xPos + 50, yPos - 5)] = color;
	Result[int2(xPos + 47, yPos - 6)] = color;
	Result[int2(xPos + 48, yPos - 6)] = color;
	Result[int2(xPos + 51, yPos - 6)] = color;
	Result[int2(xPos + 50, yPos - 7)] = color;
	Result[int2(xPos + 51, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
}