#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 34, yPos)] = color;
	Result[int2(xPos + 35, yPos)] = color;
	Result[int2(xPos + 49, yPos)] = color;
	Result[int2(xPos + 50, yPos)] = color;
	Result[int2(xPos + 58, yPos)] = color;
	Result[int2(xPos + 59, yPos)] = color;
	Result[int2(xPos + 60, yPos)] = color;
	Result[int2(xPos + 61, yPos)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 37, yPos - 1)] = color;
	Result[int2(xPos + 48, yPos - 1)] = color;
	Result[int2(xPos + 49, yPos - 1)] = color;
	Result[int2(xPos + 51, yPos - 1)] = color;
	Result[int2(xPos + 52, yPos - 1)] = color;
	Result[int2(xPos + 53, yPos - 1)] = color;
	Result[int2(xPos + 54, yPos - 1)] = color;
	Result[int2(xPos + 58, yPos - 1)] = color;
	Result[int2(xPos + 62, yPos - 1)] = color;
	Result[int2(xPos + 31, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 50, yPos - 2)] = color;
	Result[int2(xPos + 51, yPos - 2)] = color;
	Result[int2(xPos + 52, yPos - 2)] = color;
	Result[int2(xPos + 53, yPos - 2)] = color;
	Result[int2(xPos + 54, yPos - 2)] = color;
	Result[int2(xPos + 58, yPos - 2)] = color;
	Result[int2(xPos + 31, yPos - 3)] = color;
	Result[int2(xPos + 37, yPos - 3)] = color;
	Result[int2(xPos + 50, yPos - 3)] = color;
	Result[int2(xPos + 51, yPos - 3)] = color;
	Result[int2(xPos + 52, yPos - 3)] = color;
	Result[int2(xPos + 53, yPos - 3)] = color;
	Result[int2(xPos + 59, yPos - 3)] = color;
	Result[int2(xPos + 62, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 31, yPos - 4)] = color;
	Result[int2(xPos + 32, yPos - 4)] = color;
	Result[int2(xPos + 33, yPos - 4)] = color;
	Result[int2(xPos + 34, yPos - 4)] = color;
	Result[int2(xPos + 35, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 6, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 7, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 31, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 35, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
}