#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 5, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 13, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 30, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 17)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 30, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
	Result[int2(xPos + 14, yPos - 19)] = color;
	Result[int2(xPos + 15, yPos - 19)] = color;
	Result[int2(xPos + 30, yPos - 19)] = color;
	Result[int2(xPos + 31, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 3, yPos - 25)] = color;
	Result[int2(xPos + 7, yPos - 25)] = color;
	Result[int2(xPos + 8, yPos - 25)] = color;
	Result[int2(xPos + 9, yPos - 25)] = color;
	Result[int2(xPos, yPos - 26)] = color;
	Result[int2(xPos + 3, yPos - 26)] = color;
	Result[int2(xPos + 7, yPos - 26)] = color;
	Result[int2(xPos + 10, yPos - 26)] = color;
	Result[int2(xPos, yPos - 27)] = color;
	Result[int2(xPos + 1, yPos - 27)] = color;
	Result[int2(xPos + 3, yPos - 27)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 9, yPos - 27)] = color;
	Result[int2(xPos + 10, yPos - 27)] = color;
	Result[int2(xPos + 1, yPos - 43)] = color;
	Result[int2(xPos + 2, yPos - 43)] = color;
	Result[int2(xPos + 8, yPos - 43)] = color;
	Result[int2(xPos + 9, yPos - 43)] = color;
	Result[int2(xPos + 1, yPos - 44)] = color;
	Result[int2(xPos + 2, yPos - 44)] = color;
	Result[int2(xPos + 8, yPos - 44)] = color;
	Result[int2(xPos + 9, yPos - 44)] = color;
}