#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 24, yPos)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 24, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 21, yPos - 5)] = color;
	Result[int2(xPos + 22, yPos - 5)] = color;
	Result[int2(xPos + 23, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 21, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 10)] = color;
	Result[int2(xPos + 38, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 37, yPos - 11)] = color;
	Result[int2(xPos + 38, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 30, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 35, yPos - 13)] = color;
	Result[int2(xPos + 37, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 29, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 37, yPos - 14)] = color;
	Result[int2(xPos + 40, yPos - 14)] = color;
	Result[int2(xPos + 41, yPos - 14)] = color;
	Result[int2(xPos + 42, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 29, yPos - 16)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 40, yPos - 19)] = color;
	Result[int2(xPos + 41, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 40, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 41, yPos - 21)] = color;
	Result[int2(xPos + 42, yPos - 21)] = color;
	Result[int2(xPos + 43, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 43, yPos - 22)] = color;
}