#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 12)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 42)) * yMult)] = color;
}