#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 51)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 76)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 24)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 76)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 51)) * yMult)] = color;
}