#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 23, yPos)] = color;
	Result[int2(xPos + 42, yPos)] = color;
	Result[int2(xPos + 43, yPos)] = color;
	Result[int2(xPos + 62, yPos)] = color;
	Result[int2(xPos + 63, yPos)] = color;
	Result[int2(xPos + 82, yPos)] = color;
	Result[int2(xPos + 83, yPos)] = color;
	Result[int2(xPos + 102, yPos)] = color;
	Result[int2(xPos + 103, yPos)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 42, yPos - 1)] = color;
	Result[int2(xPos + 62, yPos - 1)] = color;
	Result[int2(xPos + 82, yPos - 1)] = color;
	Result[int2(xPos + 102, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 45, yPos - 2)] = color;
	Result[int2(xPos + 65, yPos - 2)] = color;
	Result[int2(xPos + 85, yPos - 2)] = color;
	Result[int2(xPos + 105, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 25, yPos - 3)] = color;
	Result[int2(xPos + 44, yPos - 3)] = color;
	Result[int2(xPos + 45, yPos - 3)] = color;
	Result[int2(xPos + 64, yPos - 3)] = color;
	Result[int2(xPos + 65, yPos - 3)] = color;
	Result[int2(xPos + 84, yPos - 3)] = color;
	Result[int2(xPos + 85, yPos - 3)] = color;
	Result[int2(xPos + 104, yPos - 3)] = color;
	Result[int2(xPos + 105, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 64, yPos - 5)] = color;
	Result[int2(xPos + 65, yPos - 5)] = color;
	Result[int2(xPos + 84, yPos - 5)] = color;
	Result[int2(xPos + 85, yPos - 5)] = color;
	Result[int2(xPos + 102, yPos - 5)] = color;
	Result[int2(xPos + 103, yPos - 5)] = color;
	Result[int2(xPos + 104, yPos - 5)] = color;
	Result[int2(xPos + 105, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 42, yPos - 6)] = color;
	Result[int2(xPos + 43, yPos - 6)] = color;
	Result[int2(xPos + 44, yPos - 6)] = color;
	Result[int2(xPos + 63, yPos - 6)] = color;
	Result[int2(xPos + 65, yPos - 6)] = color;
	Result[int2(xPos + 76, yPos - 6)] = color;
	Result[int2(xPos + 83, yPos - 6)] = color;
	Result[int2(xPos + 85, yPos - 6)] = color;
	Result[int2(xPos + 102, yPos - 6)] = color;
	Result[int2(xPos + 105, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 44, yPos - 7)] = color;
	Result[int2(xPos + 64, yPos - 7)] = color;
	Result[int2(xPos + 74, yPos - 7)] = color;
	Result[int2(xPos + 76, yPos - 7)] = color;
	Result[int2(xPos + 84, yPos - 7)] = color;
	Result[int2(xPos + 103, yPos - 7)] = color;
	Result[int2(xPos + 104, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 43, yPos - 8)] = color;
	Result[int2(xPos + 75, yPos - 8)] = color;
	Result[int2(xPos + 76, yPos - 8)] = color;
	Result[int2(xPos + 78, yPos - 9)] = color;
	Result[int2(xPos + 79, yPos - 9)] = color;
	Result[int2(xPos + 79, yPos - 10)] = color;
	Result[int2(xPos + 80, yPos - 10)] = color;
	Result[int2(xPos + 78, yPos - 11)] = color;
}