#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 76, yPos)] = color;
	Result[int2(xPos + 75, yPos - 1)] = color;
	Result[int2(xPos + 75, yPos - 2)] = color;
	Result[int2(xPos + 76, yPos - 2)] = color;
	Result[int2(xPos + 77, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 73, yPos - 4)] = color;
	Result[int2(xPos + 74, yPos - 4)] = color;
	Result[int2(xPos + 37, yPos - 5)] = color;
	Result[int2(xPos + 41, yPos - 5)] = color;
	Result[int2(xPos + 42, yPos - 5)] = color;
	Result[int2(xPos + 69, yPos - 5)] = color;
	Result[int2(xPos + 73, yPos - 5)] = color;
	Result[int2(xPos + 74, yPos - 5)] = color;
	Result[int2(xPos + 101, yPos - 5)] = color;
	Result[int2(xPos + 36, yPos - 6)] = color;
	Result[int2(xPos + 38, yPos - 6)] = color;
	Result[int2(xPos + 68, yPos - 6)] = color;
	Result[int2(xPos + 70, yPos - 6)] = color;
	Result[int2(xPos + 100, yPos - 6)] = color;
	Result[int2(xPos + 102, yPos - 6)] = color;
	Result[int2(xPos + 35, yPos - 7)] = color;
	Result[int2(xPos + 37, yPos - 7)] = color;
	Result[int2(xPos + 38, yPos - 7)] = color;
	Result[int2(xPos + 67, yPos - 7)] = color;
	Result[int2(xPos + 69, yPos - 7)] = color;
	Result[int2(xPos + 70, yPos - 7)] = color;
	Result[int2(xPos + 99, yPos - 7)] = color;
	Result[int2(xPos + 101, yPos - 7)] = color;
	Result[int2(xPos + 102, yPos - 7)] = color;
	Result[int2(xPos + 35, yPos - 8)] = color;
	Result[int2(xPos + 67, yPos - 8)] = color;
	Result[int2(xPos + 99, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 11, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 65, yPos - 9)] = color;
	Result[int2(xPos + 67, yPos - 9)] = color;
	Result[int2(xPos + 97, yPos - 9)] = color;
	Result[int2(xPos + 99, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 13, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos + 65, yPos - 10)] = color;
	Result[int2(xPos + 66, yPos - 10)] = color;
	Result[int2(xPos + 97, yPos - 10)] = color;
	Result[int2(xPos + 98, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 17, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 7, yPos - 13)] = color;
	Result[int2(xPos + 9, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
}