#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 50, yPos)] = color;
	Result[int2(xPos + 50, yPos - 1)] = color;
	Result[int2(xPos + 52, yPos - 1)] = color;
	Result[int2(xPos + 50, yPos - 2)] = color;
	Result[int2(xPos + 51, yPos - 2)] = color;
	Result[int2(xPos + 47, yPos - 3)] = color;
	Result[int2(xPos + 54, yPos - 3)] = color;
	Result[int2(xPos + 46, yPos - 4)] = color;
	Result[int2(xPos + 53, yPos - 4)] = color;
	Result[int2(xPos + 46, yPos - 5)] = color;
	Result[int2(xPos + 47, yPos - 5)] = color;
	Result[int2(xPos + 48, yPos - 5)] = color;
	Result[int2(xPos + 53, yPos - 5)] = color;
	Result[int2(xPos + 54, yPos - 5)] = color;
	Result[int2(xPos + 55, yPos - 5)] = color;
	Result[int2(xPos + 43, yPos - 7)] = color;
	Result[int2(xPos + 50, yPos - 7)] = color;
	Result[int2(xPos + 43, yPos - 8)] = color;
	Result[int2(xPos + 45, yPos - 8)] = color;
	Result[int2(xPos + 50, yPos - 8)] = color;
	Result[int2(xPos + 52, yPos - 8)] = color;
	Result[int2(xPos + 58, yPos - 8)] = color;
	Result[int2(xPos + 43, yPos - 9)] = color;
	Result[int2(xPos + 44, yPos - 9)] = color;
	Result[int2(xPos + 50, yPos - 9)] = color;
	Result[int2(xPos + 51, yPos - 9)] = color;
	Result[int2(xPos + 56, yPos - 9)] = color;
	Result[int2(xPos + 57, yPos - 9)] = color;
	Result[int2(xPos + 40, yPos - 10)] = color;
	Result[int2(xPos + 48, yPos - 10)] = color;
	Result[int2(xPos + 57, yPos - 10)] = color;
	Result[int2(xPos + 58, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 11)] = color;
	Result[int2(xPos + 39, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 53, yPos - 12)] = color;
	Result[int2(xPos + 55, yPos - 12)] = color;
	Result[int2(xPos + 53, yPos - 13)] = color;
	Result[int2(xPos + 54, yPos - 13)] = color;
	Result[int2(xPos + 54, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 51, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 49, yPos - 16)] = color;
	Result[int2(xPos + 50, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 50, yPos - 17)] = color;
	Result[int2(xPos + 51, yPos - 17)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 20, yPos - 26)] = color;
	Result[int2(xPos + 27, yPos - 26)] = color;
	Result[int2(xPos + 29, yPos - 26)] = color;
	Result[int2(xPos + 18, yPos - 27)] = color;
	Result[int2(xPos + 20, yPos - 27)] = color;
	Result[int2(xPos + 28, yPos - 27)] = color;
	Result[int2(xPos + 29, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 20, yPos - 28)] = color;
	Result[int2(xPos + 25, yPos - 29)] = color;
	Result[int2(xPos + 26, yPos - 30)] = color;
	Result[int2(xPos + 31, yPos - 30)] = color;
	Result[int2(xPos + 32, yPos - 30)] = color;
	Result[int2(xPos + 33, yPos - 30)] = color;
	Result[int2(xPos + 24, yPos - 31)] = color;
	Result[int2(xPos + 25, yPos - 31)] = color;
	Result[int2(xPos + 26, yPos - 31)] = color;
	Result[int2(xPos + 31, yPos - 31)] = color;
	Result[int2(xPos + 32, yPos - 32)] = color;
	Result[int2(xPos + 37, yPos - 33)] = color;
	Result[int2(xPos + 38, yPos - 33)] = color;
	Result[int2(xPos + 28, yPos - 34)] = color;
	Result[int2(xPos + 29, yPos - 34)] = color;
	Result[int2(xPos + 37, yPos - 34)] = color;
	Result[int2(xPos + 39, yPos - 34)] = color;
	Result[int2(xPos + 28, yPos - 35)] = color;
	Result[int2(xPos + 30, yPos - 35)] = color;
	Result[int2(xPos + 37, yPos - 35)] = color;
	Result[int2(xPos + 28, yPos - 36)] = color;
	Result[int2(xPos + 45, yPos - 54)] = color;
	Result[int2(xPos + 46, yPos - 54)] = color;
	Result[int2(xPos + 45, yPos - 55)] = color;
	Result[int2(xPos + 47, yPos - 55)] = color;
	Result[int2(xPos + 45, yPos - 56)] = color;
}