#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 29, yPos)] = color;
	Result[int2(xPos + 30, yPos)] = color;
	Result[int2(xPos + 31, yPos)] = color;
	Result[int2(xPos + 32, yPos)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 30, yPos - 1)] = color;
	Result[int2(xPos + 31, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 29, yPos - 2)] = color;
	Result[int2(xPos + 30, yPos - 2)] = color;
	Result[int2(xPos + 31, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 32, yPos - 3)] = color;
	Result[int2(xPos + 33, yPos - 3)] = color;
	Result[int2(xPos + 38, yPos - 7)] = color;
	Result[int2(xPos + 39, yPos - 7)] = color;
	Result[int2(xPos + 40, yPos - 7)] = color;
	Result[int2(xPos + 41, yPos - 7)] = color;
	Result[int2(xPos + 42, yPos - 7)] = color;
	Result[int2(xPos + 43, yPos - 7)] = color;
	Result[int2(xPos + 26, yPos - 8)] = color;
	Result[int2(xPos + 27, yPos - 8)] = color;
	Result[int2(xPos + 36, yPos - 8)] = color;
	Result[int2(xPos + 37, yPos - 8)] = color;
	Result[int2(xPos + 43, yPos - 8)] = color;
	Result[int2(xPos + 25, yPos - 9)] = color;
	Result[int2(xPos + 26, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 34, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 37, yPos - 9)] = color;
	Result[int2(xPos + 43, yPos - 9)] = color;
	Result[int2(xPos + 26, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 38, yPos - 10)] = color;
	Result[int2(xPos + 42, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 40, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 39, yPos - 13)] = color;
	Result[int2(xPos + 40, yPos - 13)] = color;
	Result[int2(xPos + 41, yPos - 13)] = color;
	Result[int2(xPos + 42, yPos - 13)] = color;
	Result[int2(xPos + 13, yPos - 14)] = color;
	Result[int2(xPos + 39, yPos - 14)] = color;
	Result[int2(xPos + 40, yPos - 14)] = color;
	Result[int2(xPos + 42, yPos - 14)] = color;
	Result[int2(xPos + 43, yPos - 14)] = color;
	Result[int2(xPos + 41, yPos - 15)] = color;
	Result[int2(xPos + 42, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 29, yPos - 17)] = color;
	Result[int2(xPos + 35, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 18)] = color;
	Result[int2(xPos + 29, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 19)] = color;
	Result[int2(xPos + 31, yPos - 20)] = color;
	Result[int2(xPos + 32, yPos - 20)] = color;
}