#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 23)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 123)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 123)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 125)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 123)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 124)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 98)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 98)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 122)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 121)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 122)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 121)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 123)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 91)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 131)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 132)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 92)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 131)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 133)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 131)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 132)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 133)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 132)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 134)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 132)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 140)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 141)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 140)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 142)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 140)) * xMult), (yPos - 24)) * yMult)] = color;
}