#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos + 29, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 14)] = color;
	Result[int2(xPos + 28, yPos - 14)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos + 25, yPos - 15)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos + 23, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 18)] = color;
	Result[int2(xPos + 39, yPos - 18)] = color;
	Result[int2(xPos + 40, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 19)] = color;
	Result[int2(xPos + 38, yPos - 19)] = color;
	Result[int2(xPos + 39, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 20)] = color;
	Result[int2(xPos + 40, yPos - 20)] = color;
	Result[int2(xPos, yPos - 30)] = color;
	Result[int2(xPos + 1, yPos - 30)] = color;
	Result[int2(xPos + 40, yPos - 30)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 2, yPos - 31)] = color;
	Result[int2(xPos + 39, yPos - 31)] = color;
	Result[int2(xPos + 40, yPos - 31)] = color;
	Result[int2(xPos, yPos - 32)] = color;
	Result[int2(xPos + 39, yPos - 32)] = color;
	Result[int2(xPos + 41, yPos - 32)] = color;
	Result[int2(xPos + 3, yPos - 34)] = color;
	Result[int2(xPos + 4, yPos - 34)] = color;
	Result[int2(xPos + 13, yPos - 34)] = color;
	Result[int2(xPos + 2, yPos - 35)] = color;
	Result[int2(xPos + 4, yPos - 35)] = color;
	Result[int2(xPos + 13, yPos - 35)] = color;
	Result[int2(xPos + 14, yPos - 35)] = color;
	Result[int2(xPos + 4, yPos - 36)] = color;
	Result[int2(xPos + 12, yPos - 36)] = color;
	Result[int2(xPos + 14, yPos - 36)] = color;
	Result[int2(xPos + 7, yPos - 37)] = color;
	Result[int2(xPos + 8, yPos - 37)] = color;
	Result[int2(xPos + 45, yPos - 37)] = color;
	Result[int2(xPos + 46, yPos - 37)] = color;
	Result[int2(xPos + 6, yPos - 38)] = color;
	Result[int2(xPos + 8, yPos - 38)] = color;
	Result[int2(xPos + 45, yPos - 38)] = color;
	Result[int2(xPos + 47, yPos - 38)] = color;
	Result[int2(xPos + 8, yPos - 39)] = color;
	Result[int2(xPos + 45, yPos - 39)] = color;
	Result[int2(xPos + 11, yPos - 40)] = color;
	Result[int2(xPos + 12, yPos - 40)] = color;
	Result[int2(xPos + 13, yPos - 40)] = color;
	Result[int2(xPos + 13, yPos - 41)] = color;
	Result[int2(xPos + 12, yPos - 42)] = color;
	Result[int2(xPos + 42, yPos - 43)] = color;
	Result[int2(xPos + 43, yPos - 43)] = color;
	Result[int2(xPos + 44, yPos - 43)] = color;
	Result[int2(xPos + 42, yPos - 44)] = color;
	Result[int2(xPos + 43, yPos - 45)] = color;
}