#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 1)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 82)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 83)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 84)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 84)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 84)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 103)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 104)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 104)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 105)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 105)) * yMult)] = color;
	Result[int2((xPos + 124)) * xMult), (yPos - 123)) * yMult)] = color;
	Result[int2((xPos + 125)) * xMult), (yPos - 124)) * yMult)] = color;
	Result[int2((xPos + 123)) * xMult), (yPos - 125)) * yMult)] = color;
	Result[int2((xPos + 124)) * xMult), (yPos - 125)) * yMult)] = color;
	Result[int2((xPos + 125)) * xMult), (yPos - 125)) * yMult)] = color;
	Result[int2((xPos + 145)) * xMult), (yPos - 144)) * yMult)] = color;
	Result[int2((xPos + 143)) * xMult), (yPos - 145)) * yMult)] = color;
	Result[int2((xPos + 145)) * xMult), (yPos - 145)) * yMult)] = color;
	Result[int2((xPos + 144)) * xMult), (yPos - 146)) * yMult)] = color;
	Result[int2((xPos + 145)) * xMult), (yPos - 146)) * yMult)] = color;
	Result[int2((xPos + 165)) * xMult), (yPos - 164)) * yMult)] = color;
	Result[int2((xPos + 166)) * xMult), (yPos - 165)) * yMult)] = color;
	Result[int2((xPos + 164)) * xMult), (yPos - 166)) * yMult)] = color;
	Result[int2((xPos + 165)) * xMult), (yPos - 166)) * yMult)] = color;
	Result[int2((xPos + 166)) * xMult), (yPos - 166)) * yMult)] = color;
	Result[int2((xPos + 186)) * xMult), (yPos - 185)) * yMult)] = color;
	Result[int2((xPos + 184)) * xMult), (yPos - 186)) * yMult)] = color;
	Result[int2((xPos + 186)) * xMult), (yPos - 186)) * yMult)] = color;
	Result[int2((xPos + 185)) * xMult), (yPos - 187)) * yMult)] = color;
	Result[int2((xPos + 186)) * xMult), (yPos - 187)) * yMult)] = color;
	Result[int2((xPos + 206)) * xMult), (yPos - 205)) * yMult)] = color;
	Result[int2((xPos + 207)) * xMult), (yPos - 206)) * yMult)] = color;
	Result[int2((xPos + 205)) * xMult), (yPos - 207)) * yMult)] = color;
	Result[int2((xPos + 206)) * xMult), (yPos - 207)) * yMult)] = color;
	Result[int2((xPos + 207)) * xMult), (yPos - 207)) * yMult)] = color;
	Result[int2((xPos + 227)) * xMult), (yPos - 226)) * yMult)] = color;
	Result[int2((xPos + 225)) * xMult), (yPos - 227)) * yMult)] = color;
	Result[int2((xPos + 227)) * xMult), (yPos - 227)) * yMult)] = color;
	Result[int2((xPos + 226)) * xMult), (yPos - 228)) * yMult)] = color;
	Result[int2((xPos + 227)) * xMult), (yPos - 228)) * yMult)] = color;
	Result[int2((xPos + 247)) * xMult), (yPos - 246)) * yMult)] = color;
	Result[int2((xPos + 248)) * xMult), (yPos - 247)) * yMult)] = color;
	Result[int2((xPos + 246)) * xMult), (yPos - 248)) * yMult)] = color;
	Result[int2((xPos + 247)) * xMult), (yPos - 248)) * yMult)] = color;
	Result[int2((xPos + 248)) * xMult), (yPos - 248)) * yMult)] = color;
	Result[int2((xPos + 268)) * xMult), (yPos - 267)) * yMult)] = color;
	Result[int2((xPos + 266)) * xMult), (yPos - 268)) * yMult)] = color;
	Result[int2((xPos + 268)) * xMult), (yPos - 268)) * yMult)] = color;
	Result[int2((xPos + 267)) * xMult), (yPos - 269)) * yMult)] = color;
	Result[int2((xPos + 268)) * xMult), (yPos - 269)) * yMult)] = color;
	Result[int2((xPos + 288)) * xMult), (yPos - 287)) * yMult)] = color;
	Result[int2((xPos + 289)) * xMult), (yPos - 288)) * yMult)] = color;
	Result[int2((xPos + 287)) * xMult), (yPos - 289)) * yMult)] = color;
	Result[int2((xPos + 288)) * xMult), (yPos - 289)) * yMult)] = color;
	Result[int2((xPos + 289)) * xMult), (yPos - 289)) * yMult)] = color;
	Result[int2((xPos + 309)) * xMult), (yPos - 308)) * yMult)] = color;
	Result[int2((xPos + 307)) * xMult), (yPos - 309)) * yMult)] = color;
	Result[int2((xPos + 309)) * xMult), (yPos - 309)) * yMult)] = color;
	Result[int2((xPos + 308)) * xMult), (yPos - 310)) * yMult)] = color;
	Result[int2((xPos + 309)) * xMult), (yPos - 310)) * yMult)] = color;
	Result[int2((xPos + 329)) * xMult), (yPos - 328)) * yMult)] = color;
	Result[int2((xPos + 330)) * xMult), (yPos - 329)) * yMult)] = color;
	Result[int2((xPos + 328)) * xMult), (yPos - 330)) * yMult)] = color;
	Result[int2((xPos + 329)) * xMult), (yPos - 330)) * yMult)] = color;
	Result[int2((xPos + 330)) * xMult), (yPos - 330)) * yMult)] = color;
	Result[int2((xPos + 350)) * xMult), (yPos - 349)) * yMult)] = color;
	Result[int2((xPos + 348)) * xMult), (yPos - 350)) * yMult)] = color;
	Result[int2((xPos + 350)) * xMult), (yPos - 350)) * yMult)] = color;
	Result[int2((xPos + 349)) * xMult), (yPos - 351)) * yMult)] = color;
	Result[int2((xPos + 350)) * xMult), (yPos - 351)) * yMult)] = color;
	Result[int2((xPos + 370)) * xMult), (yPos - 369)) * yMult)] = color;
	Result[int2((xPos + 371)) * xMult), (yPos - 370)) * yMult)] = color;
	Result[int2((xPos + 369)) * xMult), (yPos - 371)) * yMult)] = color;
	Result[int2((xPos + 370)) * xMult), (yPos - 371)) * yMult)] = color;
	Result[int2((xPos + 371)) * xMult), (yPos - 371)) * yMult)] = color;
	Result[int2((xPos + 391)) * xMult), (yPos - 390)) * yMult)] = color;
	Result[int2((xPos + 389)) * xMult), (yPos - 391)) * yMult)] = color;
	Result[int2((xPos + 391)) * xMult), (yPos - 391)) * yMult)] = color;
	Result[int2((xPos + 390)) * xMult), (yPos - 392)) * yMult)] = color;
	Result[int2((xPos + 391)) * xMult), (yPos - 392)) * yMult)] = color;
	Result[int2((xPos + 411)) * xMult), (yPos - 410)) * yMult)] = color;
	Result[int2((xPos + 412)) * xMult), (yPos - 411)) * yMult)] = color;
	Result[int2((xPos + 410)) * xMult), (yPos - 412)) * yMult)] = color;
	Result[int2((xPos + 411)) * xMult), (yPos - 412)) * yMult)] = color;
	Result[int2((xPos + 412)) * xMult), (yPos - 412)) * yMult)] = color;
	Result[int2((xPos + 432)) * xMult), (yPos - 431)) * yMult)] = color;
	Result[int2((xPos + 430)) * xMult), (yPos - 432)) * yMult)] = color;
	Result[int2((xPos + 432)) * xMult), (yPos - 432)) * yMult)] = color;
	Result[int2((xPos + 431)) * xMult), (yPos - 433)) * yMult)] = color;
	Result[int2((xPos + 432)) * xMult), (yPos - 433)) * yMult)] = color;
	Result[int2((xPos + 452)) * xMult), (yPos - 451)) * yMult)] = color;
	Result[int2((xPos + 453)) * xMult), (yPos - 452)) * yMult)] = color;
	Result[int2((xPos + 451)) * xMult), (yPos - 453)) * yMult)] = color;
	Result[int2((xPos + 452)) * xMult), (yPos - 453)) * yMult)] = color;
	Result[int2((xPos + 453)) * xMult), (yPos - 453)) * yMult)] = color;
	Result[int2((xPos + 473)) * xMult), (yPos - 472)) * yMult)] = color;
	Result[int2((xPos + 471)) * xMult), (yPos - 473)) * yMult)] = color;
	Result[int2((xPos + 473)) * xMult), (yPos - 473)) * yMult)] = color;
	Result[int2((xPos + 472)) * xMult), (yPos - 474)) * yMult)] = color;
	Result[int2((xPos + 473)) * xMult), (yPos - 474)) * yMult)] = color;
	Result[int2((xPos + 493)) * xMult), (yPos - 492)) * yMult)] = color;
	Result[int2((xPos + 494)) * xMult), (yPos - 493)) * yMult)] = color;
	Result[int2((xPos + 492)) * xMult), (yPos - 494)) * yMult)] = color;
	Result[int2((xPos + 493)) * xMult), (yPos - 494)) * yMult)] = color;
	Result[int2((xPos + 494)) * xMult), (yPos - 494)) * yMult)] = color;
	Result[int2((xPos + 514)) * xMult), (yPos - 513)) * yMult)] = color;
	Result[int2((xPos + 512)) * xMult), (yPos - 514)) * yMult)] = color;
	Result[int2((xPos + 514)) * xMult), (yPos - 514)) * yMult)] = color;
	Result[int2((xPos + 513)) * xMult), (yPos - 515)) * yMult)] = color;
	Result[int2((xPos + 514)) * xMult), (yPos - 515)) * yMult)] = color;
	Result[int2((xPos + 534)) * xMult), (yPos - 533)) * yMult)] = color;
	Result[int2((xPos + 535)) * xMult), (yPos - 534)) * yMult)] = color;
	Result[int2((xPos + 533)) * xMult), (yPos - 535)) * yMult)] = color;
	Result[int2((xPos + 534)) * xMult), (yPos - 535)) * yMult)] = color;
	Result[int2((xPos + 535)) * xMult), (yPos - 535)) * yMult)] = color;
	Result[int2((xPos + 555)) * xMult), (yPos - 554)) * yMult)] = color;
	Result[int2((xPos + 553)) * xMult), (yPos - 555)) * yMult)] = color;
	Result[int2((xPos + 555)) * xMult), (yPos - 555)) * yMult)] = color;
	Result[int2((xPos + 554)) * xMult), (yPos - 556)) * yMult)] = color;
	Result[int2((xPos + 555)) * xMult), (yPos - 556)) * yMult)] = color;
	Result[int2((xPos + 575)) * xMult), (yPos - 574)) * yMult)] = color;
	Result[int2((xPos + 576)) * xMult), (yPos - 575)) * yMult)] = color;
	Result[int2((xPos + 574)) * xMult), (yPos - 576)) * yMult)] = color;
	Result[int2((xPos + 575)) * xMult), (yPos - 576)) * yMult)] = color;
	Result[int2((xPos + 576)) * xMult), (yPos - 576)) * yMult)] = color;
	Result[int2((xPos + 596)) * xMult), (yPos - 595)) * yMult)] = color;
	Result[int2((xPos + 594)) * xMult), (yPos - 596)) * yMult)] = color;
	Result[int2((xPos + 596)) * xMult), (yPos - 596)) * yMult)] = color;
	Result[int2((xPos + 595)) * xMult), (yPos - 597)) * yMult)] = color;
	Result[int2((xPos + 596)) * xMult), (yPos - 597)) * yMult)] = color;
	Result[int2((xPos + 616)) * xMult), (yPos - 615)) * yMult)] = color;
	Result[int2((xPos + 617)) * xMult), (yPos - 616)) * yMult)] = color;
	Result[int2((xPos + 615)) * xMult), (yPos - 617)) * yMult)] = color;
	Result[int2((xPos + 616)) * xMult), (yPos - 617)) * yMult)] = color;
	Result[int2((xPos + 617)) * xMult), (yPos - 617)) * yMult)] = color;
	Result[int2((xPos + 637)) * xMult), (yPos - 636)) * yMult)] = color;
	Result[int2((xPos + 635)) * xMult), (yPos - 637)) * yMult)] = color;
	Result[int2((xPos + 637)) * xMult), (yPos - 637)) * yMult)] = color;
	Result[int2((xPos + 636)) * xMult), (yPos - 638)) * yMult)] = color;
	Result[int2((xPos + 637)) * xMult), (yPos - 638)) * yMult)] = color;
	Result[int2((xPos + 657)) * xMult), (yPos - 656)) * yMult)] = color;
	Result[int2((xPos + 658)) * xMult), (yPos - 657)) * yMult)] = color;
	Result[int2((xPos + 662)) * xMult), (yPos - 657)) * yMult)] = color;
	Result[int2((xPos + 663)) * xMult), (yPos - 657)) * yMult)] = color;
	Result[int2((xPos + 656)) * xMult), (yPos - 658)) * yMult)] = color;
	Result[int2((xPos + 657)) * xMult), (yPos - 658)) * yMult)] = color;
	Result[int2((xPos + 658)) * xMult), (yPos - 658)) * yMult)] = color;
	Result[int2((xPos + 662)) * xMult), (yPos - 658)) * yMult)] = color;
	Result[int2((xPos + 663)) * xMult), (yPos - 658)) * yMult)] = color;
}