#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (50 * xMult), yPos)] = color;
	Result[int2(xPos + (5 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos, yPos - (4 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (69 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (7 * yMult))] = color;
}