#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 44, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 42, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 3)] = color;
	Result[int2(xPos + 44, yPos - 3)] = color;
	Result[int2(xPos, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 25, yPos - 9)] = color;
	Result[int2(xPos + 25, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 25, yPos - 11)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 57, yPos - 13)] = color;
	Result[int2(xPos + 59, yPos - 13)] = color;
	Result[int2(xPos + 22, yPos - 14)] = color;
	Result[int2(xPos + 24, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 57, yPos - 14)] = color;
	Result[int2(xPos + 58, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 15)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 58, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 40, yPos - 16)] = color;
	Result[int2(xPos + 41, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 40, yPos - 17)] = color;
	Result[int2(xPos + 42, yPos - 17)] = color;
	Result[int2(xPos + 48, yPos - 17)] = color;
	Result[int2(xPos + 49, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 15, yPos - 18)] = color;
	Result[int2(xPos + 40, yPos - 18)] = color;
	Result[int2(xPos + 48, yPos - 18)] = color;
	Result[int2(xPos + 50, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
	Result[int2(xPos + 15, yPos - 19)] = color;
	Result[int2(xPos + 48, yPos - 19)] = color;
	Result[int2(xPos + 46, yPos - 21)] = color;
	Result[int2(xPos + 47, yPos - 21)] = color;
	Result[int2(xPos + 45, yPos - 22)] = color;
	Result[int2(xPos + 47, yPos - 22)] = color;
	Result[int2(xPos + 47, yPos - 23)] = color;
	Result[int2(xPos + 71, yPos - 25)] = color;
	Result[int2(xPos + 72, yPos - 25)] = color;
	Result[int2(xPos + 70, yPos - 26)] = color;
	Result[int2(xPos + 71, yPos - 26)] = color;
	Result[int2(xPos + 72, yPos - 27)] = color;
	Result[int2(xPos + 28, yPos - 29)] = color;
	Result[int2(xPos + 29, yPos - 29)] = color;
	Result[int2(xPos + 29, yPos - 30)] = color;
	Result[int2(xPos + 30, yPos - 30)] = color;
	Result[int2(xPos + 45, yPos - 30)] = color;
	Result[int2(xPos + 46, yPos - 30)] = color;
	Result[int2(xPos + 47, yPos - 30)] = color;
	Result[int2(xPos + 28, yPos - 31)] = color;
	Result[int2(xPos + 45, yPos - 31)] = color;
	Result[int2(xPos + 46, yPos - 32)] = color;
}