#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 46, yPos)] = color;
	Result[int2(xPos + 46, yPos - 1)] = color;
	Result[int2(xPos + 48, yPos - 1)] = color;
	Result[int2(xPos + 46, yPos - 2)] = color;
	Result[int2(xPos + 47, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 21)] = color;
	Result[int2(xPos + 8, yPos - 21)] = color;
	Result[int2(xPos + 8, yPos - 22)] = color;
	Result[int2(xPos + 8, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 9, yPos - 24)] = color;
	Result[int2(xPos + 10, yPos - 24)] = color;
	Result[int2(xPos + 28, yPos - 30)] = color;
	Result[int2(xPos + 29, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 31)] = color;
	Result[int2(xPos + 28, yPos - 31)] = color;
	Result[int2(xPos + 30, yPos - 31)] = color;
	Result[int2(xPos + 9, yPos - 32)] = color;
	Result[int2(xPos + 11, yPos - 32)] = color;
	Result[int2(xPos + 30, yPos - 32)] = color;
	Result[int2(xPos + 9, yPos - 33)] = color;
	Result[int2(xPos + 10, yPos - 33)] = color;
	Result[int2(xPos + 11, yPos - 33)] = color;
	Result[int2(xPos + 24, yPos - 33)] = color;
	Result[int2(xPos + 25, yPos - 33)] = color;
	Result[int2(xPos + 30, yPos - 33)] = color;
	Result[int2(xPos + 31, yPos - 33)] = color;
	Result[int2(xPos + 11, yPos - 34)] = color;
	Result[int2(xPos + 24, yPos - 34)] = color;
	Result[int2(xPos + 26, yPos - 34)] = color;
	Result[int2(xPos + 26, yPos - 35)] = color;
	Result[int2(xPos + 26, yPos - 36)] = color;
	Result[int2(xPos + 27, yPos - 36)] = color;
	Result[int2(xPos + 2, yPos - 39)] = color;
	Result[int2(xPos + 3, yPos - 39)] = color;
	Result[int2(xPos + 3, yPos - 40)] = color;
	Result[int2(xPos, yPos - 41)] = color;
	Result[int2(xPos + 1, yPos - 41)] = color;
	Result[int2(xPos + 2, yPos - 41)] = color;
	Result[int2(xPos, yPos - 42)] = color;
}