#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 11, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 9)] = color;
	Result[int2(xPos + 13, yPos - 9)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 8, yPos - 13)] = color;
	Result[int2(xPos + 10, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 5, yPos - 18)] = color;
	Result[int2(xPos + 6, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 5, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 20)] = color;
	Result[int2(xPos + 4, yPos - 21)] = color;
}