#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 107)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 110)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 110)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 106)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 108)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 110)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 112)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 106)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 112)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 76)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 95)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 96)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 97)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 98)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 111)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 91)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 92)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 94)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 95)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 99)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 70)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 71)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 91)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 92)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 95)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 69)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 73)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 93)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 101)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 70)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 72)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 75)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 99)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 61)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 74)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 100)) * xMult), (yPos - 10)) * yMult)] = color;
}