#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 36, yPos)] = color;
	Result[int2(xPos + 38, yPos)] = color;
	Result[int2(xPos + 37, yPos - 1)] = color;
	Result[int2(xPos + 38, yPos - 1)] = color;
	Result[int2(xPos + 37, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 4)] = color;
	Result[int2(xPos + 58, yPos - 4)] = color;
	Result[int2(xPos + 59, yPos - 4)] = color;
	Result[int2(xPos + 34, yPos - 5)] = color;
	Result[int2(xPos + 36, yPos - 5)] = color;
	Result[int2(xPos + 58, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 21, yPos - 6)] = color;
	Result[int2(xPos + 36, yPos - 6)] = color;
	Result[int2(xPos + 40, yPos - 6)] = color;
	Result[int2(xPos + 41, yPos - 6)] = color;
	Result[int2(xPos + 59, yPos - 6)] = color;
	Result[int2(xPos + 60, yPos - 6)] = color;
	Result[int2(xPos + 61, yPos - 6)] = color;
	Result[int2(xPos + 21, yPos - 7)] = color;
	Result[int2(xPos + 41, yPos - 7)] = color;
	Result[int2(xPos + 61, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 41, yPos - 8)] = color;
	Result[int2(xPos + 43, yPos - 8)] = color;
	Result[int2(xPos + 61, yPos - 8)] = color;
	Result[int2(xPos + 63, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 42, yPos - 9)] = color;
	Result[int2(xPos + 43, yPos - 9)] = color;
	Result[int2(xPos + 62, yPos - 9)] = color;
	Result[int2(xPos + 63, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 33, yPos - 31)] = color;
	Result[int2(xPos + 34, yPos - 31)] = color;
	Result[int2(xPos + 32, yPos - 32)] = color;
	Result[int2(xPos + 34, yPos - 32)] = color;
	Result[int2(xPos + 37, yPos - 32)] = color;
	Result[int2(xPos + 34, yPos - 33)] = color;
	Result[int2(xPos + 37, yPos - 33)] = color;
	Result[int2(xPos + 39, yPos - 33)] = color;
	Result[int2(xPos + 37, yPos - 34)] = color;
	Result[int2(xPos + 38, yPos - 34)] = color;
	Result[int2(xPos + 58, yPos - 34)] = color;
	Result[int2(xPos + 59, yPos - 34)] = color;
	Result[int2(xPos + 58, yPos - 35)] = color;
	Result[int2(xPos + 40, yPos - 36)] = color;
	Result[int2(xPos + 41, yPos - 36)] = color;
	Result[int2(xPos + 59, yPos - 36)] = color;
	Result[int2(xPos + 60, yPos - 36)] = color;
	Result[int2(xPos + 61, yPos - 36)] = color;
	Result[int2(xPos + 41, yPos - 37)] = color;
	Result[int2(xPos + 61, yPos - 37)] = color;
	Result[int2(xPos + 41, yPos - 38)] = color;
	Result[int2(xPos + 43, yPos - 38)] = color;
	Result[int2(xPos + 61, yPos - 38)] = color;
	Result[int2(xPos + 63, yPos - 38)] = color;
	Result[int2(xPos + 42, yPos - 39)] = color;
	Result[int2(xPos + 43, yPos - 39)] = color;
	Result[int2(xPos + 62, yPos - 39)] = color;
	Result[int2(xPos + 63, yPos - 39)] = color;
}