#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
	Result[int2(xPos + 25, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 23)] = color;
	Result[int2(xPos + 19, yPos - 24)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
	Result[int2(xPos + 26, yPos - 24)] = color;
	Result[int2(xPos + 19, yPos - 25)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 23, yPos - 25)] = color;
	Result[int2(xPos + 24, yPos - 25)] = color;
	Result[int2(xPos + 25, yPos - 25)] = color;
	Result[int2(xPos + 12, yPos - 26)] = color;
	Result[int2(xPos + 13, yPos - 26)] = color;
	Result[int2(xPos + 21, yPos - 26)] = color;
	Result[int2(xPos + 23, yPos - 26)] = color;
	Result[int2(xPos + 12, yPos - 27)] = color;
	Result[int2(xPos + 13, yPos - 27)] = color;
	Result[int2(xPos + 21, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
}