#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 8)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 7, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 20, yPos - 9)] = color;
	Result[int2(xPos + 6, yPos - 10)] = color;
	Result[int2(xPos + 7, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 9, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 14, yPos - 21)] = color;
	Result[int2(xPos + 15, yPos - 21)] = color;
	Result[int2(xPos + 14, yPos - 22)] = color;
	Result[int2(xPos + 16, yPos - 22)] = color;
	Result[int2(xPos + 16, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 24)] = color;
}