#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 14, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 5, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 15, yPos - 3)] = color;
	Result[int2(xPos + 19, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
	Result[int2(xPos + 25, yPos - 6)] = color;
	Result[int2(xPos + 26, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 20, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 25, yPos - 15)] = color;
	Result[int2(xPos + 27, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 27, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos + 13, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 27, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 12, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 28)] = color;
	Result[int2(xPos + 12, yPos - 28)] = color;
	Result[int2(xPos + 14, yPos - 28)] = color;
	Result[int2(xPos + 15, yPos - 29)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 31)] = color;
	Result[int2(xPos + 15, yPos - 31)] = color;
	Result[int2(xPos + 16, yPos - 31)] = color;
	Result[int2(xPos + 15, yPos - 32)] = color;
	Result[int2(xPos + 16, yPos - 32)] = color;
}