#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 50, yPos)] = color;
	Result[int2(xPos + 51, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 50, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 50, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 25, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 39, yPos - 3)] = color;
	Result[int2(xPos + 40, yPos - 3)] = color;
	Result[int2(xPos + 48, yPos - 3)] = color;
	Result[int2(xPos + 49, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 39, yPos - 4)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 41, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 6)] = color;
	Result[int2(xPos + 12, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 16, yPos - 6)] = color;
	Result[int2(xPos + 39, yPos - 6)] = color;
	Result[int2(xPos + 40, yPos - 6)] = color;
	Result[int2(xPos + 41, yPos - 6)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 15, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 10)] = color;
	Result[int2(xPos + 40, yPos - 10)] = color;
	Result[int2(xPos + 41, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 11)] = color;
	Result[int2(xPos + 41, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 39, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 25, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 13)] = color;
	Result[int2(xPos + 39, yPos - 13)] = color;
	Result[int2(xPos + 40, yPos - 13)] = color;
	Result[int2(xPos + 48, yPos - 13)] = color;
	Result[int2(xPos + 49, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 48, yPos - 14)] = color;
	Result[int2(xPos + 50, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 50, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 50, yPos - 16)] = color;
	Result[int2(xPos + 51, yPos - 16)] = color;
	Result[int2(xPos + 23, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 20)] = color;
	Result[int2(xPos + 23, yPos - 20)] = color;
	Result[int2(xPos + 24, yPos - 20)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 23, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 23)] = color;
	Result[int2(xPos + 22, yPos - 23)] = color;
	Result[int2(xPos + 19, yPos - 24)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
}