#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 11, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 6, yPos - 8)] = color;
	Result[int2(xPos + 13, yPos - 8)] = color;
	Result[int2(xPos + 7, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 11)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 13, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos, yPos - 23)] = color;
}