#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 64, yPos)] = color;
	Result[int2(xPos + 43, yPos - 1)] = color;
	Result[int2(xPos + 63, yPos - 1)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 63, yPos - 2)] = color;
	Result[int2(xPos + 64, yPos - 2)] = color;
	Result[int2(xPos + 65, yPos - 2)] = color;
	Result[int2(xPos + 42, yPos - 3)] = color;
	Result[int2(xPos + 43, yPos - 3)] = color;
	Result[int2(xPos + 42, yPos - 10)] = color;
	Result[int2(xPos + 44, yPos - 10)] = color;
	Result[int2(xPos + 43, yPos - 11)] = color;
	Result[int2(xPos + 44, yPos - 11)] = color;
	Result[int2(xPos + 43, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 56, yPos - 16)] = color;
	Result[int2(xPos + 57, yPos - 16)] = color;
	Result[int2(xPos + 60, yPos - 16)] = color;
	Result[int2(xPos + 61, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 17, yPos - 17)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 55, yPos - 17)] = color;
	Result[int2(xPos + 57, yPos - 17)] = color;
	Result[int2(xPos + 59, yPos - 17)] = color;
	Result[int2(xPos + 60, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 18)] = color;
	Result[int2(xPos + 8, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
	Result[int2(xPos + 57, yPos - 18)] = color;
	Result[int2(xPos + 61, yPos - 18)] = color;
	Result[int2(xPos + 73, yPos - 18)] = color;
	Result[int2(xPos + 74, yPos - 18)] = color;
	Result[int2(xPos + 6, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 19)] = color;
	Result[int2(xPos + 30, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 35, yPos - 19)] = color;
	Result[int2(xPos + 69, yPos - 19)] = color;
	Result[int2(xPos + 70, yPos - 19)] = color;
	Result[int2(xPos + 73, yPos - 19)] = color;
	Result[int2(xPos + 75, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 20)] = color;
	Result[int2(xPos + 35, yPos - 20)] = color;
	Result[int2(xPos + 69, yPos - 20)] = color;
	Result[int2(xPos + 75, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 21)] = color;
	Result[int2(xPos + 32, yPos - 21)] = color;
	Result[int2(xPos + 33, yPos - 21)] = color;
	Result[int2(xPos + 34, yPos - 21)] = color;
	Result[int2(xPos + 70, yPos - 21)] = color;
	Result[int2(xPos + 71, yPos - 21)] = color;
	Result[int2(xPos + 72, yPos - 21)] = color;
	Result[int2(xPos + 73, yPos - 21)] = color;
	Result[int2(xPos + 74, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 5, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 72, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
	Result[int2(xPos + 5, yPos - 23)] = color;
	Result[int2(xPos + 7, yPos - 23)] = color;
	Result[int2(xPos + 5, yPos - 24)] = color;
}