#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 7, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 19)] = color;
	Result[int2(xPos + 8, yPos - 19)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 8, yPos - 27)] = color;
	Result[int2(xPos + 9, yPos - 27)] = color;
	Result[int2(xPos + 8, yPos - 28)] = color;
	Result[int2(xPos + 9, yPos - 28)] = color;
	Result[int2(xPos + 3, yPos - 34)] = color;
	Result[int2(xPos + 4, yPos - 34)] = color;
	Result[int2(xPos + 1, yPos - 35)] = color;
	Result[int2(xPos + 2, yPos - 35)] = color;
	Result[int2(xPos + 5, yPos - 35)] = color;
	Result[int2(xPos + 6, yPos - 35)] = color;
	Result[int2(xPos + 1, yPos - 36)] = color;
	Result[int2(xPos + 6, yPos - 36)] = color;
	Result[int2(xPos + 2, yPos - 37)] = color;
	Result[int2(xPos + 5, yPos - 37)] = color;
	Result[int2(xPos, yPos - 38)] = color;
	Result[int2(xPos + 2, yPos - 38)] = color;
	Result[int2(xPos + 5, yPos - 38)] = color;
	Result[int2(xPos + 7, yPos - 38)] = color;
	Result[int2(xPos, yPos - 39)] = color;
	Result[int2(xPos + 1, yPos - 39)] = color;
	Result[int2(xPos + 6, yPos - 39)] = color;
	Result[int2(xPos + 7, yPos - 39)] = color;
}