#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 25)] = color;
	Result[int2(xPos + 12, yPos - 25)] = color;
	Result[int2(xPos + 24, yPos - 25)] = color;
	Result[int2(xPos + 6, yPos - 26)] = color;
	Result[int2(xPos + 7, yPos - 26)] = color;
	Result[int2(xPos + 11, yPos - 26)] = color;
	Result[int2(xPos + 12, yPos - 26)] = color;
	Result[int2(xPos + 22, yPos - 26)] = color;
	Result[int2(xPos + 23, yPos - 26)] = color;
	Result[int2(xPos + 24, yPos - 26)] = color;
	Result[int2(xPos + 6, yPos - 27)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 28)] = color;
	Result[int2(xPos + 5, yPos - 30)] = color;
	Result[int2(xPos + 6, yPos - 30)] = color;
	Result[int2(xPos + 6, yPos - 31)] = color;
	Result[int2(xPos + 11, yPos - 31)] = color;
	Result[int2(xPos + 12, yPos - 31)] = color;
	Result[int2(xPos + 3, yPos - 32)] = color;
	Result[int2(xPos + 4, yPos - 32)] = color;
	Result[int2(xPos + 5, yPos - 32)] = color;
	Result[int2(xPos + 11, yPos - 32)] = color;
	Result[int2(xPos + 12, yPos - 32)] = color;
	Result[int2(xPos + 3, yPos - 33)] = color;
}