#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 20, yPos)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 21, yPos - 5)] = color;
	Result[int2(xPos + 22, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 10)] = color;
	Result[int2(xPos + 24, yPos - 11)] = color;
	Result[int2(xPos + 25, yPos - 11)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 26, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 17)] = color;
	Result[int2(xPos + 23, yPos - 17)] = color;
	Result[int2(xPos + 24, yPos - 17)] = color;
	Result[int2(xPos + 23, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 18)] = color;
	Result[int2(xPos + 11, yPos - 29)] = color;
	Result[int2(xPos + 12, yPos - 29)] = color;
	Result[int2(xPos + 24, yPos - 29)] = color;
	Result[int2(xPos + 6, yPos - 30)] = color;
	Result[int2(xPos + 7, yPos - 30)] = color;
	Result[int2(xPos + 11, yPos - 30)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 22, yPos - 30)] = color;
	Result[int2(xPos + 23, yPos - 30)] = color;
	Result[int2(xPos + 24, yPos - 30)] = color;
	Result[int2(xPos + 6, yPos - 31)] = color;
	Result[int2(xPos + 7, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 32)] = color;
	Result[int2(xPos + 5, yPos - 34)] = color;
	Result[int2(xPos + 6, yPos - 34)] = color;
	Result[int2(xPos + 6, yPos - 35)] = color;
	Result[int2(xPos + 11, yPos - 35)] = color;
	Result[int2(xPos + 12, yPos - 35)] = color;
	Result[int2(xPos + 3, yPos - 36)] = color;
	Result[int2(xPos + 4, yPos - 36)] = color;
	Result[int2(xPos + 5, yPos - 36)] = color;
	Result[int2(xPos + 11, yPos - 36)] = color;
	Result[int2(xPos + 12, yPos - 36)] = color;
	Result[int2(xPos + 3, yPos - 37)] = color;
}