#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 52, yPos)] = color;
	Result[int2(xPos + 50, yPos - 1)] = color;
	Result[int2(xPos + 51, yPos - 1)] = color;
	Result[int2(xPos + 52, yPos - 1)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 3)] = color;
	Result[int2(xPos + 50, yPos - 3)] = color;
	Result[int2(xPos + 37, yPos - 4)] = color;
	Result[int2(xPos + 37, yPos - 5)] = color;
	Result[int2(xPos + 38, yPos - 5)] = color;
	Result[int2(xPos + 39, yPos - 5)] = color;
	Result[int2(xPos + 40, yPos - 6)] = color;
	Result[int2(xPos + 39, yPos - 7)] = color;
	Result[int2(xPos + 40, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 8)] = color;
	Result[int2(xPos + 7, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 53, yPos - 10)] = color;
	Result[int2(xPos + 54, yPos - 10)] = color;
	Result[int2(xPos + 53, yPos - 11)] = color;
	Result[int2(xPos + 54, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 12)] = color;
	Result[int2(xPos + 7, yPos - 12)] = color;
	Result[int2(xPos + 8, yPos - 12)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 10, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 22, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 11, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 5, yPos - 18)] = color;
	Result[int2(xPos + 8, yPos - 18)] = color;
	Result[int2(xPos + 11, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 58, yPos - 20)] = color;
	Result[int2(xPos + 59, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 21)] = color;
	Result[int2(xPos + 58, yPos - 21)] = color;
	Result[int2(xPos + 59, yPos - 21)] = color;
	Result[int2(xPos + 26, yPos - 22)] = color;
	Result[int2(xPos + 27, yPos - 22)] = color;
	Result[int2(xPos + 28, yPos - 22)] = color;
	Result[int2(xPos + 30, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 26, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 24)] = color;
	Result[int2(xPos + 9, yPos - 25)] = color;
	Result[int2(xPos + 9, yPos - 26)] = color;
	Result[int2(xPos + 11, yPos - 26)] = color;
	Result[int2(xPos + 9, yPos - 27)] = color;
	Result[int2(xPos + 10, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 55, yPos - 27)] = color;
	Result[int2(xPos + 56, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 28)] = color;
	Result[int2(xPos + 55, yPos - 28)] = color;
	Result[int2(xPos + 56, yPos - 29)] = color;
	Result[int2(xPos + 55, yPos - 30)] = color;
	Result[int2(xPos + 56, yPos - 30)] = color;
	Result[int2(xPos + 21, yPos - 33)] = color;
	Result[int2(xPos + 22, yPos - 33)] = color;
	Result[int2(xPos + 21, yPos - 34)] = color;
	Result[int2(xPos + 22, yPos - 34)] = color;
}