#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 57)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 49)) * yMult)] = color;
}