#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 14, yPos - 4)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 5)] = color;
	Result[int2(xPos + 28, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 6)] = color;
	Result[int2(xPos + 27, yPos - 6)] = color;
	Result[int2(xPos + 28, yPos - 6)] = color;
	Result[int2(xPos + 11, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 21, yPos - 11)] = color;
	Result[int2(xPos + 22, yPos - 11)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 21, yPos - 12)] = color;
	Result[int2(xPos + 24, yPos - 12)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 22, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 14)] = color;
	Result[int2(xPos + 24, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 17, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 14, yPos - 22)] = color;
	Result[int2(xPos + 17, yPos - 22)] = color;
	Result[int2(xPos, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 14, yPos - 23)] = color;
	Result[int2(xPos + 17, yPos - 23)] = color;
	Result[int2(xPos + 14, yPos - 24)] = color;
	Result[int2(xPos + 15, yPos - 24)] = color;
	Result[int2(xPos + 16, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
	Result[int2(xPos + 23, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 28)] = color;
	Result[int2(xPos + 23, yPos - 28)] = color;
}