#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 69)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 68)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 69)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 70)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 64)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 70)) * yMult)] = color;
}