#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (2 * xMult), yPos)] = color;
	Result[int2(xPos + (1 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (44 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (45 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (46 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (47 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (48 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (49 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (62 * xMult), yPos - (49 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (50 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (48 * xMult), yPos - (51 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (52 * yMult))] = color;
	Result[int2(xPos + (47 * xMult), yPos - (52 * yMult))] = color;
}