#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 3)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 26, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 5)] = color;
	Result[int2(xPos + 21, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 10)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 33, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 16, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
}