#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 16, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 6, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 30, yPos - 12)] = color;
	Result[int2(xPos + 39, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 13)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos + 29, yPos - 13)] = color;
	Result[int2(xPos + 39, yPos - 13)] = color;
	Result[int2(xPos + 40, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 28, yPos - 14)] = color;
	Result[int2(xPos + 29, yPos - 14)] = color;
	Result[int2(xPos + 30, yPos - 14)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 45, yPos - 23)] = color;
	Result[int2(xPos + 46, yPos - 23)] = color;
	Result[int2(xPos + 44, yPos - 24)] = color;
	Result[int2(xPos + 45, yPos - 24)] = color;
	Result[int2(xPos + 46, yPos - 25)] = color;
}