#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 16, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 25, yPos - 11)] = color;
	Result[int2(xPos + 21, yPos - 12)] = color;
	Result[int2(xPos + 25, yPos - 12)] = color;
	Result[int2(xPos + 13, yPos - 13)] = color;
	Result[int2(xPos + 21, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 13, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 20, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 35, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 11, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 23, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 15, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
}