#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 23, yPos)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 21, yPos - 12)] = color;
	Result[int2(xPos + 25, yPos - 12)] = color;
	Result[int2(xPos + 26, yPos - 12)] = color;
	Result[int2(xPos + 7, yPos - 13)] = color;
	Result[int2(xPos + 9, yPos - 13)] = color;
	Result[int2(xPos + 22, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 21, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 8, yPos - 16)] = color;
	Result[int2(xPos + 23, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 18)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 20)] = color;
	Result[int2(xPos + 22, yPos - 20)] = color;
	Result[int2(xPos + 29, yPos - 20)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 29, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 21)] = color;
	Result[int2(xPos + 15, yPos - 22)] = color;
	Result[int2(xPos + 30, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 37, yPos - 22)] = color;
	Result[int2(xPos + 38, yPos - 22)] = color;
	Result[int2(xPos + 14, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 23)] = color;
	Result[int2(xPos + 30, yPos - 23)] = color;
	Result[int2(xPos + 33, yPos - 23)] = color;
	Result[int2(xPos + 37, yPos - 23)] = color;
	Result[int2(xPos + 38, yPos - 23)] = color;
	Result[int2(xPos + 13, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 24)] = color;
	Result[int2(xPos + 30, yPos - 24)] = color;
	Result[int2(xPos + 32, yPos - 24)] = color;
	Result[int2(xPos + 14, yPos - 25)] = color;
	Result[int2(xPos + 15, yPos - 25)] = color;
	Result[int2(xPos + 16, yPos - 25)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 31, yPos - 25)] = color;
	Result[int2(xPos + 12, yPos - 26)] = color;
	Result[int2(xPos + 13, yPos - 26)] = color;
	Result[int2(xPos + 17, yPos - 26)] = color;
	Result[int2(xPos + 18, yPos - 26)] = color;
	Result[int2(xPos + 29, yPos - 26)] = color;
	Result[int2(xPos + 15, yPos - 37)] = color;
	Result[int2(xPos + 16, yPos - 37)] = color;
	Result[int2(xPos + 15, yPos - 38)] = color;
	Result[int2(xPos + 16, yPos - 38)] = color;
}