#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 21, yPos)] = color;
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 7, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 4, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 18, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 48, yPos - 19)] = color;
	Result[int2(xPos + 49, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 20)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 48, yPos - 20)] = color;
	Result[int2(xPos + 49, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 21)] = color;
	Result[int2(xPos + 6, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 12, yPos - 21)] = color;
	Result[int2(xPos + 4, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 10, yPos - 22)] = color;
	Result[int2(xPos + 11, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 23)] = color;
	Result[int2(xPos + 37, yPos - 23)] = color;
	Result[int2(xPos + 36, yPos - 24)] = color;
	Result[int2(xPos + 38, yPos - 24)] = color;
	Result[int2(xPos + 36, yPos - 25)] = color;
	Result[int2(xPos + 37, yPos - 25)] = color;
	Result[int2(xPos + 45, yPos - 26)] = color;
	Result[int2(xPos + 46, yPos - 26)] = color;
	Result[int2(xPos + 45, yPos - 27)] = color;
	Result[int2(xPos + 46, yPos - 28)] = color;
	Result[int2(xPos + 45, yPos - 29)] = color;
	Result[int2(xPos + 46, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 30)] = color;
	Result[int2(xPos + 10, yPos - 30)] = color;
	Result[int2(xPos + 11, yPos - 30)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 2, yPos - 31)] = color;
	Result[int2(xPos + 10, yPos - 31)] = color;
	Result[int2(xPos + 11, yPos - 31)] = color;
	Result[int2(xPos, yPos - 32)] = color;
	Result[int2(xPos + 2, yPos - 32)] = color;
}