#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (6 * xMult), yPos)] = color;
	Result[int2(xPos + (7 * xMult), yPos)] = color;
	Result[int2(xPos + (5 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos, yPos - (9 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos, yPos - (10 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (17 * yMult))] = color;
}