#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 38, yPos)] = color;
	Result[int2(xPos + 38, yPos - 1)] = color;
	Result[int2(xPos + 40, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 38, yPos - 2)] = color;
	Result[int2(xPos + 39, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 3)] = color;
	Result[int2(xPos + 35, yPos - 3)] = color;
	Result[int2(xPos + 33, yPos - 4)] = color;
	Result[int2(xPos + 34, yPos - 4)] = color;
	Result[int2(xPos + 63, yPos - 8)] = color;
	Result[int2(xPos + 64, yPos - 8)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 64, yPos - 9)] = color;
	Result[int2(xPos + 6, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 61, yPos - 10)] = color;
	Result[int2(xPos + 63, yPos - 10)] = color;
	Result[int2(xPos + 7, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 59, yPos - 12)] = color;
	Result[int2(xPos + 61, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 13)] = color;
	Result[int2(xPos + 33, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 17, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 57, yPos - 14)] = color;
	Result[int2(xPos + 59, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 56, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 56, yPos - 16)] = color;
	Result[int2(xPos + 57, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 20)] = color;
	Result[int2(xPos + 7, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
	Result[int2(xPos, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
}