#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 30, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 29, yPos - 2)] = color;
	Result[int2(xPos + 30, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 40, yPos - 6)] = color;
	Result[int2(xPos + 41, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 42, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 8)] = color;
	Result[int2(xPos + 12, yPos - 8)] = color;
	Result[int2(xPos + 40, yPos - 8)] = color;
	Result[int2(xPos + 41, yPos - 8)] = color;
	Result[int2(xPos + 13, yPos - 9)] = color;
	Result[int2(xPos + 40, yPos - 9)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 13, yPos - 10)] = color;
	Result[int2(xPos + 36, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 15)] = color;
	Result[int2(xPos + 37, yPos - 15)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 3, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 31)] = color;
	Result[int2(xPos + 2, yPos - 32)] = color;
	Result[int2(xPos + 4, yPos - 32)] = color;
	Result[int2(xPos + 25, yPos - 32)] = color;
	Result[int2(xPos + 26, yPos - 32)] = color;
	Result[int2(xPos + 2, yPos - 33)] = color;
	Result[int2(xPos + 3, yPos - 33)] = color;
	Result[int2(xPos + 4, yPos - 33)] = color;
	Result[int2(xPos + 25, yPos - 33)] = color;
	Result[int2(xPos + 4, yPos - 34)] = color;
	Result[int2(xPos + 15, yPos - 34)] = color;
	Result[int2(xPos + 16, yPos - 34)] = color;
	Result[int2(xPos + 20, yPos - 34)] = color;
	Result[int2(xPos + 21, yPos - 34)] = color;
	Result[int2(xPos + 26, yPos - 34)] = color;
	Result[int2(xPos + 27, yPos - 34)] = color;
	Result[int2(xPos + 28, yPos - 34)] = color;
	Result[int2(xPos + 13, yPos - 35)] = color;
	Result[int2(xPos + 16, yPos - 35)] = color;
	Result[int2(xPos + 21, yPos - 35)] = color;
	Result[int2(xPos + 28, yPos - 35)] = color;
	Result[int2(xPos + 13, yPos - 36)] = color;
	Result[int2(xPos + 14, yPos - 36)] = color;
	Result[int2(xPos + 15, yPos - 36)] = color;
	Result[int2(xPos + 20, yPos - 36)] = color;
	Result[int2(xPos + 20, yPos - 37)] = color;
	Result[int2(xPos + 21, yPos - 37)] = color;
	Result[int2(xPos + 13, yPos - 38)] = color;
	Result[int2(xPos + 14, yPos - 38)] = color;
	Result[int2(xPos + 16, yPos - 38)] = color;
	Result[int2(xPos + 13, yPos - 39)] = color;
	Result[int2(xPos + 15, yPos - 39)] = color;
	Result[int2(xPos + 16, yPos - 39)] = color;
}