#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 12)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 16)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
}