#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 39)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 17)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 39)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 40)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 41)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 59)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 59)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 61)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 65)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 66)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 67)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 68)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 67)) * xMult), (yPos - 69)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 70)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 71)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 71)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 71)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 71)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 72)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 74)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 74)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 75)) * yMult)] = color;
}