#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 14, yPos)] = color;
	Result[int2(xPos + 54, yPos)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 54, yPos - 1)] = color;
	Result[int2(xPos + 55, yPos - 1)] = color;
	Result[int2(xPos + 56, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 57, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos + 62, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 41, yPos - 3)] = color;
	Result[int2(xPos + 42, yPos - 3)] = color;
	Result[int2(xPos + 43, yPos - 3)] = color;
	Result[int2(xPos + 56, yPos - 3)] = color;
	Result[int2(xPos + 57, yPos - 3)] = color;
	Result[int2(xPos + 62, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 24, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 44, yPos - 4)] = color;
	Result[int2(xPos + 62, yPos - 4)] = color;
	Result[int2(xPos + 64, yPos - 4)] = color;
	Result[int2(xPos + 65, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 22, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 5)] = color;
	Result[int2(xPos + 43, yPos - 5)] = color;
	Result[int2(xPos + 44, yPos - 5)] = color;
	Result[int2(xPos + 59, yPos - 5)] = color;
	Result[int2(xPos + 60, yPos - 5)] = color;
	Result[int2(xPos + 62, yPos - 5)] = color;
	Result[int2(xPos + 65, yPos - 5)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 58, yPos - 6)] = color;
	Result[int2(xPos + 60, yPos - 6)] = color;
	Result[int2(xPos + 62, yPos - 6)] = color;
	Result[int2(xPos + 63, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos + 58, yPos - 7)] = color;
	Result[int2(xPos + 59, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 42, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 42, yPos - 13)] = color;
	Result[int2(xPos + 44, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 14)] = color;
	Result[int2(xPos + 42, yPos - 14)] = color;
	Result[int2(xPos + 43, yPos - 14)] = color;
	Result[int2(xPos + 44, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 44, yPos - 15)] = color;
}