#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 27, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 27, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 5)] = color;
	Result[int2(xPos + 26, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 13, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 10)] = color;
	Result[int2(xPos + 25, yPos - 10)] = color;
	Result[int2(xPos + 25, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 12)] = color;
	Result[int2(xPos + 13, yPos - 12)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 23, yPos - 12)] = color;
	Result[int2(xPos + 24, yPos - 12)] = color;
	Result[int2(xPos + 25, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 35, yPos - 13)] = color;
	Result[int2(xPos + 36, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 37, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 37, yPos - 15)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 37, yPos - 16)] = color;
	Result[int2(xPos + 38, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
}