#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 21, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 24, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 30, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 26, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 4, yPos - 19)] = color;
	Result[int2(xPos + 4, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 20)] = color;
	Result[int2(xPos + 29, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 28, yPos - 22)] = color;
	Result[int2(xPos + 24, yPos - 23)] = color;
	Result[int2(xPos + 25, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 24)] = color;
	Result[int2(xPos + 25, yPos - 25)] = color;
	Result[int2(xPos + 13, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 31)] = color;
	Result[int2(xPos + 14, yPos - 31)] = color;
	Result[int2(xPos + 12, yPos - 32)] = color;
	Result[int2(xPos + 14, yPos - 32)] = color;
	Result[int2(xPos + 38, yPos - 32)] = color;
	Result[int2(xPos + 39, yPos - 32)] = color;
	Result[int2(xPos + 20, yPos - 33)] = color;
	Result[int2(xPos + 21, yPos - 33)] = color;
	Result[int2(xPos + 22, yPos - 33)] = color;
	Result[int2(xPos + 38, yPos - 33)] = color;
	Result[int2(xPos + 40, yPos - 33)] = color;
	Result[int2(xPos + 22, yPos - 34)] = color;
	Result[int2(xPos + 38, yPos - 34)] = color;
	Result[int2(xPos + 21, yPos - 35)] = color;
}