#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 18, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 18, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 20, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
}