#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 34, yPos)] = color;
	Result[int2(xPos + 35, yPos)] = color;
	Result[int2(xPos + 34, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 23, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 32, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 20)] = color;
	Result[int2(xPos + 24, yPos - 21)] = color;
	Result[int2(xPos + 26, yPos - 21)] = color;
	Result[int2(xPos + 19, yPos - 22)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
	Result[int2(xPos + 25, yPos - 22)] = color;
	Result[int2(xPos + 26, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 23)] = color;
	Result[int2(xPos + 41, yPos - 23)] = color;
	Result[int2(xPos + 42, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 24)] = color;
	Result[int2(xPos + 41, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 39, yPos - 25)] = color;
	Result[int2(xPos + 41, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
	Result[int2(xPos + 2, yPos - 26)] = color;
	Result[int2(xPos + 39, yPos - 26)] = color;
	Result[int2(xPos + 40, yPos - 26)] = color;
	Result[int2(xPos, yPos - 32)] = color;
	Result[int2(xPos + 4, yPos - 32)] = color;
	Result[int2(xPos + 5, yPos - 32)] = color;
	Result[int2(xPos, yPos - 33)] = color;
	Result[int2(xPos + 1, yPos - 33)] = color;
	Result[int2(xPos + 4, yPos - 33)] = color;
	Result[int2(xPos + 5, yPos - 33)] = color;
	Result[int2(xPos + 1, yPos - 34)] = color;
	Result[int2(xPos + 2, yPos - 34)] = color;
	Result[int2(xPos, yPos - 35)] = color;
	Result[int2(xPos + 1, yPos - 35)] = color;
	Result[int2(xPos + 35, yPos - 37)] = color;
	Result[int2(xPos + 36, yPos - 37)] = color;
	Result[int2(xPos + 35, yPos - 38)] = color;
	Result[int2(xPos + 36, yPos - 39)] = color;
	Result[int2(xPos + 37, yPos - 39)] = color;
	Result[int2(xPos + 38, yPos - 39)] = color;
	Result[int2(xPos + 38, yPos - 40)] = color;
	Result[int2(xPos + 21, yPos - 45)] = color;
	Result[int2(xPos + 22, yPos - 45)] = color;
	Result[int2(xPos + 22, yPos - 46)] = color;
	Result[int2(xPos + 21, yPos - 47)] = color;
	Result[int2(xPos + 21, yPos - 48)] = color;
	Result[int2(xPos + 22, yPos - 48)] = color;
}