#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 14, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
	Result[int2(xPos + 14, yPos - 19)] = color;
	Result[int2(xPos + 4, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 20)] = color;
	Result[int2(xPos + 4, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 22, yPos - 23)] = color;
	Result[int2(xPos + 23, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 3, yPos - 25)] = color;
	Result[int2(xPos + 20, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 20, yPos - 26)] = color;
	Result[int2(xPos + 21, yPos - 26)] = color;
	Result[int2(xPos + 2, yPos - 32)] = color;
	Result[int2(xPos + 2, yPos - 33)] = color;
	Result[int2(xPos + 4, yPos - 33)] = color;
	Result[int2(xPos + 2, yPos - 34)] = color;
	Result[int2(xPos + 3, yPos - 34)] = color;
	Result[int2(xPos + 4, yPos - 34)] = color;
	Result[int2(xPos + 4, yPos - 35)] = color;
	Result[int2(xPos + 14, yPos - 37)] = color;
	Result[int2(xPos + 15, yPos - 37)] = color;
	Result[int2(xPos + 14, yPos - 38)] = color;
	Result[int2(xPos + 15, yPos - 38)] = color;
	Result[int2(xPos + 18, yPos - 38)] = color;
	Result[int2(xPos + 19, yPos - 38)] = color;
	Result[int2(xPos + 18, yPos - 39)] = color;
	Result[int2(xPos + 20, yPos - 39)] = color;
	Result[int2(xPos + 20, yPos - 40)] = color;
	Result[int2(xPos + 20, yPos - 41)] = color;
	Result[int2(xPos + 21, yPos - 41)] = color;
}