#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 12, yPos)] = color;
	Result[int2(xPos + 13, yPos)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 11, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 4, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 22)] = color;
	Result[int2(xPos + 4, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 23)] = color;
	Result[int2(xPos + 4, yPos - 23)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 19, yPos - 26)] = color;
	Result[int2(xPos + 20, yPos - 26)] = color;
	Result[int2(xPos + 19, yPos - 27)] = color;
	Result[int2(xPos + 21, yPos - 27)] = color;
	Result[int2(xPos + 21, yPos - 28)] = color;
	Result[int2(xPos + 8, yPos - 29)] = color;
	Result[int2(xPos + 21, yPos - 29)] = color;
	Result[int2(xPos + 22, yPos - 29)] = color;
	Result[int2(xPos + 8, yPos - 30)] = color;
	Result[int2(xPos + 10, yPos - 30)] = color;
	Result[int2(xPos + 8, yPos - 31)] = color;
	Result[int2(xPos + 9, yPos - 31)] = color;
	Result[int2(xPos + 10, yPos - 31)] = color;
	Result[int2(xPos + 16, yPos - 31)] = color;
	Result[int2(xPos + 17, yPos - 31)] = color;
	Result[int2(xPos + 10, yPos - 32)] = color;
	Result[int2(xPos + 16, yPos - 32)] = color;
	Result[int2(xPos + 17, yPos - 32)] = color;
	Result[int2(xPos + 2, yPos - 38)] = color;
	Result[int2(xPos + 3, yPos - 38)] = color;
	Result[int2(xPos + 12, yPos - 38)] = color;
	Result[int2(xPos + 13, yPos - 38)] = color;
	Result[int2(xPos + 2, yPos - 39)] = color;
	Result[int2(xPos + 13, yPos - 39)] = color;
	Result[int2(xPos + 3, yPos - 40)] = color;
	Result[int2(xPos + 4, yPos - 40)] = color;
	Result[int2(xPos + 5, yPos - 40)] = color;
	Result[int2(xPos + 6, yPos - 40)] = color;
	Result[int2(xPos + 7, yPos - 40)] = color;
	Result[int2(xPos + 8, yPos - 40)] = color;
	Result[int2(xPos + 9, yPos - 40)] = color;
	Result[int2(xPos + 10, yPos - 40)] = color;
	Result[int2(xPos + 11, yPos - 40)] = color;
	Result[int2(xPos + 12, yPos - 40)] = color;
	Result[int2(xPos, yPos - 41)] = color;
	Result[int2(xPos + 1, yPos - 41)] = color;
	Result[int2(xPos + 2, yPos - 41)] = color;
	Result[int2(xPos + 5, yPos - 41)] = color;
	Result[int2(xPos + 6, yPos - 41)] = color;
	Result[int2(xPos + 7, yPos - 41)] = color;
	Result[int2(xPos + 8, yPos - 41)] = color;
	Result[int2(xPos + 9, yPos - 41)] = color;
	Result[int2(xPos + 10, yPos - 41)] = color;
	Result[int2(xPos + 13, yPos - 41)] = color;
	Result[int2(xPos + 14, yPos - 41)] = color;
	Result[int2(xPos + 15, yPos - 41)] = color;
	Result[int2(xPos, yPos - 42)] = color;
	Result[int2(xPos + 3, yPos - 42)] = color;
	Result[int2(xPos + 6, yPos - 42)] = color;
	Result[int2(xPos + 7, yPos - 42)] = color;
	Result[int2(xPos + 8, yPos - 42)] = color;
	Result[int2(xPos + 9, yPos - 42)] = color;
	Result[int2(xPos + 12, yPos - 42)] = color;
	Result[int2(xPos + 15, yPos - 42)] = color;
	Result[int2(xPos + 1, yPos - 43)] = color;
	Result[int2(xPos + 2, yPos - 43)] = color;
	Result[int2(xPos + 13, yPos - 43)] = color;
	Result[int2(xPos + 14, yPos - 43)] = color;
}