#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 44, yPos)] = color;
	Result[int2(xPos + 42, yPos - 1)] = color;
	Result[int2(xPos + 44, yPos - 1)] = color;
	Result[int2(xPos + 43, yPos - 2)] = color;
	Result[int2(xPos + 44, yPos - 2)] = color;
	Result[int2(xPos + 46, yPos - 3)] = color;
	Result[int2(xPos + 46, yPos - 4)] = color;
	Result[int2(xPos + 48, yPos - 4)] = color;
	Result[int2(xPos + 65, yPos - 4)] = color;
	Result[int2(xPos + 66, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 46, yPos - 5)] = color;
	Result[int2(xPos + 47, yPos - 5)] = color;
	Result[int2(xPos + 53, yPos - 5)] = color;
	Result[int2(xPos + 64, yPos - 5)] = color;
	Result[int2(xPos + 67, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 41, yPos - 6)] = color;
	Result[int2(xPos + 52, yPos - 6)] = color;
	Result[int2(xPos + 64, yPos - 6)] = color;
	Result[int2(xPos + 67, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 42, yPos - 7)] = color;
	Result[int2(xPos + 52, yPos - 7)] = color;
	Result[int2(xPos + 53, yPos - 7)] = color;
	Result[int2(xPos + 54, yPos - 7)] = color;
	Result[int2(xPos + 62, yPos - 7)] = color;
	Result[int2(xPos + 63, yPos - 7)] = color;
	Result[int2(xPos + 68, yPos - 7)] = color;
	Result[int2(xPos + 69, yPos - 7)] = color;
	Result[int2(xPos + 4, yPos - 8)] = color;
	Result[int2(xPos + 5, yPos - 8)] = color;
	Result[int2(xPos + 25, yPos - 8)] = color;
	Result[int2(xPos + 26, yPos - 8)] = color;
	Result[int2(xPos + 40, yPos - 8)] = color;
	Result[int2(xPos + 41, yPos - 8)] = color;
	Result[int2(xPos + 42, yPos - 8)] = color;
	Result[int2(xPos + 45, yPos - 8)] = color;
	Result[int2(xPos + 46, yPos - 8)] = color;
	Result[int2(xPos + 61, yPos - 8)] = color;
	Result[int2(xPos + 70, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 25, yPos - 9)] = color;
	Result[int2(xPos + 26, yPos - 9)] = color;
	Result[int2(xPos + 45, yPos - 9)] = color;
	Result[int2(xPos + 46, yPos - 9)] = color;
	Result[int2(xPos + 49, yPos - 9)] = color;
	Result[int2(xPos + 50, yPos - 9)] = color;
	Result[int2(xPos + 51, yPos - 9)] = color;
	Result[int2(xPos + 61, yPos - 9)] = color;
	Result[int2(xPos + 70, yPos - 9)] = color;
	Result[int2(xPos + 5, yPos - 10)] = color;
	Result[int2(xPos + 37, yPos - 10)] = color;
	Result[int2(xPos + 38, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 10)] = color;
	Result[int2(xPos + 49, yPos - 10)] = color;
	Result[int2(xPos + 62, yPos - 10)] = color;
	Result[int2(xPos + 63, yPos - 10)] = color;
	Result[int2(xPos + 68, yPos - 10)] = color;
	Result[int2(xPos + 69, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 11)] = color;
	Result[int2(xPos + 50, yPos - 11)] = color;
	Result[int2(xPos + 64, yPos - 11)] = color;
	Result[int2(xPos + 67, yPos - 11)] = color;
	Result[int2(xPos + 38, yPos - 12)] = color;
	Result[int2(xPos + 44, yPos - 12)] = color;
	Result[int2(xPos + 45, yPos - 12)] = color;
	Result[int2(xPos + 64, yPos - 12)] = color;
	Result[int2(xPos + 67, yPos - 12)] = color;
	Result[int2(xPos + 43, yPos - 13)] = color;
	Result[int2(xPos + 45, yPos - 13)] = color;
	Result[int2(xPos + 65, yPos - 13)] = color;
	Result[int2(xPos + 66, yPos - 13)] = color;
	Result[int2(xPos + 45, yPos - 14)] = color;
	Result[int2(xPos + 47, yPos - 15)] = color;
	Result[int2(xPos + 48, yPos - 15)] = color;
	Result[int2(xPos + 47, yPos - 16)] = color;
	Result[int2(xPos + 49, yPos - 16)] = color;
	Result[int2(xPos + 47, yPos - 17)] = color;
}