#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 33, yPos)] = color;
	Result[int2(xPos + 31, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 6, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 24, yPos - 12)] = color;
	Result[int2(xPos + 26, yPos - 12)] = color;
	Result[int2(xPos + 25, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 13)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 27, yPos - 16)] = color;
	Result[int2(xPos + 29, yPos - 16)] = color;
	Result[int2(xPos + 27, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 19)] = color;
	Result[int2(xPos + 32, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 31, yPos - 20)] = color;
	Result[int2(xPos + 32, yPos - 21)] = color;
	Result[int2(xPos + 5, yPos - 28)] = color;
	Result[int2(xPos + 6, yPos - 28)] = color;
	Result[int2(xPos + 6, yPos - 29)] = color;
	Result[int2(xPos + 7, yPos - 29)] = color;
	Result[int2(xPos + 5, yPos - 30)] = color;
}