#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 4)] = color;
	Result[int2(xPos + 16, yPos - 4)] = color;
	Result[int2(xPos + 17, yPos - 4)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 16, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 28, yPos - 15)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 16)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 17)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
	Result[int2(xPos + 18, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 20)] = color;
	Result[int2(xPos + 33, yPos - 20)] = color;
	Result[int2(xPos + 25, yPos - 21)] = color;
	Result[int2(xPos + 32, yPos - 21)] = color;
	Result[int2(xPos + 26, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 28, yPos - 23)] = color;
	Result[int2(xPos + 29, yPos - 23)] = color;
	Result[int2(xPos + 18, yPos - 24)] = color;
	Result[int2(xPos + 19, yPos - 24)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 25)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 16, yPos - 26)] = color;
	Result[int2(xPos + 22, yPos - 26)] = color;
	Result[int2(xPos + 15, yPos - 28)] = color;
	Result[int2(xPos + 23, yPos - 28)] = color;
	Result[int2(xPos + 15, yPos - 29)] = color;
	Result[int2(xPos + 23, yPos - 29)] = color;
	Result[int2(xPos + 16, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 31)] = color;
	Result[int2(xPos + 17, yPos - 32)] = color;
	Result[int2(xPos + 21, yPos - 32)] = color;
	Result[int2(xPos + 18, yPos - 33)] = color;
	Result[int2(xPos + 19, yPos - 33)] = color;
	Result[int2(xPos + 20, yPos - 33)] = color;
}