#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 41, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 39, yPos - 1)] = color;
	Result[int2(xPos + 41, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 49, yPos - 3)] = color;
	Result[int2(xPos + 63, yPos - 3)] = color;
	Result[int2(xPos + 64, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 48, yPos - 4)] = color;
	Result[int2(xPos + 63, yPos - 4)] = color;
	Result[int2(xPos + 65, yPos - 4)] = color;
	Result[int2(xPos + 67, yPos - 4)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 12, yPos - 5)] = color;
	Result[int2(xPos + 26, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 5)] = color;
	Result[int2(xPos + 48, yPos - 5)] = color;
	Result[int2(xPos + 49, yPos - 5)] = color;
	Result[int2(xPos + 50, yPos - 5)] = color;
	Result[int2(xPos + 66, yPos - 5)] = color;
	Result[int2(xPos + 67, yPos - 5)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 52, yPos - 6)] = color;
	Result[int2(xPos + 53, yPos - 6)] = color;
	Result[int2(xPos + 54, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 52, yPos - 7)] = color;
	Result[int2(xPos + 66, yPos - 7)] = color;
	Result[int2(xPos + 67, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 41, yPos - 8)] = color;
	Result[int2(xPos + 42, yPos - 8)] = color;
	Result[int2(xPos + 53, yPos - 8)] = color;
	Result[int2(xPos + 66, yPos - 8)] = color;
	Result[int2(xPos + 67, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 40, yPos - 9)] = color;
	Result[int2(xPos + 42, yPos - 9)] = color;
	Result[int2(xPos + 42, yPos - 10)] = color;
}