#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 37, yPos - 3)] = color;
	Result[int2(xPos + 38, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 4)] = color;
	Result[int2(xPos + 38, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 5)] = color;
	Result[int2(xPos + 37, yPos - 5)] = color;
	Result[int2(xPos + 34, yPos - 6)] = color;
	Result[int2(xPos + 35, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 33, yPos - 7)] = color;
	Result[int2(xPos + 35, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 8)] = color;
	Result[int2(xPos + 34, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
}