#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 7, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 45, yPos - 2)] = color;
	Result[int2(xPos + 46, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 27, yPos - 3)] = color;
	Result[int2(xPos + 42, yPos - 3)] = color;
	Result[int2(xPos + 43, yPos - 3)] = color;
	Result[int2(xPos + 44, yPos - 3)] = color;
	Result[int2(xPos + 46, yPos - 3)] = color;
	Result[int2(xPos + 47, yPos - 3)] = color;
	Result[int2(xPos + 66, yPos - 3)] = color;
	Result[int2(xPos + 67, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 26, yPos - 4)] = color;
	Result[int2(xPos + 28, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 43, yPos - 4)] = color;
	Result[int2(xPos + 44, yPos - 4)] = color;
	Result[int2(xPos + 45, yPos - 4)] = color;
	Result[int2(xPos + 46, yPos - 4)] = color;
	Result[int2(xPos + 66, yPos - 4)] = color;
	Result[int2(xPos + 68, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 5)] = color;
	Result[int2(xPos + 29, yPos - 5)] = color;
	Result[int2(xPos + 43, yPos - 5)] = color;
	Result[int2(xPos + 44, yPos - 5)] = color;
	Result[int2(xPos + 45, yPos - 5)] = color;
	Result[int2(xPos + 67, yPos - 5)] = color;
	Result[int2(xPos + 69, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 28, yPos - 6)] = color;
	Result[int2(xPos + 30, yPos - 6)] = color;
	Result[int2(xPos + 68, yPos - 6)] = color;
	Result[int2(xPos + 70, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 29, yPos - 7)] = color;
	Result[int2(xPos + 46, yPos - 7)] = color;
	Result[int2(xPos + 69, yPos - 7)] = color;
	Result[int2(xPos + 45, yPos - 8)] = color;
	Result[int2(xPos + 46, yPos - 8)] = color;
	Result[int2(xPos + 47, yPos - 8)] = color;
	Result[int2(xPos + 45, yPos - 9)] = color;
	Result[int2(xPos + 47, yPos - 9)] = color;
	Result[int2(xPos + 48, yPos - 9)] = color;
	Result[int2(xPos + 46, yPos - 10)] = color;
	Result[int2(xPos + 47, yPos - 10)] = color;
	Result[int2(xPos + 48, yPos - 10)] = color;
	Result[int2(xPos + 46, yPos - 11)] = color;
	Result[int2(xPos + 47, yPos - 11)] = color;
	Result[int2(xPos + 48, yPos - 11)] = color;
	Result[int2(xPos + 46, yPos - 12)] = color;
	Result[int2(xPos + 47, yPos - 12)] = color;
}