#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (3 * xMult), yPos)] = color;
	Result[int2(xPos + (20 * xMult), yPos)] = color;
	Result[int2(xPos + (23 * xMult), yPos)] = color;
	Result[int2(xPos + (31 * xMult), yPos)] = color;
	Result[int2(xPos + (34 * xMult), yPos)] = color;
	Result[int2(xPos + (51 * xMult), yPos)] = color;
	Result[int2(xPos + (54 * xMult), yPos)] = color;
	Result[int2(xPos + (4 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos, yPos - (2 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (32 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (50 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (3 * yMult))] = color;
}