#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 21, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 21, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 10, yPos - 20)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 12, yPos - 21)] = color;
	Result[int2(xPos + 27, yPos - 21)] = color;
	Result[int2(xPos + 29, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 11, yPos - 22)] = color;
	Result[int2(xPos + 12, yPos - 22)] = color;
	Result[int2(xPos + 27, yPos - 22)] = color;
	Result[int2(xPos + 28, yPos - 22)] = color;
	Result[int2(xPos + 30, yPos - 22)] = color;
	Result[int2(xPos + 3, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 24, yPos - 27)] = color;
	Result[int2(xPos + 25, yPos - 27)] = color;
	Result[int2(xPos + 24, yPos - 28)] = color;
	Result[int2(xPos + 25, yPos - 28)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 1, yPos - 32)] = color;
	Result[int2(xPos + 3, yPos - 32)] = color;
	Result[int2(xPos + 24, yPos - 32)] = color;
	Result[int2(xPos + 25, yPos - 32)] = color;
	Result[int2(xPos + 27, yPos - 32)] = color;
	Result[int2(xPos + 1, yPos - 33)] = color;
	Result[int2(xPos + 2, yPos - 33)] = color;
	Result[int2(xPos + 3, yPos - 33)] = color;
	Result[int2(xPos + 24, yPos - 33)] = color;
	Result[int2(xPos + 25, yPos - 33)] = color;
	Result[int2(xPos + 27, yPos - 33)] = color;
	Result[int2(xPos + 28, yPos - 33)] = color;
	Result[int2(xPos + 29, yPos - 33)] = color;
	Result[int2(xPos + 3, yPos - 34)] = color;
	Result[int2(xPos + 15, yPos - 34)] = color;
	Result[int2(xPos + 16, yPos - 34)] = color;
	Result[int2(xPos + 30, yPos - 34)] = color;
	Result[int2(xPos + 15, yPos - 35)] = color;
	Result[int2(xPos + 24, yPos - 35)] = color;
	Result[int2(xPos + 25, yPos - 35)] = color;
	Result[int2(xPos + 27, yPos - 35)] = color;
	Result[int2(xPos + 28, yPos - 35)] = color;
	Result[int2(xPos + 29, yPos - 35)] = color;
	Result[int2(xPos + 16, yPos - 36)] = color;
	Result[int2(xPos + 17, yPos - 36)] = color;
	Result[int2(xPos + 18, yPos - 36)] = color;
	Result[int2(xPos + 23, yPos - 36)] = color;
	Result[int2(xPos + 26, yPos - 36)] = color;
	Result[int2(xPos + 27, yPos - 36)] = color;
	Result[int2(xPos + 18, yPos - 37)] = color;
	Result[int2(xPos + 23, yPos - 37)] = color;
	Result[int2(xPos + 24, yPos - 37)] = color;
}