#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 21, yPos)] = color;
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 18)] = color;
	Result[int2(xPos + 23, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 32, yPos - 21)] = color;
	Result[int2(xPos + 33, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 33, yPos - 22)] = color;
	Result[int2(xPos + 14, yPos - 25)] = color;
	Result[int2(xPos + 16, yPos - 25)] = color;
	Result[int2(xPos + 17, yPos - 25)] = color;
	Result[int2(xPos + 14, yPos - 26)] = color;
	Result[int2(xPos + 15, yPos - 26)] = color;
	Result[int2(xPos + 17, yPos - 26)] = color;
	Result[int2(xPos + 32, yPos - 37)] = color;
	Result[int2(xPos + 33, yPos - 37)] = color;
	Result[int2(xPos + 32, yPos - 38)] = color;
	Result[int2(xPos + 34, yPos - 38)] = color;
	Result[int2(xPos + 1, yPos - 39)] = color;
	Result[int2(xPos + 2, yPos - 39)] = color;
	Result[int2(xPos + 34, yPos - 39)] = color;
	Result[int2(xPos, yPos - 40)] = color;
	Result[int2(xPos + 1, yPos - 40)] = color;
	Result[int2(xPos + 2, yPos - 40)] = color;
	Result[int2(xPos + 4, yPos - 40)] = color;
	Result[int2(xPos + 5, yPos - 40)] = color;
	Result[int2(xPos + 34, yPos - 40)] = color;
	Result[int2(xPos + 35, yPos - 40)] = color;
	Result[int2(xPos + 1, yPos - 41)] = color;
	Result[int2(xPos + 2, yPos - 41)] = color;
	Result[int2(xPos + 4, yPos - 41)] = color;
	Result[int2(xPos + 5, yPos - 41)] = color;
	Result[int2(xPos + 6, yPos - 41)] = color;
	Result[int2(xPos + 8, yPos - 41)] = color;
	Result[int2(xPos + 9, yPos - 41)] = color;
	Result[int2(xPos, yPos - 42)] = color;
	Result[int2(xPos + 1, yPos - 42)] = color;
	Result[int2(xPos + 2, yPos - 42)] = color;
	Result[int2(xPos + 4, yPos - 42)] = color;
	Result[int2(xPos + 5, yPos - 42)] = color;
	Result[int2(xPos + 8, yPos - 42)] = color;
	Result[int2(xPos + 9, yPos - 42)] = color;
	Result[int2(xPos, yPos - 43)] = color;
	Result[int2(xPos + 1, yPos - 43)] = color;
	Result[int2(xPos + 32, yPos - 47)] = color;
	Result[int2(xPos + 33, yPos - 47)] = color;
	Result[int2(xPos + 32, yPos - 48)] = color;
	Result[int2(xPos + 33, yPos - 48)] = color;
	Result[int2(xPos + 6, yPos - 50)] = color;
	Result[int2(xPos + 7, yPos - 50)] = color;
	Result[int2(xPos + 7, yPos - 51)] = color;
	Result[int2(xPos + 4, yPos - 52)] = color;
	Result[int2(xPos + 5, yPos - 52)] = color;
	Result[int2(xPos + 6, yPos - 52)] = color;
	Result[int2(xPos + 32, yPos - 52)] = color;
	Result[int2(xPos + 33, yPos - 52)] = color;
	Result[int2(xPos + 4, yPos - 53)] = color;
	Result[int2(xPos + 32, yPos - 53)] = color;
	Result[int2(xPos + 33, yPos - 53)] = color;
	Result[int2(xPos + 18, yPos - 54)] = color;
	Result[int2(xPos + 19, yPos - 54)] = color;
	Result[int2(xPos + 17, yPos - 55)] = color;
	Result[int2(xPos + 19, yPos - 55)] = color;
	Result[int2(xPos + 17, yPos - 56)] = color;
	Result[int2(xPos + 16, yPos - 57)] = color;
	Result[int2(xPos + 17, yPos - 57)] = color;
	Result[int2(xPos + 26, yPos - 57)] = color;
	Result[int2(xPos + 27, yPos - 57)] = color;
	Result[int2(xPos + 26, yPos - 58)] = color;
	Result[int2(xPos + 27, yPos - 59)] = color;
	Result[int2(xPos + 28, yPos - 59)] = color;
	Result[int2(xPos + 29, yPos - 59)] = color;
	Result[int2(xPos + 29, yPos - 60)] = color;
}