#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 30, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 34, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 5, yPos - 3)] = color;
	Result[int2(xPos + 28, yPos - 3)] = color;
	Result[int2(xPos + 30, yPos - 3)] = color;
	Result[int2(xPos + 32, yPos - 3)] = color;
	Result[int2(xPos + 34, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 31, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 31, yPos - 6)] = color;
	Result[int2(xPos + 31, yPos - 7)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 28, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos + 34, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
}