#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (23 * xMult), yPos)] = color;
	Result[int2(xPos + (24 * xMult), yPos)] = color;
	Result[int2(xPos + (22 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos, yPos - (6 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (15 * yMult))] = color;
}