#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 14, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 14, yPos - 10)] = color;
	Result[int2(xPos + 15, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
}