#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 27, yPos)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 25, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 11, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 32, yPos - 6)] = color;
	Result[int2(xPos + 33, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 21, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 32, yPos - 7)] = color;
	Result[int2(xPos + 33, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 8)] = color;
	Result[int2(xPos + 19, yPos - 8)] = color;
	Result[int2(xPos + 20, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 5, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 21, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 21, yPos - 10)] = color;
	Result[int2(xPos + 24, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 23, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 25, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 39, yPos - 22)] = color;
	Result[int2(xPos + 40, yPos - 22)] = color;
	Result[int2(xPos + 39, yPos - 23)] = color;
	Result[int2(xPos + 40, yPos - 23)] = color;
	Result[int2(xPos + 18, yPos - 25)] = color;
	Result[int2(xPos + 23, yPos - 25)] = color;
	Result[int2(xPos + 24, yPos - 25)] = color;
	Result[int2(xPos + 25, yPos - 25)] = color;
	Result[int2(xPos + 20, yPos - 26)] = color;
	Result[int2(xPos + 24, yPos - 26)] = color;
	Result[int2(xPos + 26, yPos - 26)] = color;
	Result[int2(xPos + 20, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 22, yPos - 28)] = color;
	Result[int2(xPos + 22, yPos - 29)] = color;
	Result[int2(xPos + 25, yPos - 29)] = color;
	Result[int2(xPos + 26, yPos - 29)] = color;
	Result[int2(xPos + 23, yPos - 30)] = color;
	Result[int2(xPos + 24, yPos - 30)] = color;
	Result[int2(xPos + 32, yPos - 30)] = color;
	Result[int2(xPos + 10, yPos - 31)] = color;
	Result[int2(xPos + 11, yPos - 31)] = color;
	Result[int2(xPos + 21, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 31)] = color;
	Result[int2(xPos + 31, yPos - 31)] = color;
	Result[int2(xPos + 33, yPos - 31)] = color;
	Result[int2(xPos + 10, yPos - 32)] = color;
	Result[int2(xPos + 11, yPos - 32)] = color;
	Result[int2(xPos + 21, yPos - 32)] = color;
	Result[int2(xPos + 32, yPos - 32)] = color;
	Result[int2(xPos + 18, yPos - 35)] = color;
	Result[int2(xPos + 19, yPos - 35)] = color;
	Result[int2(xPos + 19, yPos - 36)] = color;
	Result[int2(xPos + 16, yPos - 37)] = color;
	Result[int2(xPos + 17, yPos - 37)] = color;
	Result[int2(xPos + 18, yPos - 37)] = color;
	Result[int2(xPos + 16, yPos - 38)] = color;
}