#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 9)] = color;
	Result[int2(xPos + 21, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 44, yPos - 17)] = color;
	Result[int2(xPos + 44, yPos - 18)] = color;
	Result[int2(xPos + 45, yPos - 18)] = color;
	Result[int2(xPos + 43, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 19)] = color;
	Result[int2(xPos + 61, yPos - 21)] = color;
	Result[int2(xPos + 62, yPos - 21)] = color;
	Result[int2(xPos + 61, yPos - 22)] = color;
	Result[int2(xPos + 63, yPos - 22)] = color;
	Result[int2(xPos + 63, yPos - 23)] = color;
	Result[int2(xPos + 30, yPos - 24)] = color;
	Result[int2(xPos + 63, yPos - 24)] = color;
	Result[int2(xPos + 64, yPos - 24)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 31, yPos - 25)] = color;
	Result[int2(xPos + 32, yPos - 25)] = color;
	Result[int2(xPos + 40, yPos - 25)] = color;
	Result[int2(xPos + 41, yPos - 25)] = color;
	Result[int2(xPos + 33, yPos - 26)] = color;
	Result[int2(xPos + 41, yPos - 26)] = color;
	Result[int2(xPos + 29, yPos - 27)] = color;
	Result[int2(xPos + 32, yPos - 27)] = color;
	Result[int2(xPos + 34, yPos - 27)] = color;
	Result[int2(xPos + 38, yPos - 27)] = color;
	Result[int2(xPos + 39, yPos - 27)] = color;
	Result[int2(xPos + 40, yPos - 27)] = color;
	Result[int2(xPos + 31, yPos - 28)] = color;
	Result[int2(xPos + 34, yPos - 28)] = color;
	Result[int2(xPos + 38, yPos - 28)] = color;
	Result[int2(xPos + 32, yPos - 29)] = color;
	Result[int2(xPos + 33, yPos - 29)] = color;
}