#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (119 * xMult), yPos)] = color;
	Result[int2(xPos + (121 * xMult), yPos)] = color;
	Result[int2(xPos + (119 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (120 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (120 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos, yPos - (11 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (22 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (23 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (89 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (110 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (104 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (116 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (118 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (116 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (117 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (117 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (106 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (133 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (134 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (133 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (137 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (138 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (134 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (136 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (138 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (97 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (107 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (134 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (135 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (138 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (136 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (139 * xMult), yPos - (29 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (138 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (139 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (24 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (110 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (108 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (109 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (85 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (38 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (39 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (40 * yMult))] = color;
	Result[int2(xPos + (88 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (104 * xMult), yPos - (41 * yMult))] = color;
	Result[int2(xPos + (88 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (89 * xMult), yPos - (42 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (43 * yMult))] = color;
	Result[int2(xPos + (89 * xMult), yPos - (43 * yMult))] = color;
}