#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 33, yPos - 7)] = color;
	Result[int2(xPos + 34, yPos - 7)] = color;
	Result[int2(xPos + 32, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos + 34, yPos - 8)] = color;
	Result[int2(xPos + 35, yPos - 8)] = color;
	Result[int2(xPos + 36, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 37, yPos - 9)] = color;
	Result[int2(xPos + 43, yPos - 9)] = color;
	Result[int2(xPos + 44, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos + 37, yPos - 10)] = color;
	Result[int2(xPos + 43, yPos - 10)] = color;
	Result[int2(xPos + 44, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 11)] = color;
	Result[int2(xPos + 36, yPos - 11)] = color;
	Result[int2(xPos + 37, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 34, yPos - 12)] = color;
	Result[int2(xPos + 35, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 36, yPos - 15)] = color;
	Result[int2(xPos + 37, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 37, yPos - 16)] = color;
	Result[int2(xPos + 43, yPos - 16)] = color;
	Result[int2(xPos + 44, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 37, yPos - 17)] = color;
	Result[int2(xPos + 43, yPos - 17)] = color;
	Result[int2(xPos + 44, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 18)] = color;
	Result[int2(xPos + 36, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 21)] = color;
	Result[int2(xPos + 11, yPos - 21)] = color;
	Result[int2(xPos + 12, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 17, yPos - 21)] = color;
	Result[int2(xPos + 18, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 12, yPos - 22)] = color;
	Result[int2(xPos + 16, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 22)] = color;
	Result[int2(xPos + 9, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 12, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 23)] = color;
	Result[int2(xPos + 18, yPos - 23)] = color;
	Result[int2(xPos + 19, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 39)] = color;
	Result[int2(xPos + 11, yPos - 39)] = color;
	Result[int2(xPos + 17, yPos - 39)] = color;
	Result[int2(xPos + 18, yPos - 39)] = color;
	Result[int2(xPos + 10, yPos - 40)] = color;
	Result[int2(xPos + 11, yPos - 40)] = color;
	Result[int2(xPos + 17, yPos - 40)] = color;
	Result[int2(xPos + 18, yPos - 40)] = color;
}