#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 25, yPos)] = color;
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 32, yPos)] = color;
	Result[int2(xPos + 33, yPos)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 13)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos + 30, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 28, yPos - 17)] = color;
	Result[int2(xPos + 30, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 18)] = color;
	Result[int2(xPos + 26, yPos - 18)] = color;
	Result[int2(xPos + 27, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 23)] = color;
	Result[int2(xPos, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 24)] = color;
	Result[int2(xPos + 18, yPos - 24)] = color;
	Result[int2(xPos, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos + 18, yPos - 25)] = color;
	Result[int2(xPos + 19, yPos - 25)] = color;
	Result[int2(xPos + 13, yPos - 26)] = color;
	Result[int2(xPos + 14, yPos - 26)] = color;
	Result[int2(xPos + 17, yPos - 26)] = color;
	Result[int2(xPos + 18, yPos - 26)] = color;
	Result[int2(xPos + 13, yPos - 30)] = color;
	Result[int2(xPos + 14, yPos - 30)] = color;
	Result[int2(xPos + 17, yPos - 30)] = color;
	Result[int2(xPos + 18, yPos - 30)] = color;
	Result[int2(xPos, yPos - 31)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 18, yPos - 31)] = color;
	Result[int2(xPos + 19, yPos - 31)] = color;
	Result[int2(xPos + 27, yPos - 31)] = color;
	Result[int2(xPos + 28, yPos - 31)] = color;
	Result[int2(xPos, yPos - 32)] = color;
	Result[int2(xPos + 1, yPos - 32)] = color;
	Result[int2(xPos + 17, yPos - 32)] = color;
	Result[int2(xPos + 18, yPos - 32)] = color;
	Result[int2(xPos + 27, yPos - 32)] = color;
	Result[int2(xPos + 28, yPos - 32)] = color;
	Result[int2(xPos + 17, yPos - 33)] = color;
}