#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 21, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 42, yPos - 12)] = color;
	Result[int2(xPos + 43, yPos - 12)] = color;
	Result[int2(xPos + 42, yPos - 13)] = color;
	Result[int2(xPos + 43, yPos - 13)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 27)] = color;
	Result[int2(xPos + 33, yPos - 27)] = color;
	Result[int2(xPos + 32, yPos - 28)] = color;
	Result[int2(xPos + 33, yPos - 28)] = color;
}