#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 52, yPos)] = color;
	Result[int2(xPos + 52, yPos - 1)] = color;
	Result[int2(xPos + 54, yPos - 1)] = color;
	Result[int2(xPos + 52, yPos - 2)] = color;
	Result[int2(xPos + 53, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 9)] = color;
	Result[int2(xPos + 16, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 43, yPos - 12)] = color;
	Result[int2(xPos + 45, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 43, yPos - 13)] = color;
	Result[int2(xPos + 44, yPos - 13)] = color;
	Result[int2(xPos + 44, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 19)] = color;
	Result[int2(xPos + 36, yPos - 19)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 36, yPos - 20)] = color;
	Result[int2(xPos + 37, yPos - 20)] = color;
	Result[int2(xPos + 35, yPos - 21)] = color;
	Result[int2(xPos + 37, yPos - 21)] = color;
	Result[int2(xPos + 38, yPos - 23)] = color;
	Result[int2(xPos + 39, yPos - 23)] = color;
	Result[int2(xPos + 38, yPos - 24)] = color;
	Result[int2(xPos + 40, yPos - 24)] = color;
	Result[int2(xPos + 38, yPos - 25)] = color;
	Result[int2(xPos + 46, yPos - 25)] = color;
	Result[int2(xPos + 47, yPos - 25)] = color;
	Result[int2(xPos + 46, yPos - 26)] = color;
	Result[int2(xPos + 48, yPos - 26)] = color;
	Result[int2(xPos + 34, yPos - 27)] = color;
	Result[int2(xPos + 35, yPos - 27)] = color;
	Result[int2(xPos + 46, yPos - 27)] = color;
	Result[int2(xPos + 34, yPos - 28)] = color;
	Result[int2(xPos + 36, yPos - 28)] = color;
	Result[int2(xPos + 34, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 30)] = color;
	Result[int2(xPos + 2, yPos - 30)] = color;
	Result[int2(xPos, yPos - 31)] = color;
	Result[int2(xPos + 2, yPos - 31)] = color;
	Result[int2(xPos + 2, yPos - 32)] = color;
}