#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 18)] = color;
	Result[int2(xPos + 19, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 20)] = color;
	Result[int2(xPos + 22, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 32)] = color;
	Result[int2(xPos + 7, yPos - 32)] = color;
	Result[int2(xPos + 8, yPos - 32)] = color;
	Result[int2(xPos + 8, yPos - 33)] = color;
	Result[int2(xPos + 7, yPos - 34)] = color;
	Result[int2(xPos, yPos - 38)] = color;
	Result[int2(xPos + 1, yPos - 38)] = color;
	Result[int2(xPos + 2, yPos - 38)] = color;
	Result[int2(xPos + 2, yPos - 39)] = color;
	Result[int2(xPos + 1, yPos - 40)] = color;
}