#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 1)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 14)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 15)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 16)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 20)) * yMult)] = color;
}