#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 7, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 4)] = color;
	Result[int2(xPos + 52, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 53, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 51, yPos - 6)] = color;
	Result[int2(xPos + 52, yPos - 6)] = color;
	Result[int2(xPos + 53, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 7)] = color;
	Result[int2(xPos + 24, yPos - 7)] = color;
	Result[int2(xPos + 55, yPos - 7)] = color;
	Result[int2(xPos + 56, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 54, yPos - 8)] = color;
	Result[int2(xPos + 56, yPos - 8)] = color;
	Result[int2(xPos + 10, yPos - 9)] = color;
	Result[int2(xPos + 11, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 54, yPos - 9)] = color;
	Result[int2(xPos + 55, yPos - 9)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 63, yPos - 10)] = color;
	Result[int2(xPos + 95, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 34, yPos - 11)] = color;
	Result[int2(xPos + 35, yPos - 11)] = color;
	Result[int2(xPos + 62, yPos - 11)] = color;
	Result[int2(xPos + 64, yPos - 11)] = color;
	Result[int2(xPos + 66, yPos - 11)] = color;
	Result[int2(xPos + 67, yPos - 11)] = color;
	Result[int2(xPos + 94, yPos - 11)] = color;
	Result[int2(xPos + 96, yPos - 11)] = color;
	Result[int2(xPos + 98, yPos - 11)] = color;
	Result[int2(xPos + 99, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 34, yPos - 12)] = color;
	Result[int2(xPos + 61, yPos - 12)] = color;
	Result[int2(xPos + 64, yPos - 12)] = color;
	Result[int2(xPos + 66, yPos - 12)] = color;
	Result[int2(xPos + 93, yPos - 12)] = color;
	Result[int2(xPos + 96, yPos - 12)] = color;
	Result[int2(xPos + 98, yPos - 12)] = color;
	Result[int2(xPos + 30, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 34, yPos - 13)] = color;
	Result[int2(xPos + 62, yPos - 13)] = color;
	Result[int2(xPos + 63, yPos - 13)] = color;
	Result[int2(xPos + 66, yPos - 13)] = color;
	Result[int2(xPos + 94, yPos - 13)] = color;
	Result[int2(xPos + 95, yPos - 13)] = color;
	Result[int2(xPos + 98, yPos - 13)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 66, yPos - 14)] = color;
	Result[int2(xPos + 67, yPos - 14)] = color;
	Result[int2(xPos + 98, yPos - 14)] = color;
	Result[int2(xPos + 99, yPos - 14)] = color;
}