#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 3)] = color;
	Result[int2(xPos + 32, yPos - 3)] = color;
	Result[int2(xPos + 33, yPos - 3)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 32, yPos - 4)] = color;
	Result[int2(xPos + 33, yPos - 4)] = color;
	Result[int2(xPos + 6, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 40, yPos - 11)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 25, yPos - 13)] = color;
	Result[int2(xPos + 40, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 15)] = color;
	Result[int2(xPos + 25, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 15, yPos - 20)] = color;
	Result[int2(xPos + 17, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 15, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 17, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos, yPos - 23)] = color;
	Result[int2(xPos + 33, yPos - 29)] = color;
	Result[int2(xPos + 34, yPos - 29)] = color;
	Result[int2(xPos + 7, yPos - 30)] = color;
	Result[int2(xPos + 8, yPos - 30)] = color;
	Result[int2(xPos + 33, yPos - 30)] = color;
	Result[int2(xPos + 35, yPos - 30)] = color;
	Result[int2(xPos + 7, yPos - 31)] = color;
	Result[int2(xPos + 8, yPos - 31)] = color;
	Result[int2(xPos + 35, yPos - 31)] = color;
	Result[int2(xPos + 23, yPos - 32)] = color;
	Result[int2(xPos + 35, yPos - 32)] = color;
	Result[int2(xPos + 36, yPos - 32)] = color;
	Result[int2(xPos + 22, yPos - 33)] = color;
	Result[int2(xPos + 24, yPos - 33)] = color;
	Result[int2(xPos + 22, yPos - 34)] = color;
	Result[int2(xPos + 23, yPos - 34)] = color;
}