#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 35, yPos)] = color;
	Result[int2(xPos + 34, yPos - 1)] = color;
	Result[int2(xPos + 36, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 37, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 3)] = color;
	Result[int2(xPos + 38, yPos - 3)] = color;
	Result[int2(xPos + 35, yPos - 4)] = color;
	Result[int2(xPos + 39, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 5)] = color;
	Result[int2(xPos + 40, yPos - 5)] = color;
	Result[int2(xPos + 37, yPos - 6)] = color;
	Result[int2(xPos + 39, yPos - 6)] = color;
	Result[int2(xPos + 38, yPos - 7)] = color;
	Result[int2(xPos + 58, yPos - 18)] = color;
	Result[int2(xPos + 59, yPos - 18)] = color;
	Result[int2(xPos + 58, yPos - 19)] = color;
	Result[int2(xPos + 41, yPos - 20)] = color;
	Result[int2(xPos + 56, yPos - 20)] = color;
	Result[int2(xPos + 58, yPos - 20)] = color;
	Result[int2(xPos + 39, yPos - 21)] = color;
	Result[int2(xPos + 40, yPos - 21)] = color;
	Result[int2(xPos + 42, yPos - 21)] = color;
	Result[int2(xPos + 43, yPos - 21)] = color;
	Result[int2(xPos + 56, yPos - 21)] = color;
	Result[int2(xPos + 57, yPos - 21)] = color;
	Result[int2(xPos + 39, yPos - 22)] = color;
	Result[int2(xPos + 42, yPos - 22)] = color;
	Result[int2(xPos + 52, yPos - 22)] = color;
	Result[int2(xPos + 53, yPos - 22)] = color;
	Result[int2(xPos + 40, yPos - 23)] = color;
	Result[int2(xPos + 41, yPos - 23)] = color;
	Result[int2(xPos + 52, yPos - 23)] = color;
	Result[int2(xPos + 54, yPos - 23)] = color;
	Result[int2(xPos + 47, yPos - 24)] = color;
	Result[int2(xPos + 48, yPos - 24)] = color;
	Result[int2(xPos + 53, yPos - 24)] = color;
	Result[int2(xPos + 54, yPos - 24)] = color;
	Result[int2(xPos + 47, yPos - 25)] = color;
	Result[int2(xPos + 48, yPos - 25)] = color;
	Result[int2(xPos + 11, yPos - 26)] = color;
	Result[int2(xPos + 12, yPos - 26)] = color;
	Result[int2(xPos + 5, yPos - 27)] = color;
	Result[int2(xPos + 6, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 12, yPos - 27)] = color;
	Result[int2(xPos + 5, yPos - 28)] = color;
	Result[int2(xPos + 7, yPos - 28)] = color;
	Result[int2(xPos + 18, yPos - 28)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 6, yPos - 29)] = color;
	Result[int2(xPos + 7, yPos - 29)] = color;
	Result[int2(xPos + 17, yPos - 29)] = color;
	Result[int2(xPos + 20, yPos - 29)] = color;
	Result[int2(xPos + 2, yPos - 30)] = color;
	Result[int2(xPos + 3, yPos - 30)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 17, yPos - 30)] = color;
	Result[int2(xPos + 19, yPos - 30)] = color;
	Result[int2(xPos + 20, yPos - 30)] = color;
	Result[int2(xPos + 1, yPos - 31)] = color;
	Result[int2(xPos + 3, yPos - 31)] = color;
	Result[int2(xPos + 18, yPos - 31)] = color;
	Result[int2(xPos + 1, yPos - 32)] = color;
	Result[int2(xPos, yPos - 33)] = color;
	Result[int2(xPos + 1, yPos - 33)] = color;
	Result[int2(xPos + 21, yPos - 44)] = color;
	Result[int2(xPos + 20, yPos - 45)] = color;
	Result[int2(xPos + 22, yPos - 45)] = color;
	Result[int2(xPos + 19, yPos - 46)] = color;
	Result[int2(xPos + 23, yPos - 46)] = color;
	Result[int2(xPos + 20, yPos - 47)] = color;
	Result[int2(xPos + 24, yPos - 47)] = color;
	Result[int2(xPos + 21, yPos - 48)] = color;
	Result[int2(xPos + 25, yPos - 48)] = color;
	Result[int2(xPos + 22, yPos - 49)] = color;
	Result[int2(xPos + 26, yPos - 49)] = color;
	Result[int2(xPos + 23, yPos - 50)] = color;
	Result[int2(xPos + 25, yPos - 50)] = color;
	Result[int2(xPos + 24, yPos - 51)] = color;
}