#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 56, yPos - 4)] = color;
	Result[int2(xPos + 57, yPos - 4)] = color;
	Result[int2(xPos + 56, yPos - 5)] = color;
	Result[int2(xPos + 58, yPos - 5)] = color;
	Result[int2(xPos + 57, yPos - 6)] = color;
	Result[int2(xPos + 58, yPos - 6)] = color;
	Result[int2(xPos + 38, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 10)] = color;
	Result[int2(xPos + 38, yPos - 11)] = color;
	Result[int2(xPos + 39, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 46, yPos - 14)] = color;
	Result[int2(xPos + 47, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 46, yPos - 15)] = color;
	Result[int2(xPos + 47, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 16, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 18)] = color;
	Result[int2(xPos + 23, yPos - 18)] = color;
	Result[int2(xPos + 8, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 28, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 21, yPos - 20)] = color;
	Result[int2(xPos + 23, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 20)] = color;
	Result[int2(xPos + 30, yPos - 20)] = color;
	Result[int2(xPos + 7, yPos - 21)] = color;
	Result[int2(xPos + 10, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 29, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 8, yPos - 22)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 23)] = color;
	Result[int2(xPos + 33, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 24)] = color;
	Result[int2(xPos + 33, yPos - 24)] = color;
	Result[int2(xPos + 13, yPos - 28)] = color;
	Result[int2(xPos + 14, yPos - 28)] = color;
	Result[int2(xPos + 25, yPos - 28)] = color;
	Result[int2(xPos + 26, yPos - 28)] = color;
	Result[int2(xPos + 12, yPos - 29)] = color;
	Result[int2(xPos + 14, yPos - 29)] = color;
	Result[int2(xPos + 25, yPos - 29)] = color;
	Result[int2(xPos + 26, yPos - 29)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 40)] = color;
	Result[int2(xPos + 10, yPos - 40)] = color;
	Result[int2(xPos + 11, yPos - 40)] = color;
	Result[int2(xPos + 17, yPos - 45)] = color;
	Result[int2(xPos + 18, yPos - 45)] = color;
	Result[int2(xPos + 16, yPos - 46)] = color;
	Result[int2(xPos + 19, yPos - 46)] = color;
	Result[int2(xPos + 17, yPos - 47)] = color;
	Result[int2(xPos + 18, yPos - 47)] = color;
	Result[int2(xPos + 18, yPos - 51)] = color;
	Result[int2(xPos + 19, yPos - 51)] = color;
	Result[int2(xPos + 17, yPos - 52)] = color;
	Result[int2(xPos + 20, yPos - 52)] = color;
	Result[int2(xPos + 17, yPos - 53)] = color;
	Result[int2(xPos + 20, yPos - 53)] = color;
	Result[int2(xPos + 18, yPos - 54)] = color;
	Result[int2(xPos + 19, yPos - 54)] = color;
	Result[int2(xPos + 26, yPos - 54)] = color;
	Result[int2(xPos + 27, yPos - 54)] = color;
	Result[int2(xPos + 26, yPos - 55)] = color;
	Result[int2(xPos + 27, yPos - 55)] = color;
}