#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 34, yPos - 1)] = color;
	Result[int2(xPos + 38, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 37, yPos - 2)] = color;
	Result[int2(xPos + 39, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 35, yPos - 3)] = color;
	Result[int2(xPos + 37, yPos - 3)] = color;
	Result[int2(xPos + 38, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 34, yPos - 4)] = color;
	Result[int2(xPos + 36, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 34, yPos - 5)] = color;
	Result[int2(xPos + 36, yPos - 5)] = color;
	Result[int2(xPos + 38, yPos - 5)] = color;
	Result[int2(xPos + 39, yPos - 5)] = color;
	Result[int2(xPos + 40, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 35, yPos - 6)] = color;
	Result[int2(xPos + 36, yPos - 6)] = color;
	Result[int2(xPos + 38, yPos - 6)] = color;
	Result[int2(xPos + 41, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 40, yPos - 7)] = color;
	Result[int2(xPos + 41, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 8)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 21, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 21, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
}