#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 18)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 19)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 51)) * yMult)] = color;
}