#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 25, yPos)] = color;
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 2)] = color;
	Result[int2(xPos + 20, yPos - 3)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 5)] = color;
	Result[int2(xPos + 22, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 26, yPos - 9)] = color;
	Result[int2(xPos + 30, yPos - 9)] = color;
	Result[int2(xPos + 31, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 32, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 11)] = color;
	Result[int2(xPos + 25, yPos - 11)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 33, yPos - 12)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 38, yPos - 14)] = color;
	Result[int2(xPos + 39, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 38, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 22, yPos - 16)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos + 38, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 23, yPos - 17)] = color;
	Result[int2(xPos + 36, yPos - 17)] = color;
	Result[int2(xPos + 37, yPos - 17)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 19, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 22, yPos - 18)] = color;
	Result[int2(xPos + 23, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 19)] = color;
	Result[int2(xPos + 33, yPos - 20)] = color;
	Result[int2(xPos + 34, yPos - 20)] = color;
	Result[int2(xPos + 21, yPos - 23)] = color;
	Result[int2(xPos + 22, yPos - 23)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 25)] = color;
	Result[int2(xPos + 3, yPos - 25)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 27, yPos - 25)] = color;
	Result[int2(xPos + 28, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
	Result[int2(xPos + 27, yPos - 26)] = color;
	Result[int2(xPos + 29, yPos - 26)] = color;
	Result[int2(xPos, yPos - 27)] = color;
	Result[int2(xPos + 1, yPos - 27)] = color;
	Result[int2(xPos + 29, yPos - 27)] = color;
	Result[int2(xPos + 29, yPos - 28)] = color;
	Result[int2(xPos + 30, yPos - 28)] = color;
	Result[int2(xPos + 17, yPos - 33)] = color;
	Result[int2(xPos + 18, yPos - 33)] = color;
	Result[int2(xPos + 17, yPos - 34)] = color;
	Result[int2(xPos + 18, yPos - 34)] = color;
}