#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 14, yPos)] = color;
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 21, yPos)] = color;
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 34, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 32, yPos - 4)] = color;
	Result[int2(xPos + 34, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 32, yPos - 5)] = color;
	Result[int2(xPos + 33, yPos - 5)] = color;
	Result[int2(xPos + 18, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos + 34, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 42, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 13)] = color;
	Result[int2(xPos + 42, yPos - 13)] = color;
	Result[int2(xPos + 41, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 38, yPos - 19)] = color;
	Result[int2(xPos + 39, yPos - 19)] = color;
	Result[int2(xPos + 8, yPos - 20)] = color;
	Result[int2(xPos + 10, yPos - 20)] = color;
	Result[int2(xPos + 38, yPos - 20)] = color;
	Result[int2(xPos + 40, yPos - 20)] = color;
	Result[int2(xPos + 8, yPos - 21)] = color;
	Result[int2(xPos + 40, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
	Result[int2(xPos + 8, yPos - 22)] = color;
	Result[int2(xPos + 15, yPos - 22)] = color;
	Result[int2(xPos + 16, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 33, yPos - 22)] = color;
	Result[int2(xPos + 40, yPos - 22)] = color;
	Result[int2(xPos + 41, yPos - 22)] = color;
	Result[int2(xPos + 15, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 23)] = color;
	Result[int2(xPos + 21, yPos - 23)] = color;
	Result[int2(xPos + 27, yPos - 23)] = color;
	Result[int2(xPos + 28, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 33, yPos - 23)] = color;
	Result[int2(xPos + 20, yPos - 24)] = color;
	Result[int2(xPos + 21, yPos - 24)] = color;
	Result[int2(xPos + 27, yPos - 24)] = color;
	Result[int2(xPos + 28, yPos - 24)] = color;
}