#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 21, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 4)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 46, yPos - 6)] = color;
	Result[int2(xPos + 47, yPos - 6)] = color;
	Result[int2(xPos + 46, yPos - 7)] = color;
	Result[int2(xPos + 47, yPos - 7)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 10)] = color;
	Result[int2(xPos + 5, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 44, yPos - 18)] = color;
	Result[int2(xPos + 45, yPos - 18)] = color;
	Result[int2(xPos + 46, yPos - 18)] = color;
	Result[int2(xPos + 44, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 20)] = color;
	Result[int2(xPos + 45, yPos - 21)] = color;
	Result[int2(xPos + 46, yPos - 21)] = color;
	Result[int2(xPos + 48, yPos - 21)] = color;
	Result[int2(xPos + 48, yPos - 22)] = color;
	Result[int2(xPos + 49, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 3, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 3, yPos - 25)] = color;
	Result[int2(xPos + 46, yPos - 26)] = color;
	Result[int2(xPos + 38, yPos - 27)] = color;
	Result[int2(xPos + 39, yPos - 27)] = color;
	Result[int2(xPos + 45, yPos - 27)] = color;
	Result[int2(xPos + 47, yPos - 27)] = color;
	Result[int2(xPos + 27, yPos - 28)] = color;
	Result[int2(xPos + 28, yPos - 28)] = color;
	Result[int2(xPos + 39, yPos - 28)] = color;
	Result[int2(xPos + 46, yPos - 28)] = color;
	Result[int2(xPos + 16, yPos - 29)] = color;
	Result[int2(xPos + 17, yPos - 29)] = color;
	Result[int2(xPos + 27, yPos - 29)] = color;
	Result[int2(xPos + 36, yPos - 29)] = color;
	Result[int2(xPos + 37, yPos - 29)] = color;
	Result[int2(xPos + 38, yPos - 29)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 17, yPos - 30)] = color;
	Result[int2(xPos + 28, yPos - 30)] = color;
	Result[int2(xPos + 29, yPos - 30)] = color;
	Result[int2(xPos + 30, yPos - 30)] = color;
	Result[int2(xPos + 36, yPos - 30)] = color;
	Result[int2(xPos + 30, yPos - 31)] = color;
}