#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 20, yPos)] = color;
	Result[int2(xPos + 21, yPos)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 3)] = color;
	Result[int2(xPos + 6, yPos - 3)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 19)] = color;
	Result[int2(xPos + 34, yPos - 19)] = color;
	Result[int2(xPos + 35, yPos - 19)] = color;
	Result[int2(xPos, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 40, yPos - 20)] = color;
	Result[int2(xPos + 41, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 40, yPos - 21)] = color;
	Result[int2(xPos + 41, yPos - 21)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
	Result[int2(xPos + 8, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 23)] = color;
	Result[int2(xPos + 9, yPos - 23)] = color;
	Result[int2(xPos + 18, yPos - 32)] = color;
	Result[int2(xPos + 19, yPos - 33)] = color;
	Result[int2(xPos + 19, yPos - 34)] = color;
	Result[int2(xPos + 37, yPos - 34)] = color;
	Result[int2(xPos + 39, yPos - 34)] = color;
	Result[int2(xPos + 18, yPos - 35)] = color;
	Result[int2(xPos + 19, yPos - 35)] = color;
	Result[int2(xPos + 38, yPos - 35)] = color;
	Result[int2(xPos + 39, yPos - 35)] = color;
	Result[int2(xPos + 38, yPos - 36)] = color;
	Result[int2(xPos + 34, yPos - 37)] = color;
	Result[int2(xPos + 35, yPos - 38)] = color;
	Result[int2(xPos + 36, yPos - 38)] = color;
	Result[int2(xPos + 34, yPos - 39)] = color;
	Result[int2(xPos + 35, yPos - 39)] = color;
	Result[int2(xPos + 20, yPos - 40)] = color;
	Result[int2(xPos + 21, yPos - 40)] = color;
	Result[int2(xPos + 20, yPos - 41)] = color;
	Result[int2(xPos + 21, yPos - 41)] = color;
}