#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 5, yPos)] = color;
	Result[int2(xPos + 7, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 4, yPos - 8)] = color;
	Result[int2(xPos + 6, yPos - 8)] = color;
	Result[int2(xPos + 7, yPos - 8)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 15)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 16)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 8, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 12, yPos - 23)] = color;
	Result[int2(xPos + 13, yPos - 23)] = color;
	Result[int2(xPos + 15, yPos - 23)] = color;
	Result[int2(xPos + 8, yPos - 24)] = color;
	Result[int2(xPos + 9, yPos - 24)] = color;
	Result[int2(xPos + 12, yPos - 24)] = color;
	Result[int2(xPos + 13, yPos - 24)] = color;
	Result[int2(xPos + 15, yPos - 24)] = color;
	Result[int2(xPos + 16, yPos - 24)] = color;
	Result[int2(xPos + 16, yPos - 25)] = color;
	Result[int2(xPos + 8, yPos - 26)] = color;
	Result[int2(xPos + 9, yPos - 26)] = color;
	Result[int2(xPos + 8, yPos - 27)] = color;
	Result[int2(xPos + 9, yPos - 27)] = color;
	Result[int2(xPos + 15, yPos - 27)] = color;
	Result[int2(xPos + 16, yPos - 27)] = color;
	Result[int2(xPos + 15, yPos - 28)] = color;
	Result[int2(xPos + 16, yPos - 28)] = color;
	Result[int2(xPos + 8, yPos - 29)] = color;
	Result[int2(xPos + 8, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 30)] = color;
	Result[int2(xPos + 11, yPos - 30)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 15, yPos - 30)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 31)] = color;
	Result[int2(xPos + 11, yPos - 31)] = color;
	Result[int2(xPos + 12, yPos - 31)] = color;
	Result[int2(xPos + 14, yPos - 31)] = color;
	Result[int2(xPos + 15, yPos - 31)] = color;
}