#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos + 6, yPos - 4)] = color;
	Result[int2(xPos + 28, yPos - 4)] = color;
	Result[int2(xPos + 29, yPos - 4)] = color;
	Result[int2(xPos + 28, yPos - 5)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 26, yPos - 6)] = color;
	Result[int2(xPos + 28, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 7)] = color;
	Result[int2(xPos + 26, yPos - 7)] = color;
	Result[int2(xPos + 27, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 8)] = color;
	Result[int2(xPos + 21, yPos - 8)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 7, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 21, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 21, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos + 25, yPos - 15)] = color;
	Result[int2(xPos + 26, yPos - 15)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
}