#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 30, yPos - 4)] = color;
	Result[int2(xPos + 28, yPos - 5)] = color;
	Result[int2(xPos + 29, yPos - 5)] = color;
	Result[int2(xPos + 30, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 6)] = color;
	Result[int2(xPos + 27, yPos - 7)] = color;
	Result[int2(xPos + 28, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 21, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 21, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 14)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 20, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 22, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 6, yPos - 27)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 5, yPos - 28)] = color;
	Result[int2(xPos + 7, yPos - 28)] = color;
	Result[int2(xPos + 5, yPos - 29)] = color;
	Result[int2(xPos + 4, yPos - 30)] = color;
	Result[int2(xPos + 5, yPos - 30)] = color;
}