#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 4)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 14, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 11, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 23, yPos - 5)] = color;
	Result[int2(xPos + 11, yPos - 6)] = color;
	Result[int2(xPos + 12, yPos - 6)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 6)] = color;
	Result[int2(xPos + 21, yPos - 6)] = color;
	Result[int2(xPos + 23, yPos - 6)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 11, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 13, yPos - 7)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 24, yPos - 7)] = color;
	Result[int2(xPos + 33, yPos - 7)] = color;
	Result[int2(xPos + 34, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos + 35, yPos - 8)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 10)] = color;
	Result[int2(xPos + 36, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 19, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 15)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 14, yPos - 23)] = color;
	Result[int2(xPos + 15, yPos - 23)] = color;
	Result[int2(xPos + 15, yPos - 24)] = color;
	Result[int2(xPos + 12, yPos - 25)] = color;
	Result[int2(xPos + 13, yPos - 25)] = color;
	Result[int2(xPos + 14, yPos - 25)] = color;
	Result[int2(xPos + 12, yPos - 26)] = color;
}