#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (2 * xMult), yPos)] = color;
	Result[int2(xPos + (3 * xMult), yPos)] = color;
	Result[int2(xPos + (4 * xMult), yPos)] = color;
	Result[int2(xPos + (35 * xMult), yPos)] = color;
	Result[int2(xPos + (36 * xMult), yPos)] = color;
	Result[int2(xPos + (51 * xMult), yPos)] = color;
	Result[int2(xPos + (52 * xMult), yPos)] = color;
	Result[int2(xPos + (83 * xMult), yPos)] = color;
	Result[int2(xPos + (84 * xMult), yPos)] = color;
	Result[int2(xPos + (85 * xMult), yPos)] = color;
	Result[int2(xPos + (36 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos, yPos - (2 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos, yPos - (3 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos, yPos - (4 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (87 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (11 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (75 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (76 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (82 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (11 * yMult))] = color;
}