#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 3)] = color;
	Result[int2(xPos + 9, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 17, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 16, yPos - 6)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 8, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 8, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 18)] = color;
	Result[int2(xPos + 22, yPos - 19)] = color;
	Result[int2(xPos + 23, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 2, yPos - 26)] = color;
	Result[int2(xPos + 4, yPos - 26)] = color;
	Result[int2(xPos + 16, yPos - 26)] = color;
	Result[int2(xPos + 3, yPos - 27)] = color;
	Result[int2(xPos + 4, yPos - 27)] = color;
	Result[int2(xPos + 15, yPos - 27)] = color;
	Result[int2(xPos + 16, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
	Result[int2(xPos + 23, yPos - 27)] = color;
	Result[int2(xPos + 24, yPos - 27)] = color;
	Result[int2(xPos + 14, yPos - 28)] = color;
	Result[int2(xPos + 15, yPos - 29)] = color;
	Result[int2(xPos + 16, yPos - 29)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 21, yPos - 36)] = color;
	Result[int2(xPos + 22, yPos - 36)] = color;
	Result[int2(xPos + 7, yPos - 37)] = color;
	Result[int2(xPos + 8, yPos - 37)] = color;
	Result[int2(xPos + 21, yPos - 37)] = color;
	Result[int2(xPos + 23, yPos - 37)] = color;
	Result[int2(xPos + 7, yPos - 38)] = color;
	Result[int2(xPos + 8, yPos - 38)] = color;
	Result[int2(xPos + 23, yPos - 38)] = color;
	Result[int2(xPos + 23, yPos - 39)] = color;
	Result[int2(xPos + 24, yPos - 39)] = color;
	Result[int2(xPos + 15, yPos - 40)] = color;
	Result[int2(xPos + 16, yPos - 40)] = color;
	Result[int2(xPos + 15, yPos - 41)] = color;
	Result[int2(xPos + 16, yPos - 42)] = color;
	Result[int2(xPos + 17, yPos - 42)] = color;
	Result[int2(xPos + 18, yPos - 42)] = color;
	Result[int2(xPos + 18, yPos - 43)] = color;
}