#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 14, yPos)] = color;
	Result[int2(xPos + 15, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 23, yPos)] = color;
	Result[int2(xPos + 24, yPos)] = color;
	Result[int2(xPos + 27, yPos)] = color;
	Result[int2(xPos + 28, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 3)] = color;
	Result[int2(xPos + 16, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 22, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 17, yPos - 5)] = color;
	Result[int2(xPos + 22, yPos - 5)] = color;
	Result[int2(xPos + 23, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
	Result[int2(xPos, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 14, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 24, yPos - 7)] = color;
	Result[int2(xPos + 25, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 14, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 8)] = color;
	Result[int2(xPos + 18, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 37, yPos - 15)] = color;
	Result[int2(xPos + 38, yPos - 15)] = color;
	Result[int2(xPos + 39, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos + 40, yPos - 16)] = color;
	Result[int2(xPos + 29, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 36, yPos - 17)] = color;
	Result[int2(xPos + 37, yPos - 17)] = color;
	Result[int2(xPos + 41, yPos - 17)] = color;
	Result[int2(xPos + 29, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 38, yPos - 18)] = color;
	Result[int2(xPos + 39, yPos - 18)] = color;
	Result[int2(xPos + 41, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 19)] = color;
	Result[int2(xPos + 39, yPos - 19)] = color;
	Result[int2(xPos + 31, yPos - 30)] = color;
	Result[int2(xPos + 32, yPos - 30)] = color;
	Result[int2(xPos + 38, yPos - 30)] = color;
	Result[int2(xPos + 39, yPos - 30)] = color;
	Result[int2(xPos + 31, yPos - 31)] = color;
	Result[int2(xPos + 32, yPos - 31)] = color;
	Result[int2(xPos + 38, yPos - 31)] = color;
	Result[int2(xPos + 39, yPos - 31)] = color;
}