#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 6)] = color;
	Result[int2(xPos + 12, yPos - 6)] = color;
	Result[int2(xPos + 14, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 12, yPos - 7)] = color;
	Result[int2(xPos + 13, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 21, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 18)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 8, yPos - 24)] = color;
	Result[int2(xPos + 9, yPos - 24)] = color;
	Result[int2(xPos + 18, yPos - 24)] = color;
	Result[int2(xPos + 19, yPos - 24)] = color;
	Result[int2(xPos + 7, yPos - 25)] = color;
	Result[int2(xPos + 9, yPos - 25)] = color;
	Result[int2(xPos + 18, yPos - 25)] = color;
	Result[int2(xPos + 7, yPos - 26)] = color;
	Result[int2(xPos + 8, yPos - 26)] = color;
	Result[int2(xPos + 19, yPos - 26)] = color;
	Result[int2(xPos + 20, yPos - 26)] = color;
	Result[int2(xPos + 21, yPos - 26)] = color;
	Result[int2(xPos + 21, yPos - 27)] = color;
	Result[int2(xPos + 10, yPos - 28)] = color;
	Result[int2(xPos + 11, yPos - 28)] = color;
	Result[int2(xPos + 10, yPos - 29)] = color;
	Result[int2(xPos + 11, yPos - 30)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 31)] = color;
}