#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (29 * xMult), yPos)] = color;
	Result[int2(xPos + (31 * xMult), yPos)] = color;
	Result[int2(xPos + (30 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos, yPos - (13 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (99 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos, yPos - (15 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (101 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (83 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (84 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (90 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (91 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (92 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (93 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (81 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (56 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (80 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (77 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (20 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (26 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (21 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (27 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (78 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (79 * xMult), yPos - (28 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (34 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (35 * yMult))] = color;
}