#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 3)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 30, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 29, yPos - 14)] = color;
	Result[int2(xPos + 31, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 13, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 21, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 20)] = color;
	Result[int2(xPos + 30, yPos - 20)] = color;
	Result[int2(xPos + 29, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 21)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 14, yPos - 29)] = color;
	Result[int2(xPos + 20, yPos - 29)] = color;
	Result[int2(xPos + 21, yPos - 29)] = color;
	Result[int2(xPos + 13, yPos - 30)] = color;
	Result[int2(xPos + 15, yPos - 30)] = color;
	Result[int2(xPos + 20, yPos - 30)] = color;
	Result[int2(xPos + 13, yPos - 31)] = color;
	Result[int2(xPos + 14, yPos - 31)] = color;
	Result[int2(xPos + 21, yPos - 31)] = color;
	Result[int2(xPos + 22, yPos - 31)] = color;
	Result[int2(xPos + 23, yPos - 31)] = color;
	Result[int2(xPos + 23, yPos - 32)] = color;
}