#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 13, yPos)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 34, yPos - 3)] = color;
	Result[int2(xPos + 35, yPos - 3)] = color;
	Result[int2(xPos + 34, yPos - 4)] = color;
	Result[int2(xPos + 35, yPos - 4)] = color;
	Result[int2(xPos + 8, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 9, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 8, yPos - 8)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 39, yPos - 9)] = color;
	Result[int2(xPos + 40, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 10)] = color;
	Result[int2(xPos + 28, yPos - 10)] = color;
	Result[int2(xPos + 29, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 39, yPos - 10)] = color;
	Result[int2(xPos + 43, yPos - 10)] = color;
	Result[int2(xPos + 44, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 28, yPos - 11)] = color;
	Result[int2(xPos + 41, yPos - 11)] = color;
	Result[int2(xPos + 44, yPos - 11)] = color;
	Result[int2(xPos + 28, yPos - 12)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 30, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 41, yPos - 12)] = color;
	Result[int2(xPos + 42, yPos - 12)] = color;
	Result[int2(xPos + 43, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 14)] = color;
	Result[int2(xPos + 40, yPos - 14)] = color;
	Result[int2(xPos + 41, yPos - 14)] = color;
	Result[int2(xPos, yPos - 15)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 40, yPos - 15)] = color;
	Result[int2(xPos + 42, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 41, yPos - 16)] = color;
	Result[int2(xPos + 42, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 17)] = color;
	Result[int2(xPos + 36, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 18)] = color;
	Result[int2(xPos + 37, yPos - 18)] = color;
	Result[int2(xPos + 35, yPos - 19)] = color;
	Result[int2(xPos + 37, yPos - 19)] = color;
	Result[int2(xPos + 36, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 10, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 10, yPos - 22)] = color;
	Result[int2(xPos + 33, yPos - 22)] = color;
	Result[int2(xPos + 34, yPos - 22)] = color;
	Result[int2(xPos + 34, yPos - 23)] = color;
	Result[int2(xPos + 31, yPos - 24)] = color;
	Result[int2(xPos + 32, yPos - 24)] = color;
	Result[int2(xPos + 33, yPos - 24)] = color;
	Result[int2(xPos + 31, yPos - 25)] = color;
}