#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 28, yPos)] = color;
	Result[int2(xPos + 29, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 28, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos + 24, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 5, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos + 25, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 10, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos + 20, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 8)] = color;
	Result[int2(xPos + 18, yPos - 8)] = color;
	Result[int2(xPos + 20, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 20, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 9, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 19, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 18, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 11, yPos - 21)] = color;
	Result[int2(xPos + 18, yPos - 21)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 10, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 22)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
	Result[int2(xPos + 4, yPos - 24)] = color;
	Result[int2(xPos + 5, yPos - 24)] = color;
	Result[int2(xPos + 24, yPos - 24)] = color;
	Result[int2(xPos + 25, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 25)] = color;
	Result[int2(xPos + 4, yPos - 25)] = color;
	Result[int2(xPos + 5, yPos - 25)] = color;
	Result[int2(xPos + 24, yPos - 25)] = color;
	Result[int2(xPos + 25, yPos - 25)] = color;
	Result[int2(xPos + 27, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
	Result[int2(xPos + 28, yPos - 26)] = color;
	Result[int2(xPos + 4, yPos - 27)] = color;
	Result[int2(xPos + 25, yPos - 27)] = color;
	Result[int2(xPos, yPos - 28)] = color;
	Result[int2(xPos + 1, yPos - 28)] = color;
	Result[int2(xPos + 3, yPos - 28)] = color;
	Result[int2(xPos + 26, yPos - 28)] = color;
	Result[int2(xPos + 28, yPos - 28)] = color;
	Result[int2(xPos + 29, yPos - 28)] = color;
	Result[int2(xPos, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 29)] = color;
	Result[int2(xPos + 28, yPos - 29)] = color;
	Result[int2(xPos + 29, yPos - 29)] = color;
}