#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 14, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 14, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 9, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 23, yPos - 12)] = color;
	Result[int2(xPos + 24, yPos - 12)] = color;
	Result[int2(xPos + 26, yPos - 12)] = color;
	Result[int2(xPos + 27, yPos - 12)] = color;
	Result[int2(xPos, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 12, yPos - 14)] = color;
	Result[int2(xPos + 24, yPos - 14)] = color;
	Result[int2(xPos + 25, yPos - 14)] = color;
	Result[int2(xPos + 26, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 25, yPos - 15)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 39, yPos - 17)] = color;
	Result[int2(xPos + 40, yPos - 17)] = color;
	Result[int2(xPos + 5, yPos - 18)] = color;
	Result[int2(xPos + 39, yPos - 18)] = color;
	Result[int2(xPos + 41, yPos - 18)] = color;
	Result[int2(xPos + 41, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 12, yPos - 20)] = color;
	Result[int2(xPos + 41, yPos - 20)] = color;
	Result[int2(xPos + 42, yPos - 20)] = color;
	Result[int2(xPos + 11, yPos - 21)] = color;
	Result[int2(xPos + 12, yPos - 21)] = color;
	Result[int2(xPos + 18, yPos - 21)] = color;
	Result[int2(xPos + 19, yPos - 21)] = color;
	Result[int2(xPos + 17, yPos - 22)] = color;
	Result[int2(xPos + 19, yPos - 22)] = color;
	Result[int2(xPos + 17, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 24)] = color;
}