#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 25, yPos)] = color;
	Result[int2(xPos + 26, yPos)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 8, yPos - 8)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 4, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 4, yPos - 10)] = color;
	Result[int2(xPos + 22, yPos - 10)] = color;
	Result[int2(xPos + 24, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 7, yPos - 12)] = color;
	Result[int2(xPos + 6, yPos - 13)] = color;
	Result[int2(xPos + 7, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 3, yPos - 16)] = color;
	Result[int2(xPos + 23, yPos - 16)] = color;
	Result[int2(xPos + 24, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 23, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 25, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 25, yPos - 19)] = color;
	Result[int2(xPos + 26, yPos - 19)] = color;
}