#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 64, yPos)] = color;
	Result[int2(xPos + 62, yPos - 1)] = color;
	Result[int2(xPos + 63, yPos - 1)] = color;
	Result[int2(xPos + 63, yPos - 2)] = color;
	Result[int2(xPos + 64, yPos - 2)] = color;
	Result[int2(xPos + 54, yPos - 9)] = color;
	Result[int2(xPos + 54, yPos - 10)] = color;
	Result[int2(xPos + 56, yPos - 10)] = color;
	Result[int2(xPos + 54, yPos - 11)] = color;
	Result[int2(xPos + 55, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 28)] = color;
	Result[int2(xPos + 36, yPos - 28)] = color;
	Result[int2(xPos, yPos - 29)] = color;
	Result[int2(xPos + 1, yPos - 29)] = color;
	Result[int2(xPos + 34, yPos - 29)] = color;
	Result[int2(xPos + 35, yPos - 29)] = color;
	Result[int2(xPos, yPos - 30)] = color;
	Result[int2(xPos + 2, yPos - 30)] = color;
	Result[int2(xPos + 35, yPos - 30)] = color;
	Result[int2(xPos + 36, yPos - 30)] = color;
	Result[int2(xPos + 9, yPos - 37)] = color;
	Result[int2(xPos + 10, yPos - 37)] = color;
	Result[int2(xPos + 26, yPos - 37)] = color;
	Result[int2(xPos + 9, yPos - 38)] = color;
	Result[int2(xPos + 11, yPos - 38)] = color;
	Result[int2(xPos + 26, yPos - 38)] = color;
	Result[int2(xPos + 28, yPos - 38)] = color;
	Result[int2(xPos + 9, yPos - 39)] = color;
	Result[int2(xPos + 26, yPos - 39)] = color;
	Result[int2(xPos + 27, yPos - 39)] = color;
	Result[int2(xPos + 3, yPos - 45)] = color;
	Result[int2(xPos + 4, yPos - 45)] = color;
	Result[int2(xPos + 10, yPos - 45)] = color;
	Result[int2(xPos + 11, yPos - 45)] = color;
	Result[int2(xPos + 2, yPos - 46)] = color;
	Result[int2(xPos + 5, yPos - 46)] = color;
	Result[int2(xPos + 9, yPos - 46)] = color;
	Result[int2(xPos + 12, yPos - 46)] = color;
	Result[int2(xPos + 5, yPos - 48)] = color;
	Result[int2(xPos + 9, yPos - 48)] = color;
	Result[int2(xPos + 17, yPos - 48)] = color;
	Result[int2(xPos + 18, yPos - 48)] = color;
	Result[int2(xPos + 3, yPos - 49)] = color;
	Result[int2(xPos + 11, yPos - 49)] = color;
	Result[int2(xPos + 16, yPos - 49)] = color;
	Result[int2(xPos + 19, yPos - 49)] = color;
	Result[int2(xPos + 3, yPos - 50)] = color;
	Result[int2(xPos + 4, yPos - 50)] = color;
	Result[int2(xPos + 10, yPos - 50)] = color;
	Result[int2(xPos + 11, yPos - 50)] = color;
	Result[int2(xPos + 17, yPos - 50)] = color;
	Result[int2(xPos + 19, yPos - 50)] = color;
	Result[int2(xPos + 6, yPos - 51)] = color;
	Result[int2(xPos + 8, yPos - 51)] = color;
	Result[int2(xPos + 18, yPos - 51)] = color;
	Result[int2(xPos + 2, yPos - 52)] = color;
	Result[int2(xPos + 5, yPos - 52)] = color;
	Result[int2(xPos + 6, yPos - 52)] = color;
	Result[int2(xPos + 8, yPos - 52)] = color;
	Result[int2(xPos + 9, yPos - 52)] = color;
	Result[int2(xPos + 12, yPos - 52)] = color;
	Result[int2(xPos + 1, yPos - 53)] = color;
	Result[int2(xPos + 3, yPos - 53)] = color;
	Result[int2(xPos + 6, yPos - 53)] = color;
	Result[int2(xPos + 8, yPos - 53)] = color;
	Result[int2(xPos + 11, yPos - 53)] = color;
	Result[int2(xPos + 13, yPos - 53)] = color;
	Result[int2(xPos + 22, yPos - 53)] = color;
	Result[int2(xPos + 23, yPos - 53)] = color;
	Result[int2(xPos + 1, yPos - 54)] = color;
	Result[int2(xPos + 4, yPos - 54)] = color;
	Result[int2(xPos + 6, yPos - 54)] = color;
	Result[int2(xPos + 8, yPos - 54)] = color;
	Result[int2(xPos + 10, yPos - 54)] = color;
	Result[int2(xPos + 13, yPos - 54)] = color;
	Result[int2(xPos + 22, yPos - 54)] = color;
	Result[int2(xPos + 5, yPos - 55)] = color;
	Result[int2(xPos + 9, yPos - 55)] = color;
	Result[int2(xPos + 23, yPos - 55)] = color;
	Result[int2(xPos + 24, yPos - 55)] = color;
	Result[int2(xPos + 25, yPos - 55)] = color;
	Result[int2(xPos + 25, yPos - 56)] = color;
}