#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 59)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 58)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 59)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 60)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 20)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 21)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 42)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 43)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 21)) * xMult), (yPos - 44)) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos - 45)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 46)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 14)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 53)) * yMult)] = color;
}