#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 59, yPos)] = color;
	Result[int2(xPos + 58, yPos - 1)] = color;
	Result[int2(xPos + 58, yPos - 2)] = color;
	Result[int2(xPos + 59, yPos - 2)] = color;
	Result[int2(xPos + 60, yPos - 2)] = color;
	Result[int2(xPos + 53, yPos - 6)] = color;
	Result[int2(xPos + 52, yPos - 7)] = color;
	Result[int2(xPos + 52, yPos - 8)] = color;
	Result[int2(xPos + 53, yPos - 8)] = color;
	Result[int2(xPos + 54, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 26)] = color;
	Result[int2(xPos + 8, yPos - 26)] = color;
	Result[int2(xPos + 33, yPos - 26)] = color;
	Result[int2(xPos + 6, yPos - 27)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 32, yPos - 27)] = color;
	Result[int2(xPos + 8, yPos - 28)] = color;
	Result[int2(xPos + 32, yPos - 28)] = color;
	Result[int2(xPos + 33, yPos - 28)] = color;
	Result[int2(xPos + 34, yPos - 28)] = color;
	Result[int2(xPos + 27, yPos - 32)] = color;
	Result[int2(xPos + 26, yPos - 33)] = color;
	Result[int2(xPos + 26, yPos - 34)] = color;
	Result[int2(xPos + 27, yPos - 34)] = color;
	Result[int2(xPos + 28, yPos - 34)] = color;
	Result[int2(xPos + 24, yPos - 42)] = color;
	Result[int2(xPos + 25, yPos - 42)] = color;
	Result[int2(xPos + 20, yPos - 43)] = color;
	Result[int2(xPos + 21, yPos - 43)] = color;
	Result[int2(xPos + 24, yPos - 43)] = color;
	Result[int2(xPos + 25, yPos - 43)] = color;
	Result[int2(xPos + 19, yPos - 44)] = color;
	Result[int2(xPos + 21, yPos - 44)] = color;
	Result[int2(xPos + 20, yPos - 45)] = color;
	Result[int2(xPos + 16, yPos - 46)] = color;
	Result[int2(xPos + 15, yPos - 47)] = color;
	Result[int2(xPos + 17, yPos - 47)] = color;
	Result[int2(xPos + 22, yPos - 47)] = color;
	Result[int2(xPos + 23, yPos - 47)] = color;
	Result[int2(xPos + 14, yPos - 48)] = color;
	Result[int2(xPos + 18, yPos - 48)] = color;
	Result[int2(xPos + 22, yPos - 48)] = color;
	Result[int2(xPos + 13, yPos - 49)] = color;
	Result[int2(xPos + 17, yPos - 49)] = color;
	Result[int2(xPos + 23, yPos - 49)] = color;
	Result[int2(xPos + 24, yPos - 49)] = color;
	Result[int2(xPos + 25, yPos - 49)] = color;
	Result[int2(xPos + 12, yPos - 50)] = color;
	Result[int2(xPos + 16, yPos - 50)] = color;
	Result[int2(xPos + 25, yPos - 50)] = color;
	Result[int2(xPos + 11, yPos - 51)] = color;
	Result[int2(xPos + 15, yPos - 51)] = color;
	Result[int2(xPos + 12, yPos - 52)] = color;
	Result[int2(xPos + 14, yPos - 52)] = color;
	Result[int2(xPos + 13, yPos - 53)] = color;
}