#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 60, yPos)] = color;
	Result[int2(xPos + 60, yPos - 1)] = color;
	Result[int2(xPos + 62, yPos - 1)] = color;
	Result[int2(xPos + 60, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos + 50, yPos - 10)] = color;
	Result[int2(xPos + 50, yPos - 11)] = color;
	Result[int2(xPos + 52, yPos - 11)] = color;
	Result[int2(xPos + 50, yPos - 12)] = color;
	Result[int2(xPos + 51, yPos - 12)] = color;
	Result[int2(xPos + 34, yPos - 26)] = color;
	Result[int2(xPos + 1, yPos - 27)] = color;
	Result[int2(xPos + 34, yPos - 27)] = color;
	Result[int2(xPos + 36, yPos - 27)] = color;
	Result[int2(xPos, yPos - 28)] = color;
	Result[int2(xPos + 1, yPos - 28)] = color;
	Result[int2(xPos + 34, yPos - 28)] = color;
	Result[int2(xPos + 35, yPos - 28)] = color;
	Result[int2(xPos, yPos - 29)] = color;
	Result[int2(xPos + 2, yPos - 29)] = color;
	Result[int2(xPos + 24, yPos - 36)] = color;
	Result[int2(xPos + 11, yPos - 37)] = color;
	Result[int2(xPos + 24, yPos - 37)] = color;
	Result[int2(xPos + 26, yPos - 37)] = color;
	Result[int2(xPos + 10, yPos - 38)] = color;
	Result[int2(xPos + 11, yPos - 38)] = color;
	Result[int2(xPos + 24, yPos - 38)] = color;
	Result[int2(xPos + 25, yPos - 38)] = color;
	Result[int2(xPos + 10, yPos - 39)] = color;
	Result[int2(xPos + 12, yPos - 39)] = color;
	Result[int2(xPos + 16, yPos - 46)] = color;
	Result[int2(xPos + 17, yPos - 46)] = color;
	Result[int2(xPos + 9, yPos - 47)] = color;
	Result[int2(xPos + 10, yPos - 47)] = color;
	Result[int2(xPos + 15, yPos - 47)] = color;
	Result[int2(xPos + 18, yPos - 47)] = color;
	Result[int2(xPos + 9, yPos - 48)] = color;
	Result[int2(xPos + 10, yPos - 48)] = color;
	Result[int2(xPos + 16, yPos - 48)] = color;
	Result[int2(xPos + 18, yPos - 48)] = color;
	Result[int2(xPos + 9, yPos - 49)] = color;
	Result[int2(xPos + 10, yPos - 49)] = color;
	Result[int2(xPos + 17, yPos - 49)] = color;
	Result[int2(xPos + 10, yPos - 50)] = color;
	Result[int2(xPos + 9, yPos - 51)] = color;
	Result[int2(xPos + 11, yPos - 51)] = color;
	Result[int2(xPos + 21, yPos - 51)] = color;
	Result[int2(xPos + 22, yPos - 51)] = color;
	Result[int2(xPos + 8, yPos - 52)] = color;
	Result[int2(xPos + 9, yPos - 52)] = color;
	Result[int2(xPos + 11, yPos - 52)] = color;
	Result[int2(xPos + 21, yPos - 52)] = color;
	Result[int2(xPos + 22, yPos - 53)] = color;
	Result[int2(xPos + 23, yPos - 53)] = color;
	Result[int2(xPos + 24, yPos - 53)] = color;
	Result[int2(xPos + 24, yPos - 54)] = color;
	Result[int2(xPos + 9, yPos - 55)] = color;
	Result[int2(xPos + 10, yPos - 55)] = color;
	Result[int2(xPos + 9, yPos - 56)] = color;
	Result[int2(xPos + 10, yPos - 56)] = color;
}