#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 27, yPos)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 21, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 50, yPos - 6)] = color;
	Result[int2(xPos + 51, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 50, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 48, yPos - 8)] = color;
	Result[int2(xPos + 50, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 36, yPos - 9)] = color;
	Result[int2(xPos + 48, yPos - 9)] = color;
	Result[int2(xPos + 49, yPos - 9)] = color;
	Result[int2(xPos + 14, yPos - 10)] = color;
	Result[int2(xPos + 37, yPos - 10)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 38, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 35, yPos - 12)] = color;
	Result[int2(xPos + 37, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 36, yPos - 13)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 36, yPos - 15)] = color;
	Result[int2(xPos + 14, yPos - 16)] = color;
	Result[int2(xPos + 15, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 20, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 37, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 31, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 38, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 37, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 36, yPos - 19)] = color;
	Result[int2(xPos + 48, yPos - 19)] = color;
	Result[int2(xPos + 49, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 48, yPos - 20)] = color;
	Result[int2(xPos + 50, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 50, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 50, yPos - 22)] = color;
	Result[int2(xPos + 51, yPos - 22)] = color;
}