#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 12, yPos)] = color;
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 25, yPos - 3)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 5)] = color;
	Result[int2(xPos + 24, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 3, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 21, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 12)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 44, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 20)] = color;
	Result[int2(xPos + 45, yPos - 20)] = color;
	Result[int2(xPos + 43, yPos - 21)] = color;
	Result[int2(xPos + 44, yPos - 21)] = color;
	Result[int2(xPos + 61, yPos - 23)] = color;
	Result[int2(xPos + 62, yPos - 23)] = color;
	Result[int2(xPos + 61, yPos - 24)] = color;
	Result[int2(xPos + 63, yPos - 24)] = color;
	Result[int2(xPos + 63, yPos - 25)] = color;
	Result[int2(xPos + 63, yPos - 26)] = color;
	Result[int2(xPos + 64, yPos - 26)] = color;
	Result[int2(xPos + 40, yPos - 27)] = color;
	Result[int2(xPos + 41, yPos - 27)] = color;
	Result[int2(xPos + 41, yPos - 28)] = color;
	Result[int2(xPos + 38, yPos - 29)] = color;
	Result[int2(xPos + 39, yPos - 29)] = color;
	Result[int2(xPos + 40, yPos - 29)] = color;
	Result[int2(xPos + 38, yPos - 30)] = color;
}