#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (61 * xMult), yPos)] = color;
	Result[int2(xPos + (40 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos, yPos - (21 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (3 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (30 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (54 * xMult), yPos - (31 * yMult))] = color;
	Result[int2(xPos + (46 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (55 * xMult), yPos - (32 * yMult))] = color;
	Result[int2(xPos + (45 * xMult), yPos - (33 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (35 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (36 * yMult))] = color;
	Result[int2(xPos + (39 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (40 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (37 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (38 * yMult))] = color;
}