#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos + 24, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 24, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 21, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 21, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 8, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 30, yPos - 9)] = color;
	Result[int2(xPos + 7, yPos - 10)] = color;
	Result[int2(xPos + 9, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 29, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 17, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 21, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 20, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 16)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 16)] = color;
	Result[int2(xPos + 22, yPos - 16)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 36, yPos - 25)] = color;
	Result[int2(xPos + 37, yPos - 25)] = color;
	Result[int2(xPos + 36, yPos - 26)] = color;
	Result[int2(xPos + 37, yPos - 26)] = color;
	Result[int2(xPos + 15, yPos - 28)] = color;
	Result[int2(xPos + 20, yPos - 28)] = color;
	Result[int2(xPos + 21, yPos - 28)] = color;
	Result[int2(xPos + 22, yPos - 28)] = color;
	Result[int2(xPos + 17, yPos - 29)] = color;
	Result[int2(xPos + 21, yPos - 29)] = color;
	Result[int2(xPos + 23, yPos - 29)] = color;
	Result[int2(xPos + 17, yPos - 30)] = color;
	Result[int2(xPos + 16, yPos - 31)] = color;
	Result[int2(xPos + 19, yPos - 31)] = color;
	Result[int2(xPos + 19, yPos - 32)] = color;
	Result[int2(xPos + 22, yPos - 32)] = color;
	Result[int2(xPos + 23, yPos - 32)] = color;
	Result[int2(xPos + 20, yPos - 33)] = color;
	Result[int2(xPos + 21, yPos - 33)] = color;
	Result[int2(xPos + 29, yPos - 33)] = color;
	Result[int2(xPos + 7, yPos - 34)] = color;
	Result[int2(xPos + 8, yPos - 34)] = color;
	Result[int2(xPos + 18, yPos - 34)] = color;
	Result[int2(xPos + 19, yPos - 34)] = color;
	Result[int2(xPos + 28, yPos - 34)] = color;
	Result[int2(xPos + 30, yPos - 34)] = color;
	Result[int2(xPos + 7, yPos - 35)] = color;
	Result[int2(xPos + 8, yPos - 35)] = color;
	Result[int2(xPos + 18, yPos - 35)] = color;
	Result[int2(xPos + 29, yPos - 35)] = color;
	Result[int2(xPos + 15, yPos - 38)] = color;
	Result[int2(xPos + 16, yPos - 38)] = color;
	Result[int2(xPos + 16, yPos - 39)] = color;
	Result[int2(xPos + 13, yPos - 40)] = color;
	Result[int2(xPos + 14, yPos - 40)] = color;
	Result[int2(xPos + 15, yPos - 40)] = color;
	Result[int2(xPos + 13, yPos - 41)] = color;
}