#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 8, yPos)] = color;
	Result[int2(xPos + 13, yPos)] = color;
	Result[int2(xPos + 6, yPos - 1)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 11)] = color;
	Result[int2(xPos + 8, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 13, yPos - 11)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 6, yPos - 12)] = color;
	Result[int2(xPos + 9, yPos - 12)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 22, yPos - 12)] = color;
	Result[int2(xPos + 23, yPos - 12)] = color;
	Result[int2(xPos, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 7, yPos - 13)] = color;
	Result[int2(xPos + 9, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 22, yPos - 13)] = color;
	Result[int2(xPos + 23, yPos - 13)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 20)] = color;
	Result[int2(xPos + 15, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 7, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 14, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 23, yPos - 21)] = color;
	Result[int2(xPos, yPos - 22)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 9, yPos - 22)] = color;
	Result[int2(xPos + 14, yPos - 22)] = color;
	Result[int2(xPos + 17, yPos - 22)] = color;
	Result[int2(xPos + 22, yPos - 22)] = color;
	Result[int2(xPos + 23, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 23)] = color;
	Result[int2(xPos + 8, yPos - 23)] = color;
	Result[int2(xPos + 10, yPos - 23)] = color;
	Result[int2(xPos + 13, yPos - 23)] = color;
	Result[int2(xPos + 15, yPos - 23)] = color;
	Result[int2(xPos + 16, yPos - 23)] = color;
}