#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 61, yPos)] = color;
	Result[int2(xPos + 40, yPos - 1)] = color;
	Result[int2(xPos + 59, yPos - 1)] = color;
	Result[int2(xPos + 60, yPos - 1)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 42, yPos - 2)] = color;
	Result[int2(xPos + 60, yPos - 2)] = color;
	Result[int2(xPos + 61, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 3)] = color;
	Result[int2(xPos + 41, yPos - 3)] = color;
	Result[int2(xPos + 54, yPos - 5)] = color;
	Result[int2(xPos + 44, yPos - 6)] = color;
	Result[int2(xPos + 53, yPos - 6)] = color;
	Result[int2(xPos + 45, yPos - 7)] = color;
	Result[int2(xPos + 46, yPos - 7)] = color;
	Result[int2(xPos + 53, yPos - 7)] = color;
	Result[int2(xPos + 54, yPos - 7)] = color;
	Result[int2(xPos + 55, yPos - 7)] = color;
	Result[int2(xPos + 44, yPos - 8)] = color;
	Result[int2(xPos + 45, yPos - 8)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 14, yPos - 14)] = color;
	Result[int2(xPos + 54, yPos - 14)] = color;
	Result[int2(xPos + 14, yPos - 15)] = color;
	Result[int2(xPos + 15, yPos - 15)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 53, yPos - 15)] = color;
	Result[int2(xPos + 55, yPos - 15)] = color;
	Result[int2(xPos + 53, yPos - 16)] = color;
	Result[int2(xPos + 55, yPos - 16)] = color;
	Result[int2(xPos + 17, yPos - 17)] = color;
	Result[int2(xPos + 18, yPos - 17)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 54, yPos - 17)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 45, yPos - 21)] = color;
	Result[int2(xPos + 44, yPos - 22)] = color;
	Result[int2(xPos + 46, yPos - 22)] = color;
	Result[int2(xPos + 3, yPos - 23)] = color;
	Result[int2(xPos + 4, yPos - 23)] = color;
	Result[int2(xPos + 5, yPos - 23)] = color;
	Result[int2(xPos + 44, yPos - 23)] = color;
	Result[int2(xPos + 46, yPos - 23)] = color;
	Result[int2(xPos + 5, yPos - 24)] = color;
	Result[int2(xPos + 45, yPos - 24)] = color;
	Result[int2(xPos + 4, yPos - 25)] = color;
	Result[int2(xPos + 54, yPos - 30)] = color;
	Result[int2(xPos + 55, yPos - 30)] = color;
	Result[int2(xPos + 44, yPos - 31)] = color;
	Result[int2(xPos + 45, yPos - 31)] = color;
	Result[int2(xPos + 46, yPos - 31)] = color;
	Result[int2(xPos + 53, yPos - 31)] = color;
	Result[int2(xPos + 54, yPos - 31)] = color;
	Result[int2(xPos + 46, yPos - 32)] = color;
	Result[int2(xPos + 55, yPos - 32)] = color;
	Result[int2(xPos + 45, yPos - 33)] = color;
	Result[int2(xPos + 58, yPos - 35)] = color;
	Result[int2(xPos + 59, yPos - 35)] = color;
	Result[int2(xPos + 38, yPos - 36)] = color;
	Result[int2(xPos + 39, yPos - 36)] = color;
	Result[int2(xPos + 57, yPos - 36)] = color;
	Result[int2(xPos + 58, yPos - 36)] = color;
	Result[int2(xPos + 39, yPos - 37)] = color;
	Result[int2(xPos + 40, yPos - 37)] = color;
	Result[int2(xPos + 59, yPos - 37)] = color;
	Result[int2(xPos + 38, yPos - 38)] = color;
}