#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 13, yPos - 1)] = color;
	Result[int2(xPos + 14, yPos - 2)] = color;
	Result[int2(xPos + 13, yPos - 3)] = color;
	Result[int2(xPos + 14, yPos - 3)] = color;
	Result[int2(xPos + 13, yPos - 9)] = color;
	Result[int2(xPos + 14, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 13, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 14, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 12)] = color;
	Result[int2(xPos + 15, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 33, yPos - 14)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 15)] = color;
	Result[int2(xPos + 24, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 23, yPos - 16)] = color;
	Result[int2(xPos + 24, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 50, yPos - 16)] = color;
	Result[int2(xPos + 51, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 33, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 48, yPos - 17)] = color;
	Result[int2(xPos + 51, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 3, yPos - 18)] = color;
	Result[int2(xPos + 12, yPos - 18)] = color;
	Result[int2(xPos + 48, yPos - 18)] = color;
	Result[int2(xPos + 49, yPos - 18)] = color;
	Result[int2(xPos + 50, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 12, yPos - 19)] = color;
	Result[int2(xPos + 14, yPos - 19)] = color;
	Result[int2(xPos + 13, yPos - 20)] = color;
	Result[int2(xPos + 15, yPos - 20)] = color;
	Result[int2(xPos + 48, yPos - 20)] = color;
	Result[int2(xPos + 49, yPos - 20)] = color;
	Result[int2(xPos + 50, yPos - 20)] = color;
	Result[int2(xPos + 13, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 21)] = color;
	Result[int2(xPos + 32, yPos - 21)] = color;
	Result[int2(xPos + 33, yPos - 21)] = color;
	Result[int2(xPos + 34, yPos - 21)] = color;
	Result[int2(xPos + 48, yPos - 21)] = color;
	Result[int2(xPos + 51, yPos - 21)] = color;
	Result[int2(xPos + 13, yPos - 22)] = color;
	Result[int2(xPos + 15, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 50, yPos - 22)] = color;
	Result[int2(xPos + 51, yPos - 22)] = color;
	Result[int2(xPos + 12, yPos - 23)] = color;
	Result[int2(xPos + 14, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 34, yPos - 23)] = color;
	Result[int2(xPos + 12, yPos - 24)] = color;
	Result[int2(xPos + 33, yPos - 24)] = color;
	Result[int2(xPos + 34, yPos - 24)] = color;
}