#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 19, yPos)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 12, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 20, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 7)] = color;
	Result[int2(xPos + 24, yPos - 7)] = color;
	Result[int2(xPos + 6, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 3, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 28, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 13, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos + 27, yPos - 10)] = color;
	Result[int2(xPos + 29, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 14, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 29, yPos - 12)] = color;
	Result[int2(xPos + 30, yPos - 12)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 22, yPos - 14)] = color;
	Result[int2(xPos + 23, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 23, yPos - 15)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 29, yPos - 17)] = color;
	Result[int2(xPos + 30, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
	Result[int2(xPos + 20, yPos - 18)] = color;
	Result[int2(xPos + 29, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 19)] = color;
	Result[int2(xPos + 12, yPos - 19)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
	Result[int2(xPos + 17, yPos - 19)] = color;
	Result[int2(xPos + 18, yPos - 19)] = color;
	Result[int2(xPos + 19, yPos - 19)] = color;
	Result[int2(xPos + 27, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 3, yPos - 20)] = color;
	Result[int2(xPos + 27, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 21)] = color;
	Result[int2(xPos + 24, yPos - 21)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 24, yPos - 22)] = color;
	Result[int2(xPos + 6, yPos - 23)] = color;
	Result[int2(xPos + 24, yPos - 23)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 27)] = color;
	Result[int2(xPos + 10, yPos - 28)] = color;
	Result[int2(xPos + 12, yPos - 28)] = color;
	Result[int2(xPos + 18, yPos - 28)] = color;
	Result[int2(xPos + 20, yPos - 28)] = color;
	Result[int2(xPos + 11, yPos - 29)] = color;
	Result[int2(xPos + 19, yPos - 29)] = color;
}