#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos, yPos)] = color;
	Result[int2(xPos + (3 * xMult), yPos)] = color;
	Result[int2(xPos + (4 * xMult), yPos)] = color;
	Result[int2(xPos + (5 * xMult), yPos)] = color;
	Result[int2(xPos + (6 * xMult), yPos)] = color;
	Result[int2(xPos + (7 * xMult), yPos)] = color;
	Result[int2(xPos + (8 * xMult), yPos)] = color;
	Result[int2(xPos + (9 * xMult), yPos)] = color;
	Result[int2(xPos + (10 * xMult), yPos)] = color;
	Result[int2(xPos + (11 * xMult), yPos)] = color;
	Result[int2(xPos + (12 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (14 * xMult), yPos)] = color;
	Result[int2(xPos + (15 * xMult), yPos)] = color;
	Result[int2(xPos + (16 * xMult), yPos)] = color;
	Result[int2(xPos + (17 * xMult), yPos)] = color;
	Result[int2(xPos + (20 * xMult), yPos)] = color;
	Result[int2(xPos + (21 * xMult), yPos)] = color;
	Result[int2(xPos + (22 * xMult), yPos)] = color;
	Result[int2(xPos + (23 * xMult), yPos)] = color;
	Result[int2(xPos + (26 * xMult), yPos)] = color;
	Result[int2(xPos + (1062732399 * xMult), yPos)] = color;
	Result[int2(xPos + (70 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (6 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (61 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (70 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (16 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (104 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (12 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (44 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (74 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (105 * xMult), yPos - (13 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (42 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (43 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (72 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (73 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (103 * xMult), yPos - (14 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (7 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (15 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (41 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (71 * xMult), yPos - (15 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (60 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (102 * xMult), yPos - (16 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (37 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (38 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (67 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (68 * xMult), yPos - (17 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (9 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (100 * xMult), yPos - (18 * yMult))] = color;
	Result[int2(xPos + (8 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (10 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (57 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (19 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (36 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (52 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (59 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (66 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (98 * xMult), yPos - (20 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (51 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (53 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (58 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (96 * xMult), yPos - (21 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (35 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (65 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (22 * yMult))] = color;
	Result[int2(xPos + (4 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (5 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (33 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (34 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (63 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (64 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (94 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (95 * xMult), yPos - (23 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos + (6 * xMult), yPos - (24 * yMult))] = color;
	Result[int2(xPos, yPos - (25 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (25 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (26 * yMult))] = color;
}