#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 1, yPos)] = color;
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 3, yPos)] = color;
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 16, yPos)] = color;
	Result[int2(xPos + 23, yPos)] = color;
	Result[int2(xPos + 24, yPos)] = color;
	Result[int2(xPos + 25, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 1)] = color;
	Result[int2(xPos + 16, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 18, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 6, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 23, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 6, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 20, yPos - 5)] = color;
	Result[int2(xPos + 23, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 24, yPos - 6)] = color;
}