#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 33, yPos)] = color;
	Result[int2(xPos + 31, yPos - 1)] = color;
	Result[int2(xPos + 33, yPos - 1)] = color;
	Result[int2(xPos + 32, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 56, yPos - 2)] = color;
	Result[int2(xPos + 55, yPos - 3)] = color;
	Result[int2(xPos + 55, yPos - 4)] = color;
	Result[int2(xPos + 56, yPos - 4)] = color;
	Result[int2(xPos + 57, yPos - 4)] = color;
	Result[int2(xPos + 15, yPos - 5)] = color;
	Result[int2(xPos + 17, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 6)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos + 35, yPos - 10)] = color;
	Result[int2(xPos + 35, yPos - 11)] = color;
	Result[int2(xPos + 36, yPos - 11)] = color;
	Result[int2(xPos + 34, yPos - 12)] = color;
	Result[int2(xPos + 38, yPos - 12)] = color;
	Result[int2(xPos + 40, yPos - 12)] = color;
	Result[int2(xPos + 38, yPos - 13)] = color;
	Result[int2(xPos + 39, yPos - 13)] = color;
	Result[int2(xPos + 39, yPos - 14)] = color;
	Result[int2(xPos + 50, yPos - 14)] = color;
	Result[int2(xPos + 52, yPos - 14)] = color;
	Result[int2(xPos + 50, yPos - 15)] = color;
	Result[int2(xPos + 51, yPos - 15)] = color;
	Result[int2(xPos + 51, yPos - 16)] = color;
	Result[int2(xPos + 45, yPos - 19)] = color;
	Result[int2(xPos + 46, yPos - 19)] = color;
	Result[int2(xPos + 44, yPos - 20)] = color;
	Result[int2(xPos + 45, yPos - 20)] = color;
	Result[int2(xPos + 46, yPos - 21)] = color;
	Result[int2(xPos + 18, yPos - 27)] = color;
	Result[int2(xPos + 19, yPos - 27)] = color;
	Result[int2(xPos + 57, yPos - 27)] = color;
	Result[int2(xPos + 58, yPos - 27)] = color;
	Result[int2(xPos + 12, yPos - 28)] = color;
	Result[int2(xPos + 13, yPos - 28)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 20, yPos - 28)] = color;
	Result[int2(xPos + 56, yPos - 28)] = color;
	Result[int2(xPos + 57, yPos - 28)] = color;
	Result[int2(xPos + 13, yPos - 29)] = color;
	Result[int2(xPos + 14, yPos - 29)] = color;
	Result[int2(xPos + 18, yPos - 29)] = color;
	Result[int2(xPos + 58, yPos - 29)] = color;
	Result[int2(xPos + 12, yPos - 30)] = color;
	Result[int2(xPos + 37, yPos - 30)] = color;
	Result[int2(xPos + 38, yPos - 30)] = color;
	Result[int2(xPos + 39, yPos - 30)] = color;
	Result[int2(xPos + 39, yPos - 31)] = color;
	Result[int2(xPos + 19, yPos - 32)] = color;
	Result[int2(xPos + 20, yPos - 32)] = color;
	Result[int2(xPos + 21, yPos - 32)] = color;
	Result[int2(xPos + 38, yPos - 32)] = color;
	Result[int2(xPos + 21, yPos - 33)] = color;
	Result[int2(xPos + 20, yPos - 34)] = color;
	Result[int2(xPos + 39, yPos - 36)] = color;
	Result[int2(xPos + 40, yPos - 36)] = color;
	Result[int2(xPos + 39, yPos - 37)] = color;
	Result[int2(xPos + 41, yPos - 37)] = color;
	Result[int2(xPos + 17, yPos - 38)] = color;
	Result[int2(xPos + 18, yPos - 38)] = color;
	Result[int2(xPos + 19, yPos - 38)] = color;
	Result[int2(xPos + 39, yPos - 38)] = color;
	Result[int2(xPos + 19, yPos - 39)] = color;
	Result[int2(xPos + 18, yPos - 40)] = color;
	Result[int2(xPos + 1, yPos - 48)] = color;
	Result[int2(xPos + 1, yPos - 49)] = color;
	Result[int2(xPos + 2, yPos - 49)] = color;
	Result[int2(xPos, yPos - 50)] = color;
	Result[int2(xPos + 2, yPos - 50)] = color;
}