#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos, yPos - 6)] = color;
	Result[int2(xPos + 2, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 1, yPos - 7)] = color;
	Result[int2(xPos + 2, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 7, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 8)] = color;
	Result[int2(xPos + 6, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 25, yPos - 8)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 26, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 10)] = color;
	Result[int2(xPos + 25, yPos - 10)] = color;
	Result[int2(xPos + 26, yPos - 10)] = color;
	Result[int2(xPos + 24, yPos - 12)] = color;
	Result[int2(xPos + 25, yPos - 12)] = color;
	Result[int2(xPos + 27, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 24, yPos - 13)] = color;
	Result[int2(xPos + 26, yPos - 13)] = color;
	Result[int2(xPos + 27, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 15)] = color;
	Result[int2(xPos + 11, yPos - 15)] = color;
	Result[int2(xPos + 12, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 10, yPos - 16)] = color;
	Result[int2(xPos + 11, yPos - 16)] = color;
	Result[int2(xPos + 12, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
}