#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 9, yPos)] = color;
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 24, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 12, yPos - 2)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 3)] = color;
	Result[int2(xPos + 11, yPos - 3)] = color;
	Result[int2(xPos + 12, yPos - 3)] = color;
	Result[int2(xPos + 21, yPos - 3)] = color;
	Result[int2(xPos + 23, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 21, yPos - 4)] = color;
	Result[int2(xPos + 22, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 16, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 3, yPos - 14)] = color;
	Result[int2(xPos + 15, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 16, yPos - 15)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 35, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 17)] = color;
	Result[int2(xPos + 14, yPos - 17)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 12, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 12, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 12, yPos - 20)] = color;
	Result[int2(xPos + 36, yPos - 24)] = color;
	Result[int2(xPos + 37, yPos - 24)] = color;
	Result[int2(xPos + 39, yPos - 24)] = color;
	Result[int2(xPos + 36, yPos - 25)] = color;
	Result[int2(xPos + 38, yPos - 25)] = color;
	Result[int2(xPos + 39, yPos - 25)] = color;
	Result[int2(xPos + 29, yPos - 27)] = color;
	Result[int2(xPos + 30, yPos - 27)] = color;
	Result[int2(xPos + 29, yPos - 28)] = color;
	Result[int2(xPos + 30, yPos - 28)] = color;
	Result[int2(xPos + 28, yPos - 44)] = color;
	Result[int2(xPos + 29, yPos - 44)] = color;
	Result[int2(xPos + 30, yPos - 44)] = color;
	Result[int2(xPos + 28, yPos - 45)] = color;
	Result[int2(xPos + 27, yPos - 46)] = color;
	Result[int2(xPos + 28, yPos - 46)] = color;
}