#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 11, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 4, yPos - 3)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 5, yPos - 4)] = color;
	Result[int2(xPos + 6, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 9, yPos - 4)] = color;
	Result[int2(xPos + 10, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 3, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 9, yPos - 5)] = color;
	Result[int2(xPos + 10, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 3, yPos - 7)] = color;
	Result[int2(xPos + 4, yPos - 7)] = color;
	Result[int2(xPos + 31, yPos - 7)] = color;
	Result[int2(xPos + 32, yPos - 7)] = color;
	Result[int2(xPos + 31, yPos - 8)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 31, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 10)] = color;
	Result[int2(xPos + 30, yPos - 10)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 36, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 26, yPos - 18)] = color;
	Result[int2(xPos + 27, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 26, yPos - 19)] = color;
	Result[int2(xPos + 27, yPos - 19)] = color;
	Result[int2(xPos, yPos - 20)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 24)] = color;
	Result[int2(xPos + 10, yPos - 24)] = color;
	Result[int2(xPos + 14, yPos - 24)] = color;
	Result[int2(xPos + 15, yPos - 24)] = color;
	Result[int2(xPos + 10, yPos - 25)] = color;
	Result[int2(xPos + 14, yPos - 25)] = color;
	Result[int2(xPos + 7, yPos - 26)] = color;
	Result[int2(xPos + 8, yPos - 26)] = color;
	Result[int2(xPos + 9, yPos - 26)] = color;
	Result[int2(xPos + 15, yPos - 26)] = color;
	Result[int2(xPos + 16, yPos - 26)] = color;
	Result[int2(xPos + 17, yPos - 26)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 17, yPos - 27)] = color;
	Result[int2(xPos + 17, yPos - 28)] = color;
	Result[int2(xPos + 19, yPos - 28)] = color;
	Result[int2(xPos + 18, yPos - 29)] = color;
	Result[int2(xPos + 19, yPos - 29)] = color;
	Result[int2(xPos + 25, yPos - 35)] = color;
	Result[int2(xPos + 26, yPos - 35)] = color;
	Result[int2(xPos + 27, yPos - 35)] = color;
	Result[int2(xPos + 25, yPos - 36)] = color;
	Result[int2(xPos + 24, yPos - 37)] = color;
	Result[int2(xPos + 25, yPos - 37)] = color;
}