#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 18, yPos - 1)] = color;
	Result[int2(xPos + 15, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 2)] = color;
	Result[int2(xPos + 15, yPos - 3)] = color;
	Result[int2(xPos + 36, yPos - 5)] = color;
	Result[int2(xPos + 39, yPos - 5)] = color;
	Result[int2(xPos + 36, yPos - 6)] = color;
	Result[int2(xPos + 35, yPos - 7)] = color;
	Result[int2(xPos + 40, yPos - 7)] = color;
	Result[int2(xPos + 34, yPos - 8)] = color;
	Result[int2(xPos + 36, yPos - 8)] = color;
	Result[int2(xPos + 39, yPos - 8)] = color;
	Result[int2(xPos + 40, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos + 35, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 35, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 6, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 34, yPos - 13)] = color;
	Result[int2(xPos + 35, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 21, yPos - 14)] = color;
	Result[int2(xPos + 22, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 22, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 16, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 21, yPos - 16)] = color;
	Result[int2(xPos + 22, yPos - 16)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 15, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 6, yPos - 18)] = color;
	Result[int2(xPos + 16, yPos - 18)] = color;
	Result[int2(xPos + 17, yPos - 18)] = color;
	Result[int2(xPos + 18, yPos - 18)] = color;
	Result[int2(xPos, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 3, yPos - 19)] = color;
	Result[int2(xPos + 5, yPos - 19)] = color;
	Result[int2(xPos + 4, yPos - 20)] = color;
	Result[int2(xPos + 25, yPos - 23)] = color;
	Result[int2(xPos + 23, yPos - 24)] = color;
	Result[int2(xPos + 24, yPos - 24)] = color;
	Result[int2(xPos + 25, yPos - 24)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 26)] = color;
	Result[int2(xPos + 23, yPos - 26)] = color;
}