#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 46, yPos)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 46, yPos - 1)] = color;
	Result[int2(xPos + 47, yPos - 1)] = color;
	Result[int2(xPos + 48, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 3)] = color;
	Result[int2(xPos + 48, yPos - 3)] = color;
	Result[int2(xPos + 49, yPos - 3)] = color;
	Result[int2(xPos + 40, yPos - 4)] = color;
	Result[int2(xPos + 41, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 18, yPos - 5)] = color;
	Result[int2(xPos + 43, yPos - 5)] = color;
	Result[int2(xPos + 16, yPos - 6)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 42, yPos - 6)] = color;
	Result[int2(xPos + 43, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 15, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 3, yPos - 11)] = color;
	Result[int2(xPos + 4, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 3, yPos - 13)] = color;
	Result[int2(xPos + 4, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 19, yPos - 14)] = color;
	Result[int2(xPos + 33, yPos - 14)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 15)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 22)] = color;
	Result[int2(xPos + 22, yPos - 22)] = color;
	Result[int2(xPos + 24, yPos - 22)] = color;
	Result[int2(xPos + 31, yPos - 22)] = color;
	Result[int2(xPos + 32, yPos - 22)] = color;
	Result[int2(xPos + 21, yPos - 23)] = color;
	Result[int2(xPos + 22, yPos - 23)] = color;
	Result[int2(xPos + 24, yPos - 23)] = color;
	Result[int2(xPos + 25, yPos - 23)] = color;
	Result[int2(xPos + 26, yPos - 23)] = color;
	Result[int2(xPos + 30, yPos - 23)] = color;
	Result[int2(xPos + 32, yPos - 23)] = color;
	Result[int2(xPos + 54, yPos - 23)] = color;
	Result[int2(xPos + 55, yPos - 23)] = color;
	Result[int2(xPos + 27, yPos - 24)] = color;
	Result[int2(xPos + 30, yPos - 24)] = color;
	Result[int2(xPos + 54, yPos - 24)] = color;
	Result[int2(xPos + 56, yPos - 24)] = color;
	Result[int2(xPos + 21, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 25)] = color;
	Result[int2(xPos + 24, yPos - 25)] = color;
	Result[int2(xPos + 25, yPos - 25)] = color;
	Result[int2(xPos + 26, yPos - 25)] = color;
	Result[int2(xPos + 29, yPos - 25)] = color;
	Result[int2(xPos + 30, yPos - 25)] = color;
	Result[int2(xPos + 56, yPos - 25)] = color;
	Result[int2(xPos + 22, yPos - 26)] = color;
	Result[int2(xPos + 24, yPos - 26)] = color;
	Result[int2(xPos + 56, yPos - 26)] = color;
	Result[int2(xPos + 57, yPos - 26)] = color;
	Result[int2(xPos + 10, yPos - 27)] = color;
	Result[int2(xPos + 11, yPos - 27)] = color;
	Result[int2(xPos + 22, yPos - 27)] = color;
	Result[int2(xPos + 24, yPos - 27)] = color;
	Result[int2(xPos + 10, yPos - 28)] = color;
	Result[int2(xPos + 11, yPos - 28)] = color;
	Result[int2(xPos + 23, yPos - 28)] = color;
}