#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 24, yPos)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 1)] = color;
	Result[int2(xPos + 23, yPos - 2)] = color;
	Result[int2(xPos + 24, yPos - 2)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 1, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 4, yPos - 15)] = color;
	Result[int2(xPos + 6, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 36, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 35, yPos - 17)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 20, yPos - 19)] = color;
	Result[int2(xPos + 29, yPos - 19)] = color;
	Result[int2(xPos, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 21, yPos - 20)] = color;
	Result[int2(xPos + 22, yPos - 20)] = color;
	Result[int2(xPos + 28, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 20, yPos - 21)] = color;
	Result[int2(xPos + 21, yPos - 21)] = color;
	Result[int2(xPos + 28, yPos - 21)] = color;
	Result[int2(xPos + 29, yPos - 21)] = color;
	Result[int2(xPos + 30, yPos - 21)] = color;
	Result[int2(xPos + 28, yPos - 27)] = color;
	Result[int2(xPos + 29, yPos - 27)] = color;
	Result[int2(xPos + 27, yPos - 28)] = color;
	Result[int2(xPos + 29, yPos - 28)] = color;
	Result[int2(xPos + 29, yPos - 29)] = color;
	Result[int2(xPos + 37, yPos - 30)] = color;
	Result[int2(xPos + 36, yPos - 31)] = color;
	Result[int2(xPos + 37, yPos - 31)] = color;
	Result[int2(xPos + 36, yPos - 32)] = color;
	Result[int2(xPos + 38, yPos - 32)] = color;
}