#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 2, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 2, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 24, yPos - 8)] = color;
	Result[int2(xPos + 16, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 9)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 14, yPos - 10)] = color;
	Result[int2(xPos + 16, yPos - 10)] = color;
	Result[int2(xPos + 23, yPos - 10)] = color;
	Result[int2(xPos + 15, yPos - 11)] = color;
	Result[int2(xPos + 16, yPos - 11)] = color;
	Result[int2(xPos + 20, yPos - 20)] = color;
	Result[int2(xPos + 21, yPos - 21)] = color;
	Result[int2(xPos + 19, yPos - 22)] = color;
	Result[int2(xPos + 20, yPos - 22)] = color;
	Result[int2(xPos + 21, yPos - 22)] = color;
	Result[int2(xPos + 26, yPos - 26)] = color;
	Result[int2(xPos + 25, yPos - 27)] = color;
	Result[int2(xPos + 26, yPos - 27)] = color;
	Result[int2(xPos + 15, yPos - 28)] = color;
	Result[int2(xPos + 16, yPos - 28)] = color;
	Result[int2(xPos + 17, yPos - 28)] = color;
	Result[int2(xPos + 25, yPos - 28)] = color;
	Result[int2(xPos + 27, yPos - 28)] = color;
	Result[int2(xPos + 17, yPos - 29)] = color;
	Result[int2(xPos + 16, yPos - 30)] = color;
	Result[int2(xPos + 26, yPos - 40)] = color;
	Result[int2(xPos + 25, yPos - 41)] = color;
	Result[int2(xPos + 26, yPos - 41)] = color;
	Result[int2(xPos + 25, yPos - 42)] = color;
	Result[int2(xPos + 27, yPos - 42)] = color;
	Result[int2(xPos + 10, yPos - 43)] = color;
	Result[int2(xPos + 10, yPos - 44)] = color;
	Result[int2(xPos + 11, yPos - 44)] = color;
	Result[int2(xPos + 9, yPos - 45)] = color;
	Result[int2(xPos + 11, yPos - 45)] = color;
}