#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 6, yPos)] = color;
	Result[int2(xPos + 7, yPos - 1)] = color;
	Result[int2(xPos + 5, yPos - 2)] = color;
	Result[int2(xPos + 6, yPos - 2)] = color;
	Result[int2(xPos + 7, yPos - 2)] = color;
	Result[int2(xPos + 18, yPos - 5)] = color;
	Result[int2(xPos + 30, yPos - 5)] = color;
	Result[int2(xPos + 31, yPos - 5)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 20, yPos - 6)] = color;
	Result[int2(xPos + 29, yPos - 6)] = color;
	Result[int2(xPos + 32, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos + 29, yPos - 7)] = color;
	Result[int2(xPos + 31, yPos - 7)] = color;
	Result[int2(xPos + 32, yPos - 7)] = color;
	Result[int2(xPos + 26, yPos - 8)] = color;
	Result[int2(xPos + 27, yPos - 8)] = color;
	Result[int2(xPos + 29, yPos - 8)] = color;
	Result[int2(xPos + 25, yPos - 9)] = color;
	Result[int2(xPos + 27, yPos - 9)] = color;
	Result[int2(xPos + 29, yPos - 9)] = color;
	Result[int2(xPos + 31, yPos - 9)] = color;
	Result[int2(xPos + 32, yPos - 9)] = color;
	Result[int2(xPos + 33, yPos - 9)] = color;
	Result[int2(xPos + 34, yPos - 9)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 11, yPos - 10)] = color;
	Result[int2(xPos + 12, yPos - 10)] = color;
	Result[int2(xPos + 25, yPos - 10)] = color;
	Result[int2(xPos + 35, yPos - 10)] = color;
	Result[int2(xPos + 10, yPos - 11)] = color;
	Result[int2(xPos + 26, yPos - 11)] = color;
	Result[int2(xPos + 27, yPos - 11)] = color;
	Result[int2(xPos + 28, yPos - 11)] = color;
	Result[int2(xPos + 29, yPos - 11)] = color;
	Result[int2(xPos + 31, yPos - 11)] = color;
	Result[int2(xPos + 33, yPos - 11)] = color;
	Result[int2(xPos + 35, yPos - 11)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 33, yPos - 12)] = color;
	Result[int2(xPos + 34, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 13)] = color;
	Result[int2(xPos + 2, yPos - 13)] = color;
	Result[int2(xPos + 28, yPos - 13)] = color;
	Result[int2(xPos + 29, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 14)] = color;
	Result[int2(xPos + 28, yPos - 14)] = color;
	Result[int2(xPos + 31, yPos - 14)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 10, yPos - 15)] = color;
	Result[int2(xPos + 29, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 13, yPos - 18)] = color;
	Result[int2(xPos + 14, yPos - 18)] = color;
	Result[int2(xPos + 15, yPos - 18)] = color;
	Result[int2(xPos + 13, yPos - 19)] = color;
	Result[int2(xPos + 14, yPos - 20)] = color;
}