#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 25)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 12)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 13)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 22)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 23)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 25)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 26)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 77)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 27)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 28)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 29)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 78)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 81)) * xMult), (yPos - 30)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 79)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 80)) * xMult), (yPos - 31)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 32)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 33)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 34)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 32)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 33)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 35)) * yMult)] = color;
	Result[int2((xPos + 34)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 36)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 37)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 38)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 47)) * yMult)] = color;
	Result[int2((xPos + 16)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 48)) * yMult)] = color;
	Result[int2((xPos + 15)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 49)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 50)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 51)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 52)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 53)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos + 26)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 54)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 55)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 46)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 56)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 57)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 57)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 3)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 58)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 59)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 59)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 60)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 62)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 63)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 72)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 72)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 72)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 73)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 75)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 76)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 76)) * yMult)] = color;
	Result[int2((xPos + 50)) * xMult), (yPos - 77)) * yMult)] = color;
	Result[int2((xPos + 51)) * xMult), (yPos - 77)) * yMult)] = color;
	Result[int2((xPos + 52)) * xMult), (yPos - 77)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 83)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 83)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 84)) * yMult)] = color;
	Result[int2((xPos + 57)) * xMult), (yPos - 84)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 85)) * yMult)] = color;
	Result[int2((xPos + 56)) * xMult), (yPos - 85)) * yMult)] = color;
}