#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 82, yPos)] = color;
	Result[int2(xPos + 82, yPos - 1)] = color;
	Result[int2(xPos + 84, yPos - 1)] = color;
	Result[int2(xPos + 82, yPos - 2)] = color;
	Result[int2(xPos + 83, yPos - 2)] = color;
	Result[int2(xPos + 60, yPos - 6)] = color;
	Result[int2(xPos + 58, yPos - 7)] = color;
	Result[int2(xPos + 60, yPos - 7)] = color;
	Result[int2(xPos + 59, yPos - 8)] = color;
	Result[int2(xPos + 60, yPos - 8)] = color;
	Result[int2(xPos + 67, yPos - 9)] = color;
	Result[int2(xPos + 66, yPos - 10)] = color;
	Result[int2(xPos + 66, yPos - 11)] = color;
	Result[int2(xPos + 67, yPos - 11)] = color;
	Result[int2(xPos + 68, yPos - 11)] = color;
	Result[int2(xPos + 65, yPos - 13)] = color;
	Result[int2(xPos + 66, yPos - 14)] = color;
	Result[int2(xPos + 76, yPos - 14)] = color;
	Result[int2(xPos + 64, yPos - 15)] = color;
	Result[int2(xPos + 65, yPos - 15)] = color;
	Result[int2(xPos + 66, yPos - 15)] = color;
	Result[int2(xPos + 75, yPos - 15)] = color;
	Result[int2(xPos + 75, yPos - 16)] = color;
	Result[int2(xPos + 76, yPos - 16)] = color;
	Result[int2(xPos + 77, yPos - 16)] = color;
	Result[int2(xPos + 79, yPos - 17)] = color;
	Result[int2(xPos + 80, yPos - 17)] = color;
	Result[int2(xPos + 81, yPos - 17)] = color;
	Result[int2(xPos + 79, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 38, yPos - 19)] = color;
	Result[int2(xPos + 70, yPos - 19)] = color;
	Result[int2(xPos + 80, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 20)] = color;
	Result[int2(xPos + 2, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 20)] = color;
	Result[int2(xPos + 38, yPos - 20)] = color;
	Result[int2(xPos + 70, yPos - 20)] = color;
	Result[int2(xPos, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 4, yPos - 21)] = color;
	Result[int2(xPos + 5, yPos - 21)] = color;
	Result[int2(xPos + 38, yPos - 21)] = color;
	Result[int2(xPos + 70, yPos - 21)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 66, yPos - 22)] = color;
	Result[int2(xPos + 100, yPos - 22)] = color;
	Result[int2(xPos + 67, yPos - 23)] = color;
	Result[int2(xPos + 98, yPos - 23)] = color;
	Result[int2(xPos + 99, yPos - 23)] = color;
	Result[int2(xPos + 100, yPos - 23)] = color;
	Result[int2(xPos + 65, yPos - 24)] = color;
	Result[int2(xPos + 66, yPos - 24)] = color;
	Result[int2(xPos + 67, yPos - 24)] = color;
	Result[int2(xPos + 97, yPos - 24)] = color;
	Result[int2(xPos + 101, yPos - 24)] = color;
	Result[int2(xPos + 102, yPos - 24)] = color;
	Result[int2(xPos + 96, yPos - 25)] = color;
	Result[int2(xPos + 99, yPos - 25)] = color;
	Result[int2(xPos + 101, yPos - 25)] = color;
	Result[int2(xPos + 103, yPos - 25)] = color;
	Result[int2(xPos + 97, yPos - 26)] = color;
	Result[int2(xPos + 98, yPos - 26)] = color;
	Result[int2(xPos + 99, yPos - 26)] = color;
	Result[int2(xPos + 100, yPos - 26)] = color;
	Result[int2(xPos + 101, yPos - 26)] = color;
	Result[int2(xPos + 103, yPos - 26)] = color;
	Result[int2(xPos + 102, yPos - 27)] = color;
	Result[int2(xPos + 79, yPos - 28)] = color;
	Result[int2(xPos + 80, yPos - 28)] = color;
	Result[int2(xPos + 99, yPos - 28)] = color;
	Result[int2(xPos + 100, yPos - 28)] = color;
	Result[int2(xPos + 101, yPos - 28)] = color;
	Result[int2(xPos + 78, yPos - 29)] = color;
	Result[int2(xPos + 79, yPos - 29)] = color;
	Result[int2(xPos + 99, yPos - 29)] = color;
	Result[int2(xPos + 80, yPos - 30)] = color;
	Result[int2(xPos + 67, yPos - 31)] = color;
	Result[int2(xPos + 68, yPos - 31)] = color;
	Result[int2(xPos + 66, yPos - 32)] = color;
	Result[int2(xPos + 68, yPos - 32)] = color;
	Result[int2(xPos + 68, yPos - 33)] = color;
}