#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 69, yPos)] = color;
	Result[int2(xPos + 71, yPos)] = color;
	Result[int2(xPos + 69, yPos - 2)] = color;
	Result[int2(xPos + 72, yPos - 2)] = color;
	Result[int2(xPos + 71, yPos - 3)] = color;
	Result[int2(xPos + 72, yPos - 3)] = color;
	Result[int2(xPos + 72, yPos - 4)] = color;
	Result[int2(xPos + 69, yPos - 9)] = color;
	Result[int2(xPos + 70, yPos - 9)] = color;
	Result[int2(xPos + 71, yPos - 10)] = color;
	Result[int2(xPos + 69, yPos - 11)] = color;
	Result[int2(xPos + 70, yPos - 11)] = color;
	Result[int2(xPos + 52, yPos - 17)] = color;
	Result[int2(xPos + 54, yPos - 17)] = color;
	Result[int2(xPos + 61, yPos - 17)] = color;
	Result[int2(xPos + 63, yPos - 17)] = color;
	Result[int2(xPos + 51, yPos - 18)] = color;
	Result[int2(xPos + 61, yPos - 18)] = color;
	Result[int2(xPos + 63, yPos - 18)] = color;
	Result[int2(xPos + 52, yPos - 19)] = color;
	Result[int2(xPos + 55, yPos - 19)] = color;
	Result[int2(xPos + 62, yPos - 19)] = color;
	Result[int2(xPos + 54, yPos - 20)] = color;
	Result[int2(xPos + 55, yPos - 20)] = color;
	Result[int2(xPos + 56, yPos - 20)] = color;
	Result[int2(xPos + 44, yPos - 25)] = color;
	Result[int2(xPos + 43, yPos - 26)] = color;
	Result[int2(xPos + 45, yPos - 26)] = color;
	Result[int2(xPos + 43, yPos - 28)] = color;
	Result[int2(xPos + 46, yPos - 28)] = color;
	Result[int2(xPos + 45, yPos - 29)] = color;
	Result[int2(xPos + 46, yPos - 29)] = color;
	Result[int2(xPos + 46, yPos - 30)] = color;
	Result[int2(xPos + 43, yPos - 35)] = color;
	Result[int2(xPos + 44, yPos - 35)] = color;
	Result[int2(xPos + 45, yPos - 36)] = color;
	Result[int2(xPos + 43, yPos - 37)] = color;
	Result[int2(xPos + 44, yPos - 37)] = color;
	Result[int2(xPos + 26, yPos - 43)] = color;
	Result[int2(xPos + 28, yPos - 43)] = color;
	Result[int2(xPos + 35, yPos - 43)] = color;
	Result[int2(xPos + 37, yPos - 43)] = color;
	Result[int2(xPos + 25, yPos - 44)] = color;
	Result[int2(xPos + 35, yPos - 44)] = color;
	Result[int2(xPos + 37, yPos - 44)] = color;
	Result[int2(xPos + 26, yPos - 45)] = color;
	Result[int2(xPos + 29, yPos - 45)] = color;
	Result[int2(xPos + 36, yPos - 45)] = color;
	Result[int2(xPos + 28, yPos - 46)] = color;
	Result[int2(xPos + 29, yPos - 46)] = color;
	Result[int2(xPos + 30, yPos - 46)] = color;
	Result[int2(xPos + 18, yPos - 51)] = color;
	Result[int2(xPos + 17, yPos - 52)] = color;
	Result[int2(xPos + 19, yPos - 52)] = color;
	Result[int2(xPos + 17, yPos - 54)] = color;
	Result[int2(xPos + 20, yPos - 54)] = color;
	Result[int2(xPos + 19, yPos - 55)] = color;
	Result[int2(xPos + 20, yPos - 55)] = color;
	Result[int2(xPos + 20, yPos - 56)] = color;
	Result[int2(xPos + 17, yPos - 61)] = color;
	Result[int2(xPos + 18, yPos - 61)] = color;
	Result[int2(xPos + 19, yPos - 62)] = color;
	Result[int2(xPos + 17, yPos - 63)] = color;
	Result[int2(xPos + 18, yPos - 63)] = color;
	Result[int2(xPos, yPos - 69)] = color;
	Result[int2(xPos + 2, yPos - 69)] = color;
	Result[int2(xPos + 9, yPos - 69)] = color;
	Result[int2(xPos + 11, yPos - 69)] = color;
	Result[int2(xPos + 9, yPos - 70)] = color;
	Result[int2(xPos + 11, yPos - 70)] = color;
	Result[int2(xPos + 77, yPos - 70)] = color;
	Result[int2(xPos, yPos - 71)] = color;
	Result[int2(xPos + 3, yPos - 71)] = color;
	Result[int2(xPos + 10, yPos - 71)] = color;
	Result[int2(xPos + 2, yPos - 72)] = color;
	Result[int2(xPos + 3, yPos - 72)] = color;
	Result[int2(xPos + 4, yPos - 72)] = color;
	Result[int2(xPos + 70, yPos - 77)] = color;
}