#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 8)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 10)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 20)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 27)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 28)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 9)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 38)) * xMult), (yPos - 1)) * yMult)] = color;
}