#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 22, yPos)] = color;
	Result[int2(xPos + 46, yPos)] = color;
	Result[int2(xPos + 22, yPos - 1)] = color;
	Result[int2(xPos + 46, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 11, yPos - 2)] = color;
	Result[int2(xPos + 22, yPos - 2)] = color;
	Result[int2(xPos + 33, yPos - 2)] = color;
	Result[int2(xPos + 34, yPos - 2)] = color;
	Result[int2(xPos + 35, yPos - 2)] = color;
	Result[int2(xPos + 46, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 3)] = color;
	Result[int2(xPos + 2, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 2, yPos - 4)] = color;
	Result[int2(xPos + 7, yPos - 4)] = color;
	Result[int2(xPos + 13, yPos - 4)] = color;
	Result[int2(xPos + 18, yPos - 4)] = color;
	Result[int2(xPos + 19, yPos - 4)] = color;
	Result[int2(xPos + 20, yPos - 4)] = color;
	Result[int2(xPos + 24, yPos - 4)] = color;
	Result[int2(xPos + 25, yPos - 4)] = color;
	Result[int2(xPos + 26, yPos - 4)] = color;
	Result[int2(xPos + 31, yPos - 4)] = color;
	Result[int2(xPos + 37, yPos - 4)] = color;
	Result[int2(xPos + 42, yPos - 4)] = color;
	Result[int2(xPos + 43, yPos - 4)] = color;
	Result[int2(xPos + 44, yPos - 4)] = color;
	Result[int2(xPos + 48, yPos - 4)] = color;
	Result[int2(xPos + 49, yPos - 4)] = color;
	Result[int2(xPos + 50, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 2, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 5)] = color;
	Result[int2(xPos + 13, yPos - 5)] = color;
	Result[int2(xPos + 31, yPos - 5)] = color;
	Result[int2(xPos + 37, yPos - 5)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 13, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 6)] = color;
	Result[int2(xPos + 31, yPos - 6)] = color;
	Result[int2(xPos + 37, yPos - 6)] = color;
	Result[int2(xPos + 46, yPos - 6)] = color;
	Result[int2(xPos + 22, yPos - 7)] = color;
	Result[int2(xPos + 46, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 8)] = color;
	Result[int2(xPos + 10, yPos - 8)] = color;
	Result[int2(xPos + 11, yPos - 8)] = color;
	Result[int2(xPos + 22, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos + 34, yPos - 8)] = color;
	Result[int2(xPos + 35, yPos - 8)] = color;
	Result[int2(xPos + 46, yPos - 8)] = color;
}