#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos + 4)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 63)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 83)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 103)) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 22)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 62)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 82)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 102)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 4)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 4)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 106)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 5)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 64)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 66)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 84)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 86)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 93)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 104)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 107)) * xMult), (yPos - 6)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 65)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 85)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 93)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 95)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 105)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos + 106)) * xMult), (yPos - 7)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 44)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 93)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 94)) * xMult), (yPos - 8)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 45)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 91)) * xMult), (yPos - 9)) * yMult)] = color;
	Result[int2((xPos + 39)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 89)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 90)) * xMult), (yPos - 10)) * yMult)] = color;
	Result[int2((xPos + 40)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 11)) * yMult)] = color;
	Result[int2((xPos + 91)) * xMult), (yPos - 11)) * yMult)] = color;
}