#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 36, yPos)] = color;
	Result[int2(xPos + 42, yPos)] = color;
	Result[int2(xPos + 36, yPos - 1)] = color;
	Result[int2(xPos + 37, yPos - 1)] = color;
	Result[int2(xPos + 41, yPos - 1)] = color;
	Result[int2(xPos + 42, yPos - 1)] = color;
	Result[int2(xPos + 46, yPos - 1)] = color;
	Result[int2(xPos + 47, yPos - 1)] = color;
	Result[int2(xPos + 36, yPos - 2)] = color;
	Result[int2(xPos + 37, yPos - 2)] = color;
	Result[int2(xPos + 41, yPos - 2)] = color;
	Result[int2(xPos + 42, yPos - 2)] = color;
	Result[int2(xPos + 46, yPos - 2)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 51, yPos - 2)] = color;
	Result[int2(xPos + 52, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 3)] = color;
	Result[int2(xPos + 37, yPos - 3)] = color;
	Result[int2(xPos + 41, yPos - 3)] = color;
	Result[int2(xPos + 47, yPos - 3)] = color;
	Result[int2(xPos + 51, yPos - 3)] = color;
	Result[int2(xPos + 52, yPos - 3)] = color;
	Result[int2(xPos, yPos - 4)] = color;
	Result[int2(xPos + 1, yPos - 4)] = color;
	Result[int2(xPos + 17, yPos - 4)] = color;
	Result[int2(xPos + 19, yPos - 4)] = color;
	Result[int2(xPos + 27, yPos - 4)] = color;
	Result[int2(xPos + 28, yPos - 4)] = color;
	Result[int2(xPos, yPos - 5)] = color;
	Result[int2(xPos + 1, yPos - 5)] = color;
	Result[int2(xPos + 19, yPos - 5)] = color;
	Result[int2(xPos + 27, yPos - 5)] = color;
	Result[int2(xPos + 28, yPos - 5)] = color;
	Result[int2(xPos + 58, yPos - 5)] = color;
	Result[int2(xPos + 17, yPos - 6)] = color;
	Result[int2(xPos + 18, yPos - 6)] = color;
	Result[int2(xPos + 19, yPos - 6)] = color;
	Result[int2(xPos + 56, yPos - 6)] = color;
	Result[int2(xPos + 57, yPos - 6)] = color;
	Result[int2(xPos + 58, yPos - 6)] = color;
	Result[int2(xPos + 55, yPos - 7)] = color;
	Result[int2(xPos + 55, yPos - 8)] = color;
	Result[int2(xPos + 56, yPos - 8)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 19, yPos - 10)] = color;
	Result[int2(xPos, yPos - 11)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos, yPos - 12)] = color;
	Result[int2(xPos + 1, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 12)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 17, yPos - 13)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 47, yPos - 13)] = color;
	Result[int2(xPos + 48, yPos - 13)] = color;
	Result[int2(xPos + 49, yPos - 13)] = color;
	Result[int2(xPos + 46, yPos - 14)] = color;
	Result[int2(xPos + 49, yPos - 14)] = color;
	Result[int2(xPos + 57, yPos - 14)] = color;
	Result[int2(xPos + 58, yPos - 14)] = color;
	Result[int2(xPos + 46, yPos - 15)] = color;
	Result[int2(xPos + 57, yPos - 15)] = color;
	Result[int2(xPos + 59, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 59, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 17)] = color;
	Result[int2(xPos + 46, yPos - 17)] = color;
	Result[int2(xPos + 47, yPos - 17)] = color;
	Result[int2(xPos + 48, yPos - 17)] = color;
	Result[int2(xPos + 59, yPos - 17)] = color;
	Result[int2(xPos + 60, yPos - 17)] = color;
	Result[int2(xPos + 31, yPos - 18)] = color;
	Result[int2(xPos + 32, yPos - 18)] = color;
	Result[int2(xPos + 33, yPos - 18)] = color;
	Result[int2(xPos + 47, yPos - 18)] = color;
	Result[int2(xPos + 31, yPos - 19)] = color;
}