#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 17, yPos)] = color;
	Result[int2(xPos + 18, yPos)] = color;
	Result[int2(xPos + 50, yPos)] = color;
	Result[int2(xPos, yPos - 1)] = color;
	Result[int2(xPos + 1, yPos - 1)] = color;
	Result[int2(xPos + 17, yPos - 1)] = color;
	Result[int2(xPos + 19, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 39, yPos - 1)] = color;
	Result[int2(xPos + 40, yPos - 1)] = color;
	Result[int2(xPos + 49, yPos - 1)] = color;
	Result[int2(xPos + 50, yPos - 1)] = color;
	Result[int2(xPos + 66, yPos - 1)] = color;
	Result[int2(xPos + 67, yPos - 1)] = color;
	Result[int2(xPos, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 2)] = color;
	Result[int2(xPos + 27, yPos - 2)] = color;
	Result[int2(xPos + 28, yPos - 2)] = color;
	Result[int2(xPos + 39, yPos - 2)] = color;
	Result[int2(xPos + 40, yPos - 2)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 49, yPos - 2)] = color;
	Result[int2(xPos + 66, yPos - 2)] = color;
	Result[int2(xPos + 67, yPos - 2)] = color;
	Result[int2(xPos + 17, yPos - 3)] = color;
	Result[int2(xPos + 18, yPos - 3)] = color;
	Result[int2(xPos + 19, yPos - 3)] = color;
	Result[int2(xPos + 49, yPos - 3)] = color;
	Result[int2(xPos + 50, yPos - 3)] = color;
	Result[int2(xPos + 53, yPos - 3)] = color;
	Result[int2(xPos + 54, yPos - 3)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 18, yPos - 7)] = color;
	Result[int2(xPos + 19, yPos - 7)] = color;
	Result[int2(xPos + 49, yPos - 7)] = color;
	Result[int2(xPos + 50, yPos - 7)] = color;
	Result[int2(xPos + 53, yPos - 7)] = color;
	Result[int2(xPos + 54, yPos - 7)] = color;
	Result[int2(xPos, yPos - 8)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 19, yPos - 8)] = color;
	Result[int2(xPos + 32, yPos - 8)] = color;
	Result[int2(xPos + 33, yPos - 8)] = color;
	Result[int2(xPos + 34, yPos - 8)] = color;
	Result[int2(xPos + 48, yPos - 8)] = color;
	Result[int2(xPos + 49, yPos - 8)] = color;
	Result[int2(xPos + 66, yPos - 8)] = color;
	Result[int2(xPos + 67, yPos - 8)] = color;
	Result[int2(xPos, yPos - 9)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 9)] = color;
	Result[int2(xPos + 19, yPos - 9)] = color;
	Result[int2(xPos + 49, yPos - 9)] = color;
	Result[int2(xPos + 50, yPos - 9)] = color;
	Result[int2(xPos + 66, yPos - 9)] = color;
	Result[int2(xPos + 67, yPos - 9)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 50, yPos - 10)] = color;
}