#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 25, yPos)] = color;
	Result[int2(xPos + 25, yPos - 1)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 25, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 1, yPos - 9)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 3, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 14)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 19)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 21, yPos - 19)] = color;
	Result[int2(xPos + 7, yPos - 20)] = color;
	Result[int2(xPos + 9, yPos - 20)] = color;
	Result[int2(xPos + 21, yPos - 20)] = color;
	Result[int2(xPos + 23, yPos - 20)] = color;
	Result[int2(xPos + 8, yPos - 21)] = color;
	Result[int2(xPos + 9, yPos - 21)] = color;
	Result[int2(xPos + 21, yPos - 21)] = color;
	Result[int2(xPos + 22, yPos - 21)] = color;
	Result[int2(xPos + 12, yPos - 32)] = color;
	Result[int2(xPos + 13, yPos - 32)] = color;
	Result[int2(xPos + 14, yPos - 32)] = color;
	Result[int2(xPos + 17, yPos - 32)] = color;
	Result[int2(xPos + 18, yPos - 32)] = color;
	Result[int2(xPos + 22, yPos - 32)] = color;
	Result[int2(xPos + 14, yPos - 33)] = color;
	Result[int2(xPos + 18, yPos - 33)] = color;
	Result[int2(xPos + 19, yPos - 33)] = color;
	Result[int2(xPos + 21, yPos - 33)] = color;
	Result[int2(xPos + 22, yPos - 33)] = color;
	Result[int2(xPos + 13, yPos - 34)] = color;
	Result[int2(xPos + 17, yPos - 34)] = color;
	Result[int2(xPos + 21, yPos - 34)] = color;
	Result[int2(xPos + 23, yPos - 34)] = color;
	Result[int2(xPos + 26, yPos - 35)] = color;
	Result[int2(xPos + 25, yPos - 36)] = color;
	Result[int2(xPos + 26, yPos - 36)] = color;
	Result[int2(xPos + 25, yPos - 37)] = color;
	Result[int2(xPos + 27, yPos - 37)] = color;
}