#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 29, yPos)] = color;
	Result[int2(xPos + 27, yPos - 1)] = color;
	Result[int2(xPos + 28, yPos - 1)] = color;
	Result[int2(xPos + 29, yPos - 1)] = color;
	Result[int2(xPos + 26, yPos - 2)] = color;
	Result[int2(xPos + 26, yPos - 3)] = color;
	Result[int2(xPos + 27, yPos - 3)] = color;
	Result[int2(xPos + 3, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 4)] = color;
	Result[int2(xPos + 4, yPos - 5)] = color;
	Result[int2(xPos + 4, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 6, yPos - 7)] = color;
	Result[int2(xPos + 23, yPos - 9)] = color;
	Result[int2(xPos + 24, yPos - 9)] = color;
	Result[int2(xPos + 22, yPos - 10)] = color;
	Result[int2(xPos + 23, yPos - 10)] = color;
	Result[int2(xPos + 23, yPos - 11)] = color;
	Result[int2(xPos + 2, yPos - 15)] = color;
	Result[int2(xPos + 3, yPos - 15)] = color;
	Result[int2(xPos + 4, yPos - 16)] = color;
	Result[int2(xPos + 6, yPos - 16)] = color;
	Result[int2(xPos + 7, yPos - 16)] = color;
	Result[int2(xPos, yPos - 17)] = color;
	Result[int2(xPos + 3, yPos - 17)] = color;
	Result[int2(xPos + 6, yPos - 17)] = color;
	Result[int2(xPos + 7, yPos - 17)] = color;
	Result[int2(xPos + 47, yPos - 17)] = color;
	Result[int2(xPos, yPos - 18)] = color;
	Result[int2(xPos + 2, yPos - 18)] = color;
	Result[int2(xPos + 47, yPos - 18)] = color;
	Result[int2(xPos + 48, yPos - 18)] = color;
	Result[int2(xPos + 1, yPos - 19)] = color;
	Result[int2(xPos + 46, yPos - 19)] = color;
	Result[int2(xPos + 47, yPos - 19)] = color;
	Result[int2(xPos + 1, yPos - 21)] = color;
	Result[int2(xPos + 2, yPos - 21)] = color;
	Result[int2(xPos + 64, yPos - 21)] = color;
	Result[int2(xPos + 65, yPos - 21)] = color;
	Result[int2(xPos + 1, yPos - 22)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 64, yPos - 22)] = color;
	Result[int2(xPos + 66, yPos - 22)] = color;
	Result[int2(xPos + 66, yPos - 23)] = color;
	Result[int2(xPos + 66, yPos - 24)] = color;
	Result[int2(xPos + 67, yPos - 24)] = color;
	Result[int2(xPos + 43, yPos - 25)] = color;
	Result[int2(xPos + 44, yPos - 25)] = color;
	Result[int2(xPos + 44, yPos - 26)] = color;
	Result[int2(xPos + 41, yPos - 27)] = color;
	Result[int2(xPos + 42, yPos - 27)] = color;
	Result[int2(xPos + 43, yPos - 27)] = color;
	Result[int2(xPos + 41, yPos - 28)] = color;
}