#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 5, yPos - 6)] = color;
	Result[int2(xPos + 6, yPos - 6)] = color;
	Result[int2(xPos + 7, yPos - 6)] = color;
	Result[int2(xPos + 8, yPos - 6)] = color;
	Result[int2(xPos + 5, yPos - 7)] = color;
	Result[int2(xPos + 9, yPos - 7)] = color;
	Result[int2(xPos + 5, yPos - 8)] = color;
	Result[int2(xPos + 6, yPos - 9)] = color;
	Result[int2(xPos + 9, yPos - 9)] = color;
	Result[int2(xPos + 10, yPos - 10)] = color;
	Result[int2(xPos + 6, yPos - 11)] = color;
	Result[int2(xPos + 12, yPos - 11)] = color;
	Result[int2(xPos + 5, yPos - 12)] = color;
	Result[int2(xPos + 5, yPos - 13)] = color;
	Result[int2(xPos + 12, yPos - 13)] = color;
	Result[int2(xPos + 5, yPos - 14)] = color;
	Result[int2(xPos + 6, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 14)] = color;
	Result[int2(xPos + 8, yPos - 14)] = color;
	Result[int2(xPos + 9, yPos - 14)] = color;
	Result[int2(xPos + 10, yPos - 14)] = color;
	Result[int2(xPos + 11, yPos - 14)] = color;
	Result[int2(xPos + 5, yPos - 17)] = color;
	Result[int2(xPos + 8, yPos - 17)] = color;
	Result[int2(xPos + 4, yPos - 18)] = color;
	Result[int2(xPos + 8, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 11, yPos - 18)] = color;
	Result[int2(xPos + 4, yPos - 19)] = color;
	Result[int2(xPos + 8, yPos - 19)] = color;
	Result[int2(xPos + 4, yPos - 20)] = color;
	Result[int2(xPos + 5, yPos - 20)] = color;
	Result[int2(xPos + 7, yPos - 20)] = color;
	Result[int2(xPos + 10, yPos - 20)] = color;
	Result[int2(xPos + 6, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 22)] = color;
}