#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2(xPos + (11 * xMult), yPos)] = color;
	Result[int2(xPos + (13 * xMult), yPos)] = color;
	Result[int2(xPos + (11 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (1 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (2 * yMult))] = color;
	Result[int2(xPos, yPos - (3 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (3 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (2 * xMult), yPos - (4 * yMult))] = color;
	Result[int2(xPos + (1 * xMult), yPos - (5 * yMult))] = color;
	Result[int2(xPos + (30 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (7 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (29 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (31 * xMult), yPos - (8 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (18 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (25 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (28 * xMult), yPos - (9 * yMult))] = color;
	Result[int2(xPos + (13 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (19 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (26 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (27 * xMult), yPos - (10 * yMult))] = color;
	Result[int2(xPos + (12 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (14 * xMult), yPos - (11 * yMult))] = color;
	Result[int2(xPos + (17 * xMult), yPos - (11 * yMult))] = color;
}