#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

bool lr;
bool ud;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float xMult = 1;
    float yMult = 1;
	
    if (lr)
    {
        xMult = -1;
    }
	
    if (ud)
    {
        yMult = -1;
    }

	Result[int2((xPos) * xMult), (yPos) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 1)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 2)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 5)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 7)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 11)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 13)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 17)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 19)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 23)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 25)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 29)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 31)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 35)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 37)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 41)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 43)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 47)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 49)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 53)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos + 55)) * xMult), (yPos - 2)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 1)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 6)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 12)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 18)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 24)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 30)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 36)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 42)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 48)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos + 54)) * xMult), (yPos - 3)) * yMult)] = color;
	Result[int2((xPos) * xMult), (yPos - 4)) * yMult)] = color;
}