#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 8, yPos - 1)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 16, yPos - 5)] = color;
	Result[int2(xPos + 15, yPos - 6)] = color;
	Result[int2(xPos + 15, yPos - 7)] = color;
	Result[int2(xPos + 16, yPos - 7)] = color;
	Result[int2(xPos + 17, yPos - 7)] = color;
	Result[int2(xPos + 1, yPos - 8)] = color;
	Result[int2(xPos + 2, yPos - 9)] = color;
	Result[int2(xPos + 18, yPos - 9)] = color;
	Result[int2(xPos, yPos - 10)] = color;
	Result[int2(xPos + 1, yPos - 10)] = color;
	Result[int2(xPos + 2, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 10)] = color;
	Result[int2(xPos + 18, yPos - 10)] = color;
	Result[int2(xPos + 31, yPos - 10)] = color;
	Result[int2(xPos + 32, yPos - 10)] = color;
	Result[int2(xPos + 34, yPos - 10)] = color;
	Result[int2(xPos + 35, yPos - 10)] = color;
	Result[int2(xPos + 17, yPos - 11)] = color;
	Result[int2(xPos + 19, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 11)] = color;
	Result[int2(xPos + 32, yPos - 11)] = color;
	Result[int2(xPos + 33, yPos - 11)] = color;
	Result[int2(xPos + 36, yPos - 11)] = color;
	Result[int2(xPos + 30, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 12)] = color;
	Result[int2(xPos + 36, yPos - 12)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 35, yPos - 13)] = color;
	Result[int2(xPos + 30, yPos - 14)] = color;
	Result[int2(xPos + 35, yPos - 14)] = color;
	Result[int2(xPos + 36, yPos - 14)] = color;
	Result[int2(xPos + 7, yPos - 15)] = color;
	Result[int2(xPos + 9, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 36, yPos - 15)] = color;
	Result[int2(xPos + 8, yPos - 16)] = color;
	Result[int2(xPos + 9, yPos - 16)] = color;
	Result[int2(xPos + 24, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 31, yPos - 16)] = color;
	Result[int2(xPos + 32, yPos - 16)] = color;
	Result[int2(xPos + 34, yPos - 16)] = color;
	Result[int2(xPos + 35, yPos - 16)] = color;
	Result[int2(xPos + 8, yPos - 17)] = color;
	Result[int2(xPos + 24, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 18)] = color;
	Result[int2(xPos + 9, yPos - 19)] = color;
	Result[int2(xPos + 10, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 19)] = color;
	Result[int2(xPos + 11, yPos - 20)] = color;
	Result[int2(xPos + 10, yPos - 21)] = color;
	Result[int2(xPos + 16, yPos - 24)] = color;
	Result[int2(xPos + 17, yPos - 24)] = color;
	Result[int2(xPos + 16, yPos - 25)] = color;
	Result[int2(xPos + 18, yPos - 25)] = color;
	Result[int2(xPos + 16, yPos - 26)] = color;
}