#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 2, yPos)] = color;
	Result[int2(xPos + 4, yPos)] = color;
	Result[int2(xPos + 47, yPos)] = color;
	Result[int2(xPos + 49, yPos)] = color;
	Result[int2(xPos + 3, yPos - 1)] = color;
	Result[int2(xPos + 4, yPos - 1)] = color;
	Result[int2(xPos + 47, yPos - 1)] = color;
	Result[int2(xPos + 48, yPos - 1)] = color;
	Result[int2(xPos + 3, yPos - 2)] = color;
	Result[int2(xPos + 48, yPos - 2)] = color;
	Result[int2(xPos + 19, yPos - 12)] = color;
	Result[int2(xPos + 32, yPos - 12)] = color;
	Result[int2(xPos + 18, yPos - 13)] = color;
	Result[int2(xPos + 19, yPos - 13)] = color;
	Result[int2(xPos + 20, yPos - 13)] = color;
	Result[int2(xPos + 31, yPos - 13)] = color;
	Result[int2(xPos + 32, yPos - 13)] = color;
	Result[int2(xPos + 33, yPos - 13)] = color;
	Result[int2(xPos + 17, yPos - 14)] = color;
	Result[int2(xPos + 18, yPos - 14)] = color;
	Result[int2(xPos + 19, yPos - 14)] = color;
	Result[int2(xPos + 20, yPos - 14)] = color;
	Result[int2(xPos + 21, yPos - 14)] = color;
	Result[int2(xPos + 30, yPos - 14)] = color;
	Result[int2(xPos + 31, yPos - 14)] = color;
	Result[int2(xPos + 32, yPos - 14)] = color;
	Result[int2(xPos + 33, yPos - 14)] = color;
	Result[int2(xPos + 34, yPos - 14)] = color;
	Result[int2(xPos + 17, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 15)] = color;
	Result[int2(xPos + 19, yPos - 15)] = color;
	Result[int2(xPos + 20, yPos - 15)] = color;
	Result[int2(xPos + 21, yPos - 15)] = color;
	Result[int2(xPos + 30, yPos - 15)] = color;
	Result[int2(xPos + 31, yPos - 15)] = color;
	Result[int2(xPos + 32, yPos - 15)] = color;
	Result[int2(xPos + 33, yPos - 15)] = color;
	Result[int2(xPos + 34, yPos - 15)] = color;
	Result[int2(xPos + 18, yPos - 16)] = color;
	Result[int2(xPos + 25, yPos - 16)] = color;
	Result[int2(xPos + 26, yPos - 16)] = color;
	Result[int2(xPos + 33, yPos - 16)] = color;
	Result[int2(xPos + 19, yPos - 17)] = color;
	Result[int2(xPos + 20, yPos - 17)] = color;
	Result[int2(xPos + 21, yPos - 17)] = color;
	Result[int2(xPos + 25, yPos - 17)] = color;
	Result[int2(xPos + 26, yPos - 17)] = color;
	Result[int2(xPos + 30, yPos - 17)] = color;
	Result[int2(xPos + 31, yPos - 17)] = color;
	Result[int2(xPos + 32, yPos - 17)] = color;
	Result[int2(xPos + 22, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 18)] = color;
	Result[int2(xPos + 27, yPos - 18)] = color;
	Result[int2(xPos + 29, yPos - 18)] = color;
	Result[int2(xPos + 24, yPos - 19)] = color;
	Result[int2(xPos + 27, yPos - 19)] = color;
	Result[int2(xPos + 22, yPos - 20)] = color;
	Result[int2(xPos + 29, yPos - 20)] = color;
	Result[int2(xPos + 23, yPos - 21)] = color;
	Result[int2(xPos + 24, yPos - 21)] = color;
	Result[int2(xPos + 25, yPos - 21)] = color;
	Result[int2(xPos + 26, yPos - 21)] = color;
	Result[int2(xPos + 27, yPos - 21)] = color;
	Result[int2(xPos + 28, yPos - 21)] = color;
	Result[int2(xPos + 23, yPos - 22)] = color;
	Result[int2(xPos + 28, yPos - 22)] = color;
	Result[int2(xPos + 7, yPos - 25)] = color;
	Result[int2(xPos + 8, yPos - 25)] = color;
	Result[int2(xPos + 43, yPos - 25)] = color;
	Result[int2(xPos + 44, yPos - 25)] = color;
	Result[int2(xPos + 1, yPos - 26)] = color;
	Result[int2(xPos + 8, yPos - 26)] = color;
	Result[int2(xPos + 9, yPos - 26)] = color;
	Result[int2(xPos + 42, yPos - 26)] = color;
	Result[int2(xPos + 43, yPos - 26)] = color;
	Result[int2(xPos + 50, yPos - 26)] = color;
	Result[int2(xPos + 1, yPos - 27)] = color;
	Result[int2(xPos + 2, yPos - 27)] = color;
	Result[int2(xPos + 7, yPos - 27)] = color;
	Result[int2(xPos + 44, yPos - 27)] = color;
	Result[int2(xPos + 49, yPos - 27)] = color;
	Result[int2(xPos + 50, yPos - 27)] = color;
	Result[int2(xPos, yPos - 28)] = color;
	Result[int2(xPos + 2, yPos - 28)] = color;
	Result[int2(xPos + 49, yPos - 28)] = color;
	Result[int2(xPos + 51, yPos - 28)] = color;
}