#pragma kernel CSMain

RWTexture2D<float4> Result;

float xPos;
float yPos;

float4 color;

[numthreads(1, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	Result[int2(xPos + 10, yPos)] = color;
	Result[int2(xPos + 11, yPos)] = color;
	Result[int2(xPos + 10, yPos - 1)] = color;
	Result[int2(xPos + 8, yPos - 2)] = color;
	Result[int2(xPos + 9, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 2)] = color;
	Result[int2(xPos + 10, yPos - 12)] = color;
	Result[int2(xPos + 11, yPos - 12)] = color;
	Result[int2(xPos + 10, yPos - 13)] = color;
	Result[int2(xPos + 11, yPos - 13)] = color;
	Result[int2(xPos + 1, yPos - 16)] = color;
	Result[int2(xPos + 2, yPos - 16)] = color;
	Result[int2(xPos + 1, yPos - 17)] = color;
	Result[int2(xPos + 2, yPos - 17)] = color;
	Result[int2(xPos + 9, yPos - 17)] = color;
	Result[int2(xPos + 10, yPos - 17)] = color;
	Result[int2(xPos + 8, yPos - 18)] = color;
	Result[int2(xPos + 10, yPos - 18)] = color;
	Result[int2(xPos + 7, yPos - 19)] = color;
	Result[int2(xPos + 8, yPos - 19)] = color;
	Result[int2(xPos + 2, yPos - 22)] = color;
	Result[int2(xPos + 3, yPos - 22)] = color;
	Result[int2(xPos + 3, yPos - 23)] = color;
	Result[int2(xPos, yPos - 24)] = color;
	Result[int2(xPos + 1, yPos - 24)] = color;
	Result[int2(xPos + 2, yPos - 24)] = color;
	Result[int2(xPos, yPos - 25)] = color;
}